#### **Recurrent Neural Networks on Imdb movie dataset:**

1.  The main objective of the problem statement is to perform the recurrent neural networks on imdb movie review dataset and predict whether the movie review is positive or negative.


#### **Steps for implementing Recurrent Neural Networks on IMDB Movie Review Dataset:**


1. Import all the necessary libraries

2. Load Dataset

3. Perform the Pad Sequences

4. Build the RNN Model

5. Compile the RNN Model

6. Train the RNN Model

7. Evaluate the RNN Model

8. Make Predictions on Custom Text

#### **Dataset Description:**

1.  The imdb movie review dataset is a balanced dataset that has 50000 labelled reviews.

2.  It contains 25000 training labelled reviews and testing labelled reviews.

#### **Step 1: Import all the necessary libraries**

In [241]:
import  numpy             as  np
import  pandas            as  pd
import  matplotlib.pyplot as plt
import  seaborn           as sns

from    tensorflow.keras.datasets               import  imdb
from    tensorflow.keras.preprocessing.sequence import  pad_sequences
from    tensorflow.keras.models                 import  Sequential
from    tensorflow.keras.layers                 import  Dense,Dropout,BatchNormalization,Flatten,Embedding,SimpleRNN

#### **OBSERVATIONS:**

1.  numpy ----------->  Calculation of numerical array

2.  pandas --------->   Data Manipulation and Analysis

3.  matplotlib ------>  Performs the data visualization

4.  seaborn  ------->   Performs the data correlation

5.  imdb ----------->   It is an imdb movie review dataset that has 50000 labels.

6.  pad_sequences ------> It makes all the input sequences of equal length for easy training of RNN model.

7.  Sequential -------->  It forms linear stack of RNN layer by layer

8.  Dense ------------->  It forms a dense dimendsional neural network

9.  Dropout ---------->  It helps in removing the overfitting.

10. BatchNormalization ------> It is used to stabilize the convergence and speed up the neural network training.

11.  Flatten --------> It converts the 2d or 3d feature maps into 1d vectors.

12.  Embedding ------->  It forms an embedding layer of RNN over the sequential layer by converting the ineteger word id into dense dimensional vectors.

13. SimpleRNN ------>  It forms a simple recurrent neural network by capturing one word at a time and captures the temporal information.It uses the information of the past state and predicts the future state.

#### **Step 2: Load Dataset**

In [242]:
#### Load the imdb movie review dataset
from tensorflow.keras.datasets import imdb

#### define the vocabulary size of the dictionary
vocab_size=10000

#### load the data and divide it into training and testing data
(X_train, Y_train),(X_test, Y_test)= imdb.load_data(num_words=vocab_size)

In [243]:
#### defining the training data

X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [244]:
Y_train

array([1, 0, 0, ..., 0, 1, 0])

In [245]:
#### defining the testing data
X_test

array([list([1, 591, 202, 14, 31, 6, 717, 10, 10, 2, 2, 5, 4, 360, 7, 4, 177, 5760, 394, 354, 4, 123, 9, 1035, 1035, 1035, 10, 10, 13, 92, 124, 89, 488, 7944, 100, 28, 1668, 14, 31, 23, 27, 7479, 29, 220, 468, 8, 124, 14, 286, 170, 8, 157, 46, 5, 27, 239, 16, 179, 2, 38, 32, 25, 7944, 451, 202, 14, 6, 717]),
       list([1, 14, 22, 3443, 6, 176, 7, 5063, 88, 12, 2679, 23, 1310, 5, 109, 943, 4, 114, 9, 55, 606, 5, 111, 7, 4, 139, 193, 273, 23, 4, 172, 270, 11, 7216, 2, 4, 8463, 2801, 109, 1603, 21, 4, 22, 3861, 8, 6, 1193, 1330, 10, 10, 4, 105, 987, 35, 841, 2, 19, 861, 1074, 5, 1987, 2, 45, 55, 221, 15, 670, 5304, 526, 14, 1069, 4, 405, 5, 2438, 7, 27, 85, 108, 131, 4, 5045, 5304, 3884, 405, 9, 3523, 133, 5, 50, 13, 104, 51, 66, 166, 14, 22, 157, 9, 4, 530, 239, 34, 8463, 2801, 45, 407, 31, 7, 41, 3778, 105, 21, 59, 299, 12, 38, 950, 5, 4521, 15, 45, 629, 488, 2733, 127, 6, 52, 292, 17, 4, 6936, 185, 132, 1988, 5304, 1799, 488, 2693, 47, 6, 392, 173, 4, 2, 4378, 270, 2352, 4, 1500, 7, 

In [246]:
Y_test

array([0, 1, 1, ..., 0, 0, 0])

#### **OBSERVATIONS:**

1.  The imdb movie review function is imported from the datasets module of tensorflow.

2.  Then the vocabulary size of 10000 is defined. It defines the length for the most frequent words in the vocabulary.

3.  Then the imdb data is loaded for the 10,000 most frequent words and then is divided into the training and testing data.

#### **Input Data**

In [247]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (25000,)
Shape of the input testing  data is: (25000,)


#### **OBSERVATIONS:**

1.  There are a total input of 25000  imdb movie review records of training data and 25000 imdb movie review records of testing data.

#### **Output Data**

In [248]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (25000,)
Shape of the output testing  data is: (25000,)


#### **OBSERVATIONS:**

1.  There are a total output of 25000  imdb movie review records of training data and 25000 imdb movie review records of testing data.

#### **Step 3: Perform the Pad Sequences on the inputs**

In [249]:
#### Perform the padding on the input sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences

#### define the maximum length for padding
max_length = 200

In [250]:
X_train

array([list([1, 14, 22, 16, 43, 530, 973, 1622, 1385, 65, 458, 4468, 66, 3941, 4, 173, 36, 256, 5, 25, 100, 43, 838, 112, 50, 670, 2, 9, 35, 480, 284, 5, 150, 4, 172, 112, 167, 2, 336, 385, 39, 4, 172, 4536, 1111, 17, 546, 38, 13, 447, 4, 192, 50, 16, 6, 147, 2025, 19, 14, 22, 4, 1920, 4613, 469, 4, 22, 71, 87, 12, 16, 43, 530, 38, 76, 15, 13, 1247, 4, 22, 17, 515, 17, 12, 16, 626, 18, 2, 5, 62, 386, 12, 8, 316, 8, 106, 5, 4, 2223, 5244, 16, 480, 66, 3785, 33, 4, 130, 12, 16, 38, 619, 5, 25, 124, 51, 36, 135, 48, 25, 1415, 33, 6, 22, 12, 215, 28, 77, 52, 5, 14, 407, 16, 82, 2, 8, 4, 107, 117, 5952, 15, 256, 4, 2, 7, 3766, 5, 723, 36, 71, 43, 530, 476, 26, 400, 317, 46, 7, 4, 2, 1029, 13, 104, 88, 4, 381, 15, 297, 98, 32, 2071, 56, 26, 141, 6, 194, 7486, 18, 4, 226, 22, 21, 134, 476, 26, 480, 5, 144, 30, 5535, 18, 51, 36, 28, 224, 92, 25, 104, 4, 226, 65, 16, 38, 1334, 88, 12, 16, 283, 5, 16, 4472, 113, 103, 32, 15, 16, 5345, 19, 178, 32]),
       list([1, 194, 1153, 194, 8255, 78, 228,

In [251]:
X_test

array([list([1, 591, 202, 14, 31, 6, 717, 10, 10, 2, 2, 5, 4, 360, 7, 4, 177, 5760, 394, 354, 4, 123, 9, 1035, 1035, 1035, 10, 10, 13, 92, 124, 89, 488, 7944, 100, 28, 1668, 14, 31, 23, 27, 7479, 29, 220, 468, 8, 124, 14, 286, 170, 8, 157, 46, 5, 27, 239, 16, 179, 2, 38, 32, 25, 7944, 451, 202, 14, 6, 717]),
       list([1, 14, 22, 3443, 6, 176, 7, 5063, 88, 12, 2679, 23, 1310, 5, 109, 943, 4, 114, 9, 55, 606, 5, 111, 7, 4, 139, 193, 273, 23, 4, 172, 270, 11, 7216, 2, 4, 8463, 2801, 109, 1603, 21, 4, 22, 3861, 8, 6, 1193, 1330, 10, 10, 4, 105, 987, 35, 841, 2, 19, 861, 1074, 5, 1987, 2, 45, 55, 221, 15, 670, 5304, 526, 14, 1069, 4, 405, 5, 2438, 7, 27, 85, 108, 131, 4, 5045, 5304, 3884, 405, 9, 3523, 133, 5, 50, 13, 104, 51, 66, 166, 14, 22, 157, 9, 4, 530, 239, 34, 8463, 2801, 45, 407, 31, 7, 41, 3778, 105, 21, 59, 299, 12, 38, 950, 5, 4521, 15, 45, 629, 488, 2733, 127, 6, 52, 292, 17, 4, 6936, 185, 132, 1988, 5304, 1799, 488, 2693, 47, 6, 392, 173, 4, 2, 4378, 270, 2352, 4, 1500, 7, 

In [252]:
print("Shape of the input training data before padding is:", X_train.shape)
print("Shape of the input testing data  before padding is:", X_test.shape)

Shape of the input training data before padding is: (25000,)
Shape of the input testing data  before padding is: (25000,)


In [253]:
#### perform the padding operation on the input data to make it of the equal length
X_train = pad_sequences(X_train, maxlen=max_length)

X_test  = pad_sequences(X_test,  maxlen=max_length)

In [254]:
print("Shape of the input training data after padding is:",  X_train.shape)
print("Shape of the input testing  data after padding is:",  X_test.shape)

Shape of the input training data after padding is: (25000, 200)
Shape of the input testing  data after padding is: (25000, 200)


In [255]:
X_train

array([[   5,   25,  100, ...,   19,  178,   32],
       [   0,    0,    0, ...,   16,  145,   95],
       [   0,    0,    0, ...,    7,  129,  113],
       ...,
       [   0,    0,    0, ...,    4, 3586,    2],
       [   0,    0,    0, ...,   12,    9,   23],
       [   0,    0,    0, ...,  204,  131,    9]], dtype=int32)

In [256]:
X_test

array([[   0,    0,    0, ...,   14,    6,  717],
       [1987,    2,   45, ...,  125,    4, 3077],
       [4468,  189,    4, ...,    9,   57,  975],
       ...,
       [   0,    0,    0, ...,   21,  846, 5518],
       [   0,    0,    0, ..., 2302,    7,  470],
       [   0,    0,    0, ...,   34, 2005, 2643]], dtype=int32)

#### **OBSERVATIONS:**

1.  Initilally all the input sequences are of the variable sequences.

2.  But after padding all the input sequences are converted into the equal sequences.

3.  Each and every word id is converted into the dense dimensional vectors of the same length of 200.


4.  Padding is done so that

    (a.)  Model Training will become faster.

    (b.)  Batch Processing will not fail.


5.  If padding is not done then the Memory Layout Becomes Difficult


6.  Here padding has been applied on the input and all the inputs are of the equal sequences.


### **Types of Padding**

1.  Pre-padding -------->  Applying the zeros at the beginning of the word vector.

2.  Post-padding ------->  Applying the zeros after the ending of the word vectors.

#### **Step 4: Architecture of Simple RNN:**

Input Review

      ↓

Embedding

      ↓

SimpleRNN

      ↓

Dense

      ↓
      
Prediction

In [257]:
#### Built the RNN Model
model = Sequential([
    #### define the embedding layer
    Embedding(input_dim = 10000, output_dim=32, input_length = max_length)                ,
    #### Apply the SimpleRNN Model on the top of the embedding layer
    SimpleRNN(units=32, activation='tanh')                                                ,
    #### Construct the output layer
    Dense(units=1, activation='sigmoid')
])

In [258]:
model

<Sequential name=sequential_7, built=False>

#### **OBSERVATIONS:**

1.  The RNN Sequential model is built with the help of the following layers :--  

    (a.)  Embedding layer:

        (i) Here the 10000 most frequent words ra econverted into 32 dense dimensional vectors with 200 equal lenth of each.

        (ii) This dense dimensional vector sequence are now processed by SimpleRNN word by word.

    (b.) SimpleRNN layer:

        (i) Here the SimpleRNN has 32 hidden neurons in the layer. Each hidden neurons represents the hidden state.

        (ii) Each hidden state processes the input sequence by using the information of the past state and then predicting for the future state.

        (iii) In this manner the last hidden state summarizes all the sentence review.

        (iv) It also uses the 'tanh' activation function to keep the values bounded and helps in stable learning representations.

    (c.) Output layer:

        (i) Here it has one neuron in the output layer where sigmoid activation function is applied on it to determine whether the movie review is positive or negative.


In [259]:
#### get the summary of the model
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_7 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

#### **Step 5: Compile the RNN Model**

In [260]:
#### Compile the RNN Model
model.compile(
    optimizer = 'adam'                                  ,
    loss      = 'binary_crossentropy'                   ,
    metrics   = ['accuracy']
)

#### **OBSERVATIONS:**

1.  The RNN Model has been made ready for the training with the following parameters:--

    (a.)  optimizer = 'adam' . It is used to update the weights during the backpropogation.

    (b.)  loss = 'binary_crossentropy'. It is used to solve the binary classification problem.

    (c.)  metrics = ['accuracy']. It is used to learn the performance of the model.

#### **Step 6: Train the RNN Model**

In [261]:
#### Train the RNN Model
history = model.fit(
    X_train                            ,
    Y_train                            ,
    epochs           =       5         ,
    batch_size       =       64        ,
    validation_split =       0.2       ,
    verbose          =        1
)

Epoch 1/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 20s 56ms/step - accuracy: 0.6105 - loss: 0.6388 - val_accuracy: 0.7862 - val_loss: 0.4788
Epoch 2/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 18s 59ms/step - accuracy: 0.7942 - loss: 0.4509 - val_accuracy: 0.7568 - val_loss: 0.5044
Epoch 3/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 18s 56ms/step - accuracy: 0.9001 - loss: 0.2462 - val_accuracy: 0.7990 - val_loss: 0.4758
Epoch 4/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 21s 58ms/step - accuracy: 0.9636 - loss: 0.1112 - val_accuracy: 0.7854 - val_loss: 0.5679
Epoch 5/5
313/313 ━━━━━━━━━━━━━━━━━━━━ 18s 58ms/step - accuracy: 0.9880 - loss: 0.0451 - val_accuracy: 0.7926 - val_loss: 0.6409


#### **OBSERVATIONS:**


1.  The RNN Model has been trained with the help of the following parameters:-

(a.) Training data -------> X_train, Y_train

(b.) epochs = 5 ---------> 5 iterations ae needed to train the model

(c.) batch_size = 64 -----> weights get updated after every 64 samples

(d.) validation_split = 0.2 ----> 20 % of the data is used fo validation.

2.  After the model training, the accuracy of the model has increased while the loss function has reduced. So the model is working completely fine

#### **Step 7: Evaluate the RNN Model**

In [262]:
loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)

print(f"Loss: {loss:.4f}")
print(f"Accuracy:{(accuracy)*100.0:.4f}")

Loss: 0.6502
Accuracy:78.7520


####  **OBSERVATIONS:**

1.  After evaluating the RNN Model , the test accuracy of the model is very high while the loss function is very less.

2.  So the model is completely fine

#### **Step 8: Make Predictions on Custom Text**

In [263]:
### Get the index of each and every word

word_index = imdb.get_word_index()

### define the function to encode the words into integers
def encoded_review(text):
  ### get the tokens from the text
  tokens = text.lower().split()

  encoded_text = [
        word_index.get(word, 2) + 3
        if word in word_index
        else 2
        for word in tokens
    ]

  encoded_text = pad_sequences(
        [encoded_text],
        maxlen=max_length
    )

  return encoded_text


### define the sample text
sample_text = "This movie was amazing and the actors were brilliant"


res = encoded_review(sample_text)
print(res)

### Make the predictions from the encoded data
predictions = model.predict(res)[0][0]
print(predictions)


if(predictions > 0.5):
  print("Positive Review")
else:
  print("Negative Review")


[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0  14  20  16 480   5   4 156
   71 530]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 224ms/step
0.9874344
Positive Review
