### Simple Neural Networks:

### Aim:-

The main aim of this project is to predict whether the student has passed(1) or failed(0) based on the number of hours he has studied using simple neural networks


### Steps used in this Algorithm:-

1.  Import  all the necessary libraries

2.  Create a sample dataset

3.  Build ANN model

4.  Compile the ANN Model

5.  Train the ANN Model

6.  Predict the ANN Model

### Step 1:  Import  all the necessary libraries

In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from  tensorflow.keras.models import Sequential
from  tensorflow.keras.layers  import Dense

### Step 2: Create a sample dataset

In [125]:
X = np.array([[2], [4], [6], [8], [10]])   # Study hours
Y = np.array([[0], [0], [1], [1], [1]])    # Pass(1) / Fail(0)

In [126]:
### Independent variables
print(X)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


In [127]:
### Dependent variables
print(Y)

[[0]
 [0]
 [1]
 [1]
 [1]]


### OBSERVATIONS:

1.  The dataset has the input and the output data.

    *  The input data is X. It determines the number of hours studied.


    *    The output data is Y. It specifies whether the Student is passed(1) or is failed(0).





    

### Step 3:  Build ANN model

In [128]:
### Create an object for ANN Model

model = Sequential([
    ### create the first dense neural network
    Dense(4, activation = 'relu', input_shape=(1,))    ,
    ### create the output layer
    Dense(1, activation = 'sigmoid')
]
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


### OBSERVATIONS:

1. The ANN Model is initialized with the help of following :-  

   (a.) Dense -----------> It forms the dense neural network model.

   (b.) activation---------> 'Relu' is an activation function used in the hidden layer that is used to increase the non-linearity of the image.

                             'sigmoid' is another activation function used in the output layer that is used for binary classification.

### Step 4: Compile the ANN Model

In [129]:
model.compile(
    optimizer = 'adam'                    ,
    loss      =  'binary_crossentropy'    ,
    metrics   =  ['accuracy']
)

### OBSERVATIONS:

1.  Here the ANN Model is made ready for training with the help of the following parameters:-

   (a.)  optimizer = 'adam' . It is an optimizer that is used to improve the performance of the model by updating the weights through backpropagation.

   (b.) loss = 'binary_crossentropy' . It is the loss function that predicts how much the predicted value is different from the actual value.

   (c.) metrics = 'accuracy'. It helps in evaluating the perormance of the model.

### Step 5: Train the ANN Model

In [130]:
### Train the model
model.fit(X,Y,epochs=100,verbose=0)

### OBSERVATIONS:

1. The ANN Model is trained with the help of the following parameters:-

    (a.)  epochs -------------> Iterations used to train the model.

    (b.)  verbose -------------> Amount of information printed in the screen while training the model.

### Step 6: Predict the ANN Model

In [131]:
pred = model.predict(X)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step


In [132]:
Y

array([[0],
       [0],
       [1],
       [1],
       [1]])

In [133]:
Y.shape

(5, 1)

In [134]:
print("Predicted Value is:", pred)

Predicted Value is: [[0.69007325]
 [0.85728025]
 [0.94187635]
 [0.9776368 ]
 [0.9915921 ]]


In [135]:
pred.shape

(5, 1)

In [136]:
### Combine the Actual Value and the Predicted Value

df = pd.DataFrame({
    "Actual Value" : Y.flatten()               ,
    "Predicted Value" : pred.flatten()
}
)

In [137]:
df

Actual Value  Predicted Value
0             0         0.690073
1             0         0.857280
2             1         0.941876
3             1         0.977637
4             1         0.991592

### OBSERVATIONS:

1. The above dataset depicts about the comparision value between the Actual value and the Predicted Value.