### Principal Component Analysis

1.  The main aim of the Principal Component Analysis (PCA) is to convert the high dimensional features into 2 dimensional features and capture the maximum variance in the dataset.

2.  Then apply logistic regression on the 2D dataset to visualize the results.

### Steps for the Project:-

1. Import all the necessary libraries

2. Load dataset

3. Perform EDA (basic exploration)

4. Split the dataset into independent and dependent variables

5. Split independent and dependent variables into training and testing data

6. Standardize data

7. Perform Hyper Parameter Tuning to improve the accuracy of the model

8. Best Model Evaluation


### Step 1: Import all the necessary libraries

In [1079]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from   sklearn.datasets        import load_wine
from   sklearn.model_selection import train_test_split,GridSearchCV  ## improvised  model
from   sklearn.preprocessing   import StandardScaler
from   sklearn.decomposition   import PCA
from   sklearn.pipeline        import Pipeline
from   sklearn.svm             import SVC
from   sklearn.metrics         import accuracy_score, confusion_matrix, classification_report

### Step 2: Load dataset

In [1080]:
data = load_wine()


### get the data

print(data.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [1081]:
### get the columns

print(data.feature_names)

['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [1082]:
### Construct the dataframe from the above data and columns

df = pd.DataFrame(data.data, columns = data.feature_names)

In [1083]:
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [1084]:
### Adding the target to the dataset

df['target'] = data.target

In [1085]:
### Display the dataframe

df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  target  
0                            3.92   1065.0       0  
1                            3.40   1050.0       0  
2                            3.17   1185.0       0  
3                            3.45   1480.0       0  
4                            2.93    735.0       0  
..                            ...      ...     ...  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2  

[178 rows x 14 columns]

### OBSERVATIONS:

1. The above dataset depicts about the wine quality features.

2. Based on the above wine quality, we need to predict the category of the wine(target) as the output.

### Step 3:-  Perform EDA (basic exploration)

In [1086]:
### get all the total records in the dataset

print("Total records in the dataset is:", len(df))

Total records in the dataset is: 178


In [1087]:
### get the shape of the dataset

print(df.shape)

(178, 14)


In [1088]:
### get the top five rows of the dataset

print(df.head())

   alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  target  
0          

In [1089]:
### get the bottom five rows of the dataset

print(df.tail())

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
173        0.61                  0.52             1.06              7.7  0.64   
174        0.75                  0.43             1.41              7.3  0.70   
175        0.69                  0.43             1.35             10.2  0.59   
176        0.68                  0.53             1.46              9.3  0.60   
177        0.76                  0.56             1.35              9.2  0.61   

     od280/od315_of_diluted_wines  pro

In [1090]:
### get all the columns used in the dataset

df.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

In [1091]:
### get the information about the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  targe

### OBSERVATIONS:

1. All the above input features are numerical in nature.

2. The output feature is integer in nature.

In [1092]:
## Get the descriptive statistics of the dataset

df.describe()

alcohol  malic_acid         ash  alcalinity_of_ash   magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

       color_intensity         hue  od280/od315_of_diluted_wines      proline  \
count       178.000000  178.000000                    178.000000   178.000000   
mean          5.058090    0.957449                      2.611685   746.893258   
std           2.318286    0.228572                      0.709990   314.907474   
min           1.280000    0.480000                      1.270000   278.000000   
25%           3.220000    0.782500                      1.937500   500.500000   
50%           4.690000    0.965000                      2.780000   673.500000   
75%           6.200000    1.120000                      3.170000   985.000000   
max          13.000000    1.710000                      4.000000  1680.000000   

           target  
count  178.000000  
mean     0.938202  
std      0.775035  
min      0.000000  
25%      0.000000  
50%      1.000000  
75%      2.000000  
max      2.000000

### OBSERVATIONS:

1. The above dataset depicts about the statistical summary about the dataset.

In [1093]:
### Check if there are any NULL Values in the dataset

df.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

### OBSERVATIONS:

1.  There are no NULL Values in the dataset.

In [1094]:
### Check for any duplicates in the dataset

df[df.duplicated()]

Empty DataFrame
Columns: [alcohol, malic_acid, ash, alcalinity_of_ash, magnesium, total_phenols, flavanoids, nonflavanoid_phenols, proanthocyanins, color_intensity, hue, od280/od315_of_diluted_wines, proline, target]
Index: []

### OBSERVATIONS:

1.  There are no duplicate records in the dataset.

In [1095]:
### Rename 'od280/od315_of_diluted_wines' to 'od280_od315_ratio' 

df.rename(columns={
    'od280/od315_of_diluted_wines': 'diluted_wines'
}, inplace=True)

In [1096]:
df

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     diluted_wines  proline  target  
0             3.92   1065.0       0  
1             3.40   1050.0       0  
2             3.17   1185.0       0  
3             3.45   1480.0       0  
4             2.93    735.0       0  
..             ...      ...     ...  
173           1.74    740.0       2  
174           1.56    750.0       2  
175           1.56    835.0       2  
176           1.62    840.0       2  
177           1.60    560.0       2  

[178 rows x 14 columns]

In [1097]:
### Get the total count of all the categories of the target

df['target'].value_counts()

target
1    71
0    59
2    48
Name: count, dtype: int64

### OBSERVATIONS:

1.  There are three categories of the target used in the dataset.

### Step 4: Split the dataset into independent and dependent variables

In [1098]:
X = df.drop(columns='target',axis=1)

Y = df['target']

In [1099]:
print(X)

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyan

In [1100]:
print(Y)

0      0
1      0
2      0
3      0
4      0
      ..
173    2
174    2
175    2
176    2
177    2
Name: target, Length: 178, dtype: int64


### Step 5: Split independent and dependent variables into training and testing data

In [1101]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.25,random_state=42,stratify=Y)

In [1102]:
X_train

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
8      14.83        1.64  2.17               14.0       97.0           2.80   
104    12.51        1.73  1.98               20.5       85.0           2.20   
36     13.28        1.64  2.84               15.5      110.0           2.60   
78     12.33        0.99  1.95               14.8      136.0           1.90   
2      13.16        2.36  2.67               18.6      101.0           2.80   
..       ...         ...   ...                ...        ...            ...   
63     12.37        1.13  2.16               19.0       87.0           3.50   
150    13.50        3.12  2.62               24.0      123.0           1.40   
34     13.51        1.80  2.65               19.0      110.0           2.35   
154    12.58        1.29  2.10               20.0      103.0           1.48   
159    13.48        1.67  2.64               22.5       89.0           2.60   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
8          2.98                  0.29             1.98             5.20  1.08   
104        1.92                  0.32             1.48             2.94  1.04   
36         2.68                  0.34             1.36             4.60  1.09   
78         1.85                  0.35             2.76             3.40  1.06   
2          3.24                  0.30             2.81             5.68  1.03   
..          ...                   ...              ...              ...   ...   
63         3.10                  0.19             1.87             4.45  1.22   
150        1.57                  0.22             1.25             8.60  0.59   
34         2.53                  0.29             1.54             4.20  1.10   
154        0.58                  0.53             1.40             7.60  0.58   
159        1.10                  0.52             2.29            11.75  0.57   

     diluted_wines  proline  
8             2.85   1045.0  
104           3.57    672.0  
36            2.78    880.0  
78            2.31    750.0  
2             3.17   1185.0  
..             ...      ...  
63            2.87    420.0  
150           1.30    500.0  
34            2.87   1095.0  
154           1.55    640.0  
159           1.78    620.0  

[133 rows x 13 columns]

In [1103]:
X_test

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
35     13.48        1.81  2.41               20.5      100.0           2.70   
93     12.29        2.83  2.22               18.0       88.0           2.45   
7      14.06        2.15  2.61               17.6      121.0           2.60   
28     13.87        1.90  2.80               19.4      107.0           2.95   
87     11.65        1.67  2.62               26.0       88.0           1.92   
42     13.88        1.89  2.59               15.0      101.0           3.25   
18     14.19        1.59  2.48               16.5      108.0           3.30   
60     12.33        1.10  2.28               16.0      101.0           2.05   
98     12.37        1.07  2.10               18.5       88.0           3.52   
130    12.86        1.35  2.32               18.0      122.0           1.51   
62     13.67        1.25  1.92               18.0       94.0           2.10   
102    12.34        2.45  2.46               21.0       98.0           2.56   
155    13.17        5.19  2.32               22.0       93.0           1.74   
156    13.84        4.12  2.38               19.5       89.0           1.80   
20     14.06        1.63  2.28               16.0      126.0           3.00   
121    11.56        2.05  3.23               28.5      119.0           3.18   
64     12.17        1.45  2.53               19.0      104.0           1.89   
22     13.71        1.86  2.36               16.6      101.0           2.61   
51     13.83        1.65  2.60               17.2       94.0           2.45   
177    14.13        4.10  2.74               24.5       96.0           2.05   
143    13.62        4.95  2.35               20.0       92.0           2.00   
164    13.78        2.76  2.30               22.0       90.0           1.35   
23     12.85        1.60  2.52               17.8       95.0           2.48   
48     14.10        2.02  2.40               18.8      103.0           2.75   
118    12.77        3.43  1.98               16.0       80.0           1.63   
84     11.84        0.89  2.58               18.0       94.0           2.20   
10     14.10        2.16  2.30               18.0      105.0           2.95   
66     13.11        1.01  1.70               15.0       78.0           2.98   
38     13.07        1.50  2.10               15.5       98.0           2.40   
94     11.62        1.99  2.28               18.0       98.0           3.02   
39     14.22        3.99  2.51               13.2      128.0           3.00   
132    12.81        2.31  2.40               24.0       98.0           1.15   
100    12.08        2.08  1.70               17.5       97.0           2.23   
138    13.49        3.59  2.19               19.5       88.0           1.62   
173    13.71        5.65  2.45               20.5       95.0           1.68   
108    12.22        1.29  1.94               19.0       92.0           2.36   
58     13.72        1.43  2.50               16.7      108.0           3.40   
176    13.17        2.59  2.37               20.0      120.0           1.65   
134    12.51        1.24  2.25               17.5       85.0           2.00   
105    12.42        2.55  2.27               22.0       90.0           1.68   
166    13.45        3.70  2.60               23.0      111.0           1.70   
112    11.76        2.68  2.92               20.0      103.0           1.75   
14     14.38        1.87  2.38               12.0      102.0           3.30   
129    12.04        4.30  2.38               22.0       80.0           2.10   
76     13.03        0.90  1.71               16.0       86.0           1.95   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
35         2.98                  0.26             1.86             5.10  1.04   
93         2.25                  0.25             1.99             2.15  1.15   
7          2.51                  0.31             1.25             5.05  1.06   
28         2.97                  0.37         

In [1104]:
print("Shape of the input training data is:", X_train.shape)

print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (133, 13)
Shape of the input testing  data is: (45, 13)


In [1105]:
Y_train

8      0
104    1
36     0
78     1
2      0
      ..
63     1
150    2
34     0
154    2
159    2
Name: target, Length: 133, dtype: int64

In [1106]:
Y_test

35     0
93     1
7      0
28     0
87     1
42     0
18     0
60     1
98     1
130    2
62     1
102    1
155    2
156    2
20     0
121    1
64     1
22     0
51     0
177    2
143    2
164    2
23     0
48     0
118    1
84     1
10     0
66     1
38     0
94     1
39     0
132    2
100    1
138    2
173    2
108    1
58     0
176    2
134    2
105    1
166    2
112    1
14     0
129    1
76     1
Name: target, dtype: int64

In [1107]:
print("Shape of the output training data is:", Y_train.shape)

print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (133,)
Shape of the output testing  data is: (45,)


### Step 7: Perform Hyper Parameter Tuning to imrpove the accuracy of the model

In [1108]:
#### Create a Pipeline

pipe = Pipeline(
    [
        ('scaler' , StandardScaler()),
        ('pca'    , PCA())           ,
        ('clf'    , SVC())
    ]
)

In [1109]:
pipe

Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA()), ('clf', SVC())])

In [1110]:
### Define the Hyper parameter tuning

param_grid = {
    'pca__n_components':[0.90,0.95,0.99],
    'clf__C':[0.1,1,10],
    'clf__kernel':['linear','rbf'],
    'clf__gamma':['scale','auto']
}

In [1111]:
param_grid

{'pca__n_components': [0.9, 0.95, 0.99],
 'clf__C': [0.1, 1, 10],
 'clf__kernel': ['linear', 'rbf'],
 'clf__gamma': ['scale', 'auto']}

### OBSERVATIONS:


1.  `pca__n_components` ---------->  Parameter of PCA step         

2.  `clf__C`            ---------->  Parameter of SVM classifier   

3.  `clf__kernel`       ---------->  Type of SVM decision boundary 

4.  `clf__gamma`        ---------->  Kernel influence (for RBF)    


In [1112]:
### Perform the Hyper parameter tuning of the model

grid = GridSearchCV(
    pipe                  ,
    param_grid            ,
    cv = 5                ,
    scoring = 'accuracy'  ,
    n_jobs  = -1 
)

In [1113]:
### Using the object of Hyper parameter model, train the data

grid.fit(X_train, Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('pca', PCA()), ('clf', SVC())]),
             n_jobs=-1,
             param_grid={'clf__C': [0.1, 1, 10],
                         'clf__gamma': ['scale', 'auto'],
                         'clf__kernel': ['linear', 'rbf'],
                         'pca__n_components': [0.9, 0.95, 0.99]},
             scoring='accuracy')

### Step 8: Best Model Evaluation

In [1114]:
### get the best model

best_model = grid.best_estimator_

print("Best Model is:", best_model)

### using the best model, predict the test data

Y_pred = best_model.predict(X_test)

print(Y_pred)

Best Model is: Pipeline(steps=[('scaler', StandardScaler()), ('pca', PCA(n_components=0.99)),
                ('clf', SVC(C=1, kernel='linear'))])
[0 1 0 0 1 0 0 1 1 2 1 1 2 2 0 1 1 0 0 2 1 2 0 0 1 1 0 1 0 1 0 2 1 2 2 1 0
 2 1 1 2 1 0 1 1]


In [1115]:
### get the best parameters

print("Best Parameters:", grid.best_params_)

Best Parameters: {'clf__C': 1, 'clf__gamma': 'scale', 'clf__kernel': 'linear', 'pca__n_components': 0.99}


In [1116]:
print("Accuracy:", accuracy_score(Y_test, Y_pred)*100.0)

Accuracy: 95.55555555555556


In [1117]:
print("\nConfusion Matrix:\n", confusion_matrix(Y_test, Y_pred))


Confusion Matrix:
 [[15  0  0]
 [ 0 18  0]
 [ 0  2 10]]


In [1118]:
print("\nClassification Report:\n", classification_report(Y_test, Y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.90      1.00      0.95        18
           2       1.00      0.83      0.91        12

    accuracy                           0.96        45
   macro avg       0.97      0.94      0.95        45
weighted avg       0.96      0.96      0.95        45



### OBSERVATIONS:

1. By using the hyper parameter tuning, the accuracy of the PCA model has improved from 73.33% to 95.55%