### Linear Algebra

In [285]:
import numpy as np
import pandas as pd

In [286]:
v1 = np.array([2, 3])

v2 = np.array([4, 1])

In [287]:
print(v1)

[2 3]


In [288]:
print(v2)

[4 1]


In [289]:
### Vector Addition


resadd = v1 + v2


print("Vector Addition is :", resadd)

Vector Addition is : [6 4]


In [290]:
### Vector Substraction

ressub = v1 - v2

print("Vector Substraction is:", ressub)

Vector Substraction is: [-2  2]


In [291]:
### Vector Multiplication

resmul = v1 * v2

print("Vector Multiplication is:", resmul)

Vector Multiplication is: [8 3]


In [292]:
### Magniture of a vector

x1 = np.linalg.norm(v1)

print("Magnitude of the first vector is:", x1)

Magnitude of the first vector is: 3.605551275463989


In [293]:
x2 = np.linalg.norm(v2)

print("Magniture of the second vector is:", x2)

Magniture of the second vector is: 4.123105625617661


###  Dot Product

In [294]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot_pro_res = np.dot(v1, v2)

print("Dot Product of two vectors is:", dot_pro_res)

Dot Product of two vectors is: 32


### Matrix Creation

In [295]:
X = np.array([
    [1, 2] ,
    [3, 4] ,
    [5, 6]
])

In [296]:
print(X)

[[1 2]
 [3 4]
 [5 6]]


In [297]:
print("Shape of the matrix is:", X.shape)

Shape of the matrix is: (3, 2)


### Matrix Multiplication

In [298]:
A = np.array([[1, 2],
              [3, 4]])

In [299]:
print(A)

[[1 2]
 [3 4]]


In [300]:
B = np.array([[2, 0],
              [1, 2]])

In [301]:
print(B)

[[2 0]
 [1 2]]


In [302]:
res = np.dot(A,B)

In [303]:
print(res)

[[ 4  4]
 [10  8]]


### Transpose of Matrix

In [304]:
X = np.array([[1, 2, 3],
              [4, 5, 6]])

In [305]:
print(X)

[[1 2 3]
 [4 5 6]]


In [306]:
print("Transpose of the matrix is:", X.T)

Transpose of the matrix is: [[1 4]
 [2 5]
 [3 6]]


### Determinant of Matrix

In [307]:
A = np.array([[1, 2],
              [3, 4]])



print(A)

[[1 2]
 [3 4]]


In [308]:
determinant = np.linalg.det(A)

In [309]:
print("Determinant of the Matrix is:", determinant)

Determinant of the Matrix is: -2.0000000000000004


### Inverse of Matrix

In [310]:
A = np.array([[1, 2],
              [3, 4]])



print("Original Matrix is :", A)

Original Matrix is : [[1 2]
 [3 4]]


In [311]:
res = np.linalg.inv(A)

In [312]:
print("Inverse Matrix is:", res)

Inverse Matrix is: [[-2.   1. ]
 [ 1.5 -0.5]]


### Solving Linear Equations

In [313]:
A = np.array([[3, 1],
              [1, 2]])

b = np.array([9, 8])


x = np.linalg.solve(A,b)

print("Solution is:", x)

Solution is: [2. 3.]
