### Numpy

1.     It stands for Numerical Python.

2.     It is used to work with arrays.

3.     It is used for scientific mathematical computations.

In [2391]:
import numpy as np

### Create a simple list

lists = [10,20,30,40,50]

print(lists)

print("Type of the lists is:", type(lists))

print("==========================================================================================")

### Convert the lists into numpy array

np_array = np.array(lists)

print(np_array)

print("Type of the numpy array is:", type(np_array))

[10, 20, 30, 40, 50]
Type of the lists is: <class 'list'>
[10 20 30 40 50]
Type of the numpy array is: <class 'numpy.ndarray'>


### OBSERVATIONS:

1.  Initially the input is in the form of lists.

2.  Then the lists is converted into the numpy array.

### Numpy


It is a standard library used in Python

It is used with arrays for performing mathematical computations like linear algebra, fourier transformations, matrices

It stands for Numerical Python

### Why use Numpy ?

Ans (i) Unlike arrays, Numpy arrays are used to perform many mathematical computations like linear algebra , fourier transformations etc and is very much faster to process.

### Why is NumPy Faster Than Lists ?

Ans (i) As all the elements in Numpy are stored in one contiguous memory location, so accessing all the elements in numpy array is very easy and can be easily manipulated.

In [2392]:
### Create a simple numpy array

import  numpy  as  np

x = np.array([1,2,3,4,5])

print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2393]:
print(np.__version__)

2.4.2


### Numpy

It is used to work with arrays. The array object in Numpy is called ndarray.

The ndarray is created using array() function.

In [2394]:
import numpy as np 

x = np.array([1,2,3,4,5])

print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### OBSERVATIONS:

1.  ndarray is the type of numpy array

2.  It is created using array()

In [2395]:
### with the help of tuple, create a numpy array

tuple = (1,2,3,4,5)

x = np.array(tuple)

print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays)

### (i) 0-D Arrays

Each element in an array is 0-D Array.

In [2396]:
import numpy as np

ans = np.array(42)

print(ans)

print(type(ans))

42
<class 'numpy.ndarray'>


### (ii) 1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [2397]:
x = [1,2,3,4,5]

print(x)

print(type(x))
print("=======================================")

### convert the list into numpy array

res = np.array(x)

print(res)

print(type(res))

### get the dimensions of the numpy array

print(res.ndim)

[1, 2, 3, 4, 5]
<class 'list'>
[1 2 3 4 5]
<class 'numpy.ndarray'>
1


### (iii) 2-D Arrays.
An array that has 1-D arrays as its elements is called a 2-D array.

It is often used to represent the matrix.

In [2398]:
### Get the numpy array of 2d list

x = [[1,2,3,4],[5,6,7,8]]

print(x)

print(type(x))

print("==========================================")

### convert the lists into numpy array

res = np.array(x)

print(res)

### get the type of the array

print(type(res))

### get the dimensions of the numpt array

print(res.ndim)

[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


### (iii) 3-D arrays

An array that has 2-D arrays (matrices) as its elements is called 3-D array

It is used to represent 3 D Tensor.

In [2399]:
import  numpy  as  np 

x = [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]

print(x)

print(type(x))

print("==========================================")

### Convert the lists into the numpy array

ans = np.array(x)

print(ans)

print(type(ans))

print(ans.ndim)

[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]]
<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


### Check Number of Dimensions

In [2400]:
import numpy as np

a = np.array([1,2,3,4,5])

b = np.array([[1,2,3],[4,5,6]])

c = np.array([[[1,2,3],[4,5,6]]])

d = np.array([[[[1,2,3],[4,5,6]]]])


print(a)
print("Number of dimensions in array a is:", a.ndim)

print(b)
print("Number of dimensions in array b is:", b.ndim)

print(c)
print("Number of dimensions in array c is:", c.ndim)

print(d)
print("Number of dimensions in array d is:", d.ndim)

[1 2 3 4 5]
Number of dimensions in array a is: 1
[[1 2 3]
 [4 5 6]]
Number of dimensions in array b is: 2
[[[1 2 3]
  [4 5 6]]]
Number of dimensions in array c is: 3
[[[[1 2 3]
   [4 5 6]]]]
Number of dimensions in array d is: 4


### Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [2401]:
import numpy as np

### Make the 1-D Array into 5-D
x = np.array([1,2,3,4,5], ndmin=5)

print(x)

print(type(x))

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>


### Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc

In [2402]:
## Get the first element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("First Element in the array is:", x[0])

First Element in the array is: 1


In [2403]:
## Get the second element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("Second Element in the array is:", x[1])

Second Element in the array is: 2


In [2404]:
## Get the third element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("Third Element in the array is:", x[2])

Third Element in the array is: 3


In [2405]:
## Get the fourth element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("Fourth Element in the array is:", x[3])

Fourth Element in the array is: 4


### Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element

In [2406]:
## Access the element on the first row, second column

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr[0][1])

2


In [2407]:
## Access the element on the 2nd row, 5th column

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1][4])

10


### Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element

In [2408]:
## Access the third element of the second array of the first array

import numpy as np 

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0][1][2])

6


### Negative Indexing

Use negative indexing to access an array from the end

In [2409]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr)

print("Last element from the 2nd dimensions is:", arr[1][-1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from the 2nd dimensions is: 10


In [2410]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr[1][1][0])

7


### NumPy Array Slicing:

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [2411]:
## Slice elements from index 1 to index 5 from the following array

import numpy as np 

x = np.array([1,2,3,4,5,6,7])

print(x[1:6])

[2 3 4 5 6]


In [2412]:
## elements from index 4 till the end of the array

print(x[4:])

[5 6 7]


In [2413]:
## Slice elements from the beginning to index 4 (not included)

print(x[:4])

[1 2 3 4]


### Negative Slicing

Use the minus operator to refer to an index from the end

In [2414]:
## Slice from the index 3 from the end to index 1 from the end

print(x[-3:])

[5 6 7]


In [2415]:
## Return every other element from index 1 to index 5

print(x[1:6])

[2 3 4 5 6]


In [2416]:
## Return every other element from the entire array

print(x[::2])

[1 3 5 7]


In [2417]:
## From the second element, slice elements from index 1 to index 4 (not included)

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[:,1:4])

[[2 3 4]
 [7 8 9]]


In [2418]:
## From both elements, return index 2

arr[:,2]

array([3, 8])

In [2419]:
## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

arr[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

### Mathematical Operations in Numpy:

In [2420]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("First Array is:", arr1)
print("Second Array is:", arr2)

### Element Wise Addition

add_res = arr1 + arr2
print("Addition value is:", add_res)

### Element Wise Substraction

sub_res = arr1 - arr2 
print("Substraction value is:", sub_res)

### Element Wise Multiplication

mul_res = arr1 * arr2 
print("Multiplication value is:", mul_res)

### Element Wise Division

div_res = arr1 / arr2 
print("Division value is:", arr1/arr2)

First Array is: [1 2 3 4 5]
Second Array is: [10 20 30 40 50]
Addition value is: [11 22 33 44 55]
Substraction value is: [ -9 -18 -27 -36 -45]
Multiplication value is: [ 10  40  90 160 250]
Division value is: [0.1 0.1 0.1 0.1 0.1]


In [2421]:
## Universal Function
arr=np.array([2,3,4,5,6])

### Square Root of the number
sqr_res = np.sqrt(arr)
print("Square Root of the number is:", sqr_res)

### Exponential value of the number
exp_res = np.exp(arr)
print("Exponential value of the number is:",exp_res)

### Sine value of the number

sin_res = np.sin(arr)
print("Sin value of the number is:", sin_res)

### Log value of the number
log_res = np.log(arr)
print("Natural log of the number is:", log_res)

Square Root of the number is: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential value of the number is: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sin value of the number is: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural log of the number is: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [2422]:
### Statistical Functions

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

### Find out the mean value from the data

means = np.mean(data)
print("Mean value of the data series is:", means)

### Find out the median value from the data
medians = np.median(data)
print("Median value of the data series is:", medians)

### Find out the variance from the data

variance = np.var(data)
print("Variance of the data series is:", variance)

### Find out the standard deviaton from the data

standarddeviation = np.std(data)
print("Standard Deviation of the data series is:", standarddeviation)

Mean value of the data series is: 5.5
Median value of the data series is: 5.5
Variance of the data series is: 8.25
Standard Deviation of the data series is: 2.8722813232690143


In [2423]:
### statistical concepts--Normalization
##to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

### Find out the mean value from the data

means = np.mean(data)
print("Mean value of the data series is:", means)

### Find out the standard deviation from the data

standarddeviation = np.std(data)
print("Standard Deviation of the data series is:", standarddeviation)

### Normalize the data
normalized_data = (data - means)/standarddeviation

print("Normalized data is:", normalized_data)


Mean value of the data series is: 3.0
Standard Deviation of the data series is: 1.4142135623730951
Normalized data is: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### NumPy Array Reshaping

### Reshaping arrays

Reshaping means changing the shape of an array.

We cannot add or remove the number of dimensions in the array through reshaping.

In [2424]:
## Convert the following 1-D array with 12 elements into a 2-D array

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='int')

print("=======================1 Dimensional Array Elements=========================================")

print(x)

print("Number of dimensions in the array is:", x.ndim)

print("=======================2 Dimensional Array Elements ==========================================")

x_new = x.reshape(4,3)

print(x_new)

print("Number of dimensions in the array is:", x_new.ndim)

print("=======================2 Dimensional Array Elements ==========================================")

x_news = x.reshape(3,4)

print(x_news)

print("Number of dimensions in the array is:", x_news.ndim)


=======================1 Dimensional Array Elements=========================================
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Number of dimensions in the array is: 1
=======================2 Dimensional Array Elements ==========================================
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Number of dimensions in the array is: 2
=======================2 Dimensional Array Elements ==========================================
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Number of dimensions in the array is: 2


### Reshape From 1-D to 3-D

In [2425]:
## Convert the following 1-D array with 12 elements into a 3-D array

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='int')

print("=======================1 Dimensional Array Elements=========================================")

print(x)

print("Number of dimensions in the array is:", x.ndim)

print("=======================3 Dimensional Array Elements=========================================")

x_3D = x.reshape(2,2,3)

print(x_3D)

print("Number of dimensions in the array is:", x_3D.ndim)

=======================1 Dimensional Array Elements=========================================
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Number of dimensions in the array is: 1
=======================3 Dimensional Array Elements=========================================
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Number of dimensions in the array is: 3


### Reshape into Row Vector using (1,-1)

In [2426]:
## Convert the following 1-D array with 12 elements into row vector 

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='int')

print("=======================1 Dimensional Array Elements=========================================")

print(x)

print("Number of dimensions in the array is:", x.ndim)

print("Shape of the original array is:", x.shape)

print("======================== Row Vector =========================================================")

x_row = x.reshape(1,-1)

print(x_row)

print("Number of dimensions in the array is:", x_row.ndim)

print("Shape of the reshaped array is:", x_row.shape)

=======================1 Dimensional Array Elements=========================================
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Number of dimensions in the array is: 1
Shape of the original array is: (12,)
======================== Row Vector =========================================================
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Number of dimensions in the array is: 2
Shape of the reshaped array is: (1, 12)


### OBSERVATIONS:

.    (1,-1) is used to convert the vector into the row vector.

###  Reshape into Column Vector using (-1,1)

In [2427]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print('----------------------------Original Array--------------------------------------------------------------')

print(arr)

print(arr.ndim)

print(arr.shape)


print('----------------------------Reshaped Array--------------------------------------------------------------')

arr = arr.reshape(-1,1)

print(arr)

print(arr.ndim)

print(arr.shape)

----------------------------Original Array--------------------------------------------------------------
[1 2 3 4 5]
1
(5,)
----------------------------Reshaped Array--------------------------------------------------------------
[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)


In [2428]:
## Check if the returned array is a copy or a view

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8], dtype = int)
print("----------------Before Reshaping---------------------------------------")
print(x)

print("----------------After Reshaping---------------------------------------")
x = x.reshape(4,2)
print(x)

print("-----------------Replica Data-----------------------------------------")
x = x.base
print(x)

----------------Before Reshaping---------------------------------------
[1 2 3 4 5 6 7 8]
----------------After Reshaping---------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-----------------Replica Data-----------------------------------------
[1 2 3 4 5 6 7 8]


### OBSEVATIONS:

1. base function is used that tells whether the reshaped data is a replica of the original data or not.

2. The Reshaped data is a replica of the original data.

### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array

We can use reshape(-1) to do this.

In [2429]:
## Convert the array into a 1D array

import numpy as np 

print("-----------------------Before Reshaping------------------------------")
x = np.array([[1,2,3,4],[5,6,7,8]], dtype = 'int')

print(x)

print('-----------------------After converting the array into 1D vector--------')

x = x.flatten()

print(x)

-----------------------Before Reshaping------------------------------
[[1 2 3 4]
 [5 6 7 8]]
-----------------------After converting the array into 1D vector--------
[1 2 3 4 5 6 7 8]


## Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array

In [2430]:
import numpy as np

arr = np.array([3, 2, 0, 1])


print("--------------------------------Original Array-----------------------------------------------------------")
print(arr)

print("--------------------------------Sorted Array-------------------------------------------------------------")

arr = np.sort(arr)
print(arr)

--------------------------------Original Array-----------------------------------------------------------
[3 2 0 1]
--------------------------------Sorted Array-------------------------------------------------------------
[0 1 2 3]


In [2431]:
import numpy as np

arr1 = np.array(['banana','apple','cherry'])


print("--------------------------------Original Array-----------------------------------------------------------")
print(arr1)

print("--------------------------------Sorted Array-------------------------------------------------------------")
arr1 = np.sort(arr1)
print(arr1)

--------------------------------Original Array-----------------------------------------------------------
['banana' 'apple' 'cherry']
--------------------------------Sorted Array-------------------------------------------------------------
['apple' 'banana' 'cherry']


In [2432]:
## Sort a boolean array

arr = [True, False,True]

print("--------------------------------Original Array-----------------------------------------------------------")

print(arr)

print("--------------------------------Sorted Array-------------------------------------------------------------")
arr1 = np.sort(arr)
print(arr1)


--------------------------------Original Array-----------------------------------------------------------
[True, False, True]
--------------------------------Sorted Array-------------------------------------------------------------
[False  True  True]


### Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted

In [2433]:
import numpy as np 

x = np.array([[1,2,3,4],[5,6,7,8]])

print("--------------------------------Original Array-----------------------------------------------------------")

print(x)

print("--------------------------------Sorted Array-------------------------------------------------------------")
x = np.sort(x)

print(x)

--------------------------------Original Array-----------------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------------------Sorted Array-------------------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]


In [2434]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print("--------------------------------Original Array-----------------------------------------------------------")

print(arr)

print("--------------------------------Sorted Array-------------------------------------------------------------")
arr = np.sort(arr)

print(arr)

--------------------------------Original Array-----------------------------------------------------------
[[3 2 4]
 [5 0 1]]
--------------------------------Sorted Array-------------------------------------------------------------
[[2 3 4]
 [0 1 5]]


## Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method

In [2435]:
import numpy as np 

x = np.array([1,2,3,4,5,6,7,8])

print(x)

# To search for a particular element in the array

print(np.where(x==1))
print(np.where(x==3))
print(np.where(x==5))
print(np.where(x==7))

[1 2 3 4 5 6 7 8]
(array([0]),)
(array([2]),)
(array([4]),)
(array([6]),)


In [2436]:
## Find the indexes where the values are even

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8])

print(x)

### find all the indexes whose position is even
print(np.where((x%2)==0))

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [2437]:
## Find the indexes where the values are odd

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8])

print(x)

### find all the indexes whose position is even
print(np.where((x%2)!=0))

[1 2 3 4 5 6 7 8]
(array([0, 2, 4, 6]),)


### Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order

In [2438]:
## Find the indexes where the value 7 should be inserted

import numpy as np 

x = np.array([6,7,8,9])

print(x)

### Returns the index position where element 7 needs to be inserted

ans = np.searchsorted(x,7)
print(ans)

[6 7 8 9]
1


### OBSERVATIONS:

Element '7' needs to be inserted at the index position 1.

In [2439]:
## Find the indexes where the value 7 should be inserted, starting from the right

import numpy as np 

x = np.array([6,7,8,9])

print(x)

ans = np.searchsorted(x,7,side='right')
print(ans)

[6 7 8 9]
2


### NumPy Array Iterating

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one

In [2440]:
## Iterate on the elements of the following 1-D array

import numpy as np 

x = np.array([1,2,3,4,5], dtype = 'int')


for i in x:
    print(i)

1
2
3
4
5


In [2441]:
## Iterating 2-D Arrays

# In a 2-D array it will go through all the rows

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])


for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [2442]:
## Iterating 3-D Arrays

## In a 3-D array it will go through all the 2-D arrays

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
1
2
3
4
5
6
7
8
9
10
11
12


### Enumerated Iteration Using ndenumerate()

It will return the index position as well as the element from the array

In [2443]:
import numpy as np

x = np.array([1,2,3,4,5], dtype='i')

print(x)

for a,b in np.ndenumerate(x):
    print(a,b)

[1 2 3 4 5]
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [2444]:
## Enumerate on following 2D array's elements

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

for x,y in np.ndenumerate(arr):
    print(x,y)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [2445]:
import numpy as np

arr = np.array([1,2,3], dtype='i')

arr

array([1, 2, 3], dtype=int32)

In [2446]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [2447]:
import numpy as np 

x = np.array([1,2,3,4,5], dtype='i')

print(x)

for i in np.nditer(x):
    print(i)

[1 2 3 4 5]
1
2
3
4
5


In [2448]:
import numpy as np
arr = np.array(['a', 'b', 'c'])

print(arr)

for x in arr:
    print('Hello ' + x)

['a' 'b' 'c']
Hello a
Hello b
Hello c


### Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0

In [2449]:
## Join two arrays

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)

x = np.concatenate((arr1,arr2), axis=0)

print(x)

[1 2 3]
[4 5 6]
1
1
[1 2 3 4 5 6]


In [2450]:
## Join two 2-D arrays along rows (axis=0)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)

### Join two arrays along the rows

x = np.concatenate((arr1,arr2), axis=0)

print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
2
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2451]:
## Join two 2-D arrays along columns (axis=1)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)

### Join two arrays along the columns

res = np.concatenate((arr1,arr2), axis=1)

print(res)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
2
2
[[1 2 5 6]
 [3 4 7 8]]


In [2452]:
## Join two 2-D arrays along rows (axis=0)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)

### Join two arrays along the rows

res = np.concatenate((arr1, arr2), axis=0)

print(res)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
2
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [2453]:
## Join two 2-D arrays along columns (axis=1)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)

### Join two arrays along the rows

res = np.concatenate((arr1, arr2), axis=1)

print(res)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
2
2
[[1 2 5 6]
 [3 4 7 8]]
