#### Latent Dirichlet Allocation(LDA)

1.  Latent Dirichlet Allocation is an unsupervised topic modeling algorithm that helps in extracting and finding out all the hidden topics from the collection of documents.

Ex:--  Suppose LDA considers document 1 as the input

        In that document 1, there are three different topics, So LDA finds out and assigns the probability scores for each topic

        Even within the particular topic, there may be several sub-topics, SO LDA may assign several sub-topics with the probability scores.

        This goes on and on unless it reaches the end of the document page.


Text :-- "Virat Kohli scored a century in the cricket match"

    Based on the above text document, LDA assigns

            (a.)    Sports -------------->   70 %

            (b.)    Politics ------------>   20 %

            (c.)    Technology ---------->   10 %


#### Mathematical Intuition :----

1.  LDA assumes each text document as the input

    For each document, LDA 

        (a.)    selects a topic distribution

        (b.)    selects a topic

        (c.)    selects the word from the topic

        (d.)    selects the sub words from the word.

2.  This process goes on unless and until it reaches the end of the document page. 

3.  So in this way, LDA extracts all the hidden topics from the collection of documents.

#### Steps used in this Algorithm:----

1.  Import all the necessary libraries

2.  Define the Sample Dataset

3.  Perform Text Vectorization (Bag of Words) i.e Tfidf Vectorizer

4.  Apply LDA Model

5.  Display the Topics

6.  Predict Topic for Each Document


#### Step 1: Import all the necessary libraries

In [433]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns

import  nltk

from    sklearn.feature_extraction.text import TfidfVectorizer
from    sklearn.decomposition           import LatentDirichletAllocation

#### OBSERVATIONS:

1.  TfidfVectorizer           ------->  Converts the input text into the matrix of tfidf numerical scores.

2.  LatentDirichletAllocation ------->  discovers the hidden topics from the collection of the text documents.

#### Step 2: Define the Sample Dataset

In [434]:
#### Define the sample dataset
documents = [
    "I love to eat pizza and pasta",
    "The new movie was fantastic and thrilling",
    "Python is great for data science and machine learning",
    "I enjoy watching movies and eating popcorn",
    "Data scientists use Python for analysis and modeling",
    "The pizza at that restaurant was delicious",
]

In [435]:
documents

['I love to eat pizza and pasta',
 'The new movie was fantastic and thrilling',
 'Python is great for data science and machine learning',
 'I enjoy watching movies and eating popcorn',
 'Data scientists use Python for analysis and modeling',
 'The pizza at that restaurant was delicious']

#### OBSERVATIONS:

1.  Here the sample text dataset is defined.

#### Step 3: Perform Text Vectorization (Bag of Words) i.e Tfidf Vectorizer

In [436]:
#### perform the Tfidf vectorizer on the sample text

from sklearn.feature_extraction.text import TfidfVectorizer

#### Create the object of TfidfVectorizer
tfidf = TfidfVectorizer()

#### Apply the object of TfidfVectorizer on to the text, to convert it into the numerical form
X_tfidf = tfidf.fit_transform(documents)

In [437]:
X_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 43 stored elements and shape (6, 33)>

#### OBSERVATIONS:

1.  Here the input document text is converted into the sparse matrix of tfidf so as to only capture the non zero values and their positions and ignore all the zero values.

2.  This is done so as to prevent the memory wastage.

In [438]:
#### Then convert the sparse matrix into the dense matrix
X = X_tfidf.toarray()

In [439]:
X

array([[0.        , 0.23062572, 0.        , 0.        , 0.        ,
        0.4501536 , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.4501536 , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.4501536 ,
        0.36913239, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.4501536 ,
        0.        , 0.        , 0.        ],
       [0.        , 0.21635609, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.422301  , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.422301  , 0.        , 0.422301  , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.34629286, 0.422301  , 0.        ,
        0.        , 0.34629286, 0.        ],
       [0.        , 0.18988419, 0.        , 0.30392276, 0.        ,
        0.        , 0.    

#### OBSERVATIONS:

1.  Here the sparse matrix is converted into the numpy array for better view and visibility.

2.  The new input has become a complete numerical model that can easily be trained by the LDA model.

#### Step 4: Apply LDA Model

In [440]:
from sklearn.decomposition import LatentDirichletAllocation

#### create an object for LatentDirichletAllocation
lda = LatentDirichletAllocation(n_components=2,random_state=42)


In [441]:
#### Train the lda model
lda.fit(X)

,"n_components n_components: int, default=10Number of topics... versionchanged:: 0.19 ``n_topics`` was renamed to ``n_components``",2
,"doc_topic_prior doc_topic_prior: float, default=NonePrior of document topic distribution `theta`. If the value is None,defaults to `1 / n_components`.In [1]_, this is called `alpha`.",None
,"topic_word_prior topic_word_prior: float, default=NonePrior of topic word distribution `beta`. If the value is None, defaultsto `1 / n_components`.In [1]_, this is called `eta`.",None
,"learning_method learning_method: {'batch', 'online'}, default='batch'Method used to update `_component`. Only used in :meth:`fit` method.In general, if the data size is large, the online update will be muchfaster than the batch update.Valid options:- 'batch': Batch variational Bayes method. Use all training data in each EM update. Old `components_` will be overwritten in each iteration.- 'online': Online variational Bayes method. In each EM update, use mini-batch of training data to update the ``components_`` variable incrementally. The learning rate is controlled by the ``learning_decay`` and the ``learning_offset`` parameters... versionchanged:: 0.20 The default learning method is now ``""batch""``.",'batch'
,"learning_decay learning_decay: float, default=0.7It is a parameter that control learning rate in the online learningmethod. The value should be set between (0.5, 1.0] to guaranteeasymptotic convergence. When the value is 0.0 and batch_size is``n_samples``, the update method is same as batch learning. In theliterature, this is called kappa.",0.7
,"learning_offset learning_offset: float, default=10.0A (positive) parameter that downweights early iterations in onlinelearning. It should be greater than 1.0. In the literature, this iscalled tau_0.",10.0
,"max_iter max_iter: int, default=10The maximum number of passes over the training data (aka epochs).It only impacts the behavior in the :meth:`fit` method, and not the:meth:`partial_fit` method.",10
,"batch_size batch_size: int, default=128Number of documents to use in each EM iteration. Only used in onlinelearning.",128
,"evaluate_every evaluate_every: int, default=-1How often to evaluate perplexity. Only used in `fit` method.set it to 0 or negative number to not evaluate perplexity intraining at all. Evaluating perplexity can help you check convergencein training process, but it will also increase total training time.Evaluating perplexity in every iteration might increase training timeup to two-fold.",-1
,"total_samples total_samples: int, default=1e6Total number of documents. Only used in the :meth:`partial_fit` method.",1000000.0
,"perp_tol perp_tol: float, default=1e-1Perplexity tolerance. Only used when ``evaluate_every`` is greater than 0.",0.1


#### OBSERVATIONS:

1.  The object of lda model has been made using the following parameters:---

    (a.)    n_components = 2 ------------> LDA discovers 2 hidden topics from the collection of the text documents.

    (b.)    random_state = 42 -----------> It ensures the reproducibility

2.  Then using the object of lda, the input numerical vector data has been trained.

#### Step 5: Display the Topics

In [442]:
#### get the vocabularies in the document
vocabularies = tfidf.get_feature_names_out()

In [443]:
vocabularies

array(['analysis', 'and', 'at', 'data', 'delicious', 'eat', 'eating',
       'enjoy', 'fantastic', 'for', 'great', 'is', 'learning', 'love',
       'machine', 'modeling', 'movie', 'movies', 'new', 'pasta', 'pizza',
       'popcorn', 'python', 'restaurant', 'science', 'scientists', 'that',
       'the', 'thrilling', 'to', 'use', 'was', 'watching'], dtype=object)

#### OBSERVATIONS:

1.  It displays the list of all the vocabularies present in the text document.

In [444]:
#### Discover the hidden topics
hidden_topics=lda.components_

In [445]:
hidden_topics

array([[0.51080001, 0.72423887, 0.90039821, 0.51159214, 0.90039821,
        0.94162535, 0.51332734, 0.51332734, 0.51863425, 0.51159214,
        0.51016456, 0.51016456, 0.51016456, 0.94162535, 0.51016456,
        0.51080001, 0.51863425, 0.51332734, 0.51863425, 0.94162535,
        1.19480172, 0.51332734, 0.51159214, 0.90039821, 0.51016456,
        0.51080001, 0.90039821, 0.8648026 , 0.51863425, 0.94162535,
        0.51080001, 0.86480215, 0.51332734],
       [0.88825141, 1.34040429, 0.50726379, 1.11955849, 0.50726379,
        0.50852825, 0.92259069, 0.92259069, 0.90366675, 1.11955849,
        0.86046649, 0.86046649, 0.86046649, 0.50852825, 0.86046649,
        0.88825141, 0.90366675, 0.92259069, 0.90366675, 0.50852825,
        0.50861935, 0.92259069, 1.11955849, 0.50726379, 0.86046649,
        0.88825141, 0.50726379, 0.81577894, 0.90366675, 0.50852825,
        0.88825141, 0.81577939, 0.92259069]])

#### OBSERVATIONS:

1.  The two hidden topics are discovered from the document using LDA algorithm.

In [446]:
#### get the shape of the lda hidden topics
print("Shape of the LDA hidden topics is:", hidden_topics.shape)

Shape of the LDA hidden topics is: (2, 33)


#### OBSERVATIONS:

1.  There are a total of 2 hidden topics and each topic has 33 vocabularies in it.

In [447]:
#### Get the top five words or each topic
for x,y in enumerate(hidden_topics):
    #### print the topic number
    print(f"Topic:{x+1}")
    #### print the top five words for each topic
    print([vocabularies[i] for i in y.argsort()[-5:]])

Topic:1
['pasta', 'love', 'to', 'eat', 'pizza']
Topic:2
['popcorn', 'data', 'python', 'for', 'and']


#### OBSERVATIONS:

1.  It returns the top five words for each topic.

#### Step 6: Predict Topic for Each Document

In [448]:
#### List the documents
documents

['I love to eat pizza and pasta',
 'The new movie was fantastic and thrilling',
 'Python is great for data science and machine learning',
 'I enjoy watching movies and eating popcorn',
 'Data scientists use Python for analysis and modeling',
 'The pizza at that restaurant was delicious']

#### OBSERVATIONS:

1.  The list of documents is obtained.

In [449]:
#### get the predicted probabilities for two hidden topics in each of the documents
predicted_probabilities_topics = lda.transform(X)

In [450]:
predicted_probabilities_topics

array([[0.83077895, 0.16922105],
       [0.18895813, 0.81104187],
       [0.1448701 , 0.8551299 ],
       [0.16891665, 0.83108335],
       [0.1501231 , 0.8498769 ],
       [0.84408263, 0.15591737]])

#### OBSERVATIONS:

1.  The predicted probabilities have been obtained for the two hidden topics in each of the documents.

In [451]:
#### print the details of the predicted probability distributions
for i,doc in enumerate(documents):
    #### print each of the document
    print(f"\n Document {i+1} : {doc}")
    #### print the probability distribution for each topic in the document
    print(f"Predicted Probability for each topic is :{predicted_probabilities_topics[i]}")
    #### get the dominant topic
    print(f"Dominant Topic is:{predicted_probabilities_topics[i].argmax()+1}")


 Document 1 : I love to eat pizza and pasta
Predicted Probability for each topic is :[0.83077895 0.16922105]
Dominant Topic is:1

 Document 2 : The new movie was fantastic and thrilling
Predicted Probability for each topic is :[0.18895813 0.81104187]
Dominant Topic is:2

 Document 3 : Python is great for data science and machine learning
Predicted Probability for each topic is :[0.1448701 0.8551299]
Dominant Topic is:2

 Document 4 : I enjoy watching movies and eating popcorn
Predicted Probability for each topic is :[0.16891665 0.83108335]
Dominant Topic is:2

 Document 5 : Data scientists use Python for analysis and modeling
Predicted Probability for each topic is :[0.1501231 0.8498769]
Dominant Topic is:2

 Document 6 : The pizza at that restaurant was delicious
Predicted Probability for each topic is :[0.84408263 0.15591737]
Dominant Topic is:1


#### OBSERVATIONS:

1.  The above code explains about the details of the probability distributions for each document.

2.  It even computes the probability distributions for each topic in the document.

3.  It finds out the dominant topic from each of the document (the index position of the topic with the highest value)