## **FastText**

1.  FastText is an improvised version of Word2Vec model.

2.  It consideres every word as atomic and breaks the words into the sub-words.

3.  It handles all the misspelled words and the morphological variations in the words.

## **Importance of FastText**

1.  It considers every word as atomic and breaks into the subwords.

2.  It handles all the misspelled words in the text.

3.  It handles the morphological variations of the words in the text.

3.  It finds out the vector representation of some unknown words not present in the vocabulary list based on the information of the subwords present in the vocabulary list.

##  **Steps used in this Algorithm**

1.  Import all the necessary libraries

2.  Download the necessary NLTK resources

3.  Prepare Your Text Data

4.  Perform the Tokenization on the corpus text

5.  Perform the normalization on the text

6.  Remove the stopwords from the text

7.  Train the FastText Model

8.  Explore the Trained Model

9.  Handle Out-of-Vocabulary (OOV) Words

## **Step 1: Import all the necessary libraries**

In [502]:
!pip install gensim

In [503]:
import numpy              as np
import pandas             as pd
import matplotlib.pyplot  as plt
import seaborn            as sns

import nltk

from  nltk.tokenize import word_tokenize
from  gensim.models import FastText

## **OBSERVATIONS:**

1.  gensim --------> It is a module used for word embedding.

2.  FastText ------> helps in finding out the vector representation of some unknown words not in the vocabulary based on the information of some subwords present in the vocabulary list.

## **Step 2: Download the necessary NLTK resources**

In [504]:
### Download the NLTK resources
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!


True

## **OBSERVATIONS:**

1.  punkt_tab ------->  It is a pre trained tokenizer that is used for tokenization process.

2.  stopwords ------->  It is used for the removal of the stopwords from the text.

3.  averaged_perceptron_tagger_eng ----> It is used for POS Tagging.

## **Step 3: Prepare Your Text Data**

In [505]:
#### Define the text data
corpus = [
    "Natural language processing is a fascinating field",
    "Machine learning enables computers to learn from data",
    "Deep learning is a subset of machine learning",
    "Word embeddings represent words as vectors",
    "FastText handles rare and unseen words effectively"
]

In [506]:
corpus

['Natural language processing is a fascinating field',
 'Machine learning enables computers to learn from data',
 'Deep learning is a subset of machine learning',
 'Word embeddings represent words as vectors',
 'FastText handles rare and unseen words effectively']

## **OBSERVATIONS:**

1.  Here the corpus text data has been made.

## **Step 4: Perform the Tokenization on the corpus text**

In [507]:
#### perform the word tokenization on the corpus text

tokenized_sentences = [word_tokenize(x.lower()) for x in corpus]

## **OBSERVATIONS:**

1.  Here Word tokenization has been applied on the corpus text in the list.

2.  The output formed is the list of all the tokenized sentences.

In [508]:
### Another method for doing the word tokenization on the corpus text

corpus

['Natural language processing is a fascinating field',
 'Machine learning enables computers to learn from data',
 'Deep learning is a subset of machine learning',
 'Word embeddings represent words as vectors',
 'FastText handles rare and unseen words effectively']

In [509]:
#### Convert the corpus text into the text form
corpus = ' '.join(corpus)

In [510]:
corpus

'Natural language processing is a fascinating field Machine learning enables computers to learn from data Deep learning is a subset of machine learning Word embeddings represent words as vectors FastText handles rare and unseen words effectively'

In [511]:
#### perform the word tokenization on the corpus text
words = word_tokenize(corpus)

In [512]:
words

['Natural',
 'language',
 'processing',
 'is',
 'a',
 'fascinating',
 'field',
 'Machine',
 'learning',
 'enables',
 'computers',
 'to',
 'learn',
 'from',
 'data',
 'Deep',
 'learning',
 'is',
 'a',
 'subset',
 'of',
 'machine',
 'learning',
 'Word',
 'embeddings',
 'represent',
 'words',
 'as',
 'vectors',
 'FastText',
 'handles',
 'rare',
 'and',
 'unseen',
 'words',
 'effectively']

In [513]:
#### Convert all the tokenized words in text form

words = ' '.join(words)

In [514]:
words

'Natural language processing is a fascinating field Machine learning enables computers to learn from data Deep learning is a subset of machine learning Word embeddings represent words as vectors FastText handles rare and unseen words effectively'

## **OBSERVATIONS:**

1.  The corpus text has been tokenized into the words.

2.  The words in the list has been converted back into the text form.

## **Step 5: Perform the normalization on the text**

In [515]:
from nltk.tokenize import RegexpTokenizer

#### Create an object for Regular Expression Tokenizer
reg = RegexpTokenizer(r'\w+')

#### Apply the object of Regular Expression and remove all the punctuations and special symbols from the text
words = reg.tokenize(words)

In [516]:
words

['Natural',
 'language',
 'processing',
 'is',
 'a',
 'fascinating',
 'field',
 'Machine',
 'learning',
 'enables',
 'computers',
 'to',
 'learn',
 'from',
 'data',
 'Deep',
 'learning',
 'is',
 'a',
 'subset',
 'of',
 'machine',
 'learning',
 'Word',
 'embeddings',
 'represent',
 'words',
 'as',
 'vectors',
 'FastText',
 'handles',
 'rare',
 'and',
 'unseen',
 'words',
 'effectively']

## **OBSERVATIONS:**

1.  The object of Regular Expression Tokenizer has been created using \w+  where it extracts only more than one occurances of numbers and digits.

2.  Then the object of Regular expression has been applied on the text so as to remove all the punctuations and the special symbols from the text.

## **Step 6: Remove the stopwords from the text**

In [517]:
#### define all the english stop words
from nltk.corpus import stopwords
english_stopwords = set(stopwords.words("english"))

In [518]:
english_stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [519]:
#### Remove all the english stop words from the text
ans = [x.lower() for x in words if(x not in english_stopwords)]

In [520]:
ans

['natural',
 'language',
 'processing',
 'fascinating',
 'field',
 'machine',
 'learning',
 'enables',
 'computers',
 'learn',
 'data',
 'deep',
 'learning',
 'subset',
 'machine',
 'learning',
 'word',
 'embeddings',
 'represent',
 'words',
 'vectors',
 'fasttext',
 'handles',
 'rare',
 'unseen',
 'words',
 'effectively']

## **OBSERVATIONS:**

1. Here all the english stop words have been removed from the text.

## **Step 7: Train the FastText Model**

In [521]:
### Train the Fast Text model
model = FastText(
    sentences         = tokenized_sentences         ,
    vector_size       =     50                      ,
    window            =      3                      ,
    min_count         =      1                      ,
    sg                =      1                      ,
    epochs            =      100
)

In [522]:
model

##**OBSERVATIONS:**

1.  Here the FastText model has been trained with the following parameters:-------

    (a.)  sentences = tokenized_sentences . It accepts the input in form of tokenized words.

    (b.)  vector_size = 50 ----------->  Here the vector is a numerical dense dimensional vector of size 50.

    (c.)   window = 3 ---------------->  Here the size of the context input is 3

    (d.)  min_count = 1 -------------->  atleast 1 time, the word must appear in the dictionary.

    (e.)  sg = 1 --------------------->  The model architecture is Skip-Grams. Here based on the target word, surrounding context words are predicted.

    (f.)  epochs = 100 ---------------> Total 100 iterations are required to train the model.

## **Step 8: Explore the Trained Model**

In [523]:
### Vector representation of the word 'natural'
model.wv['natural']

array([-7.2463701e-04, -5.3047930e-04,  6.6479814e-04, -1.2593132e-03,
        3.0367132e-03, -2.3750232e-03,  4.7879447e-03,  2.8217584e-03,
       -1.8424509e-04,  2.9925893e-03, -3.1626706e-03, -1.3293079e-03,
        1.6390678e-03,  1.4841135e-03,  2.2499785e-03, -8.2287972e-04,
       -2.3260086e-03,  6.3928356e-04, -2.3356080e-03, -4.8548065e-04,
       -8.5085107e-04,  2.4301901e-03, -1.5599162e-03, -1.4388099e-03,
        3.9753891e-03, -1.0512471e-03, -3.0597935e-03, -2.0209956e-03,
       -8.8080805e-04, -3.6776997e-04,  2.1390072e-03,  2.8840434e-03,
       -1.3368093e-05, -1.0970196e-03, -2.0248929e-04, -2.4140853e-04,
        4.1443360e-04, -4.2922402e-04, -1.4309796e-03, -9.1862434e-04,
        1.2138172e-03,  2.1118002e-03, -4.0835668e-03,  1.6549744e-03,
       -4.9756712e-04, -3.3199308e-03, -2.2702778e-03, -9.2173531e-04,
        7.1208744e-04,  1.6569267e-03], dtype=float32)

## **OBSERVATIONS**

1.  The word 'natural' has been converted into the dense dimensional numerical vector of the size 50.

In [524]:
### Vector representation of the word 'computers'
model.wv['computers']

array([-3.0194658e-03,  6.0598006e-05,  1.7136341e-04,  1.9216104e-03,
        1.4834367e-03,  4.7261622e-03,  2.7213602e-03,  1.1334965e-03,
        2.0740076e-03,  1.9569872e-03,  6.9259928e-04, -1.9935660e-04,
        2.1086175e-03,  1.9395858e-03, -1.9449521e-03, -3.9900467e-04,
        2.6208623e-03, -1.9156797e-03, -1.3821319e-03,  7.9172454e-04,
       -1.2990455e-03,  4.5235180e-03, -4.4468576e-03,  1.0411970e-03,
        3.6179731e-03,  6.0438015e-03, -2.1994836e-03, -1.5144709e-03,
       -4.9344134e-03,  2.8290194e-03, -3.0097619e-04, -1.3980876e-03,
       -1.5435828e-03, -1.4336787e-03, -5.0862593e-04, -2.8577985e-03,
        4.8043923e-03,  1.3768987e-03,  4.7756974e-03,  1.9704401e-04,
       -2.5902702e-03,  1.1380545e-03, -5.7522976e-03, -2.2898128e-03,
        8.5048744e-04,  1.2225031e-03,  1.5703536e-03, -7.1869307e-04,
       -2.1883547e-03,  2.2323737e-04], dtype=float32)

## **OBSERVATIONS**

1.  The word 'computers' has been converted into the dense dimensional numerical vector of the size 50.

In [525]:
### Vector representation of the word 'effectively'
model.wv['effectively']

array([ 0.00086432,  0.00252589,  0.0013777 , -0.00320938,  0.0016746 ,
        0.00108865, -0.00055044, -0.00106746, -0.00173503, -0.00159506,
       -0.00115426,  0.00045141,  0.00260379,  0.00289216, -0.00336846,
       -0.00032242,  0.0019783 ,  0.00207206, -0.00177563, -0.00064072,
        0.0008832 , -0.00088266, -0.00146297, -0.0025612 ,  0.00028376,
        0.00019584, -0.00055714,  0.00091751,  0.00423162,  0.00028641,
        0.00069954,  0.00115873,  0.00175122, -0.0022189 , -0.00029827,
        0.00125806, -0.00266872,  0.00035403, -0.00349325, -0.00195115,
        0.00048107,  0.00167132,  0.00132323,  0.00208579,  0.00045879,
        0.00070626,  0.00128739,  0.00088949,  0.00443277,  0.00026665],
      dtype=float32)

## **OBSERVATIONS**

1.  The word 'effectively' has been converted into the dense dimensional numerical vector of the size 50.

In [526]:
### Vector representation of the word 'Deep'
model.wv['Deep']

array([ 1.0124960e-03, -5.6624031e-03, -6.7162031e-04,  1.7997023e-03,
        9.2833862e-04,  3.4008715e-03,  9.3782274e-04, -1.1235885e-03,
       -4.3225889e-03, -6.7378371e-03, -2.7367226e-03, -6.1170040e-03,
        6.3850265e-04,  5.6243036e-05,  5.4102628e-03, -5.4045813e-03,
        1.6298697e-03,  1.6317908e-03, -3.3776350e-03, -9.8704104e-04,
       -2.4034563e-03,  1.1503441e-03, -1.3807700e-04,  3.5253793e-03,
        2.5609590e-03, -2.8460070e-03,  1.1381307e-03, -3.0629756e-04,
        4.4822507e-05, -1.1228912e-03,  3.1650004e-03, -1.5033617e-03,
        3.4652099e-03,  4.6697296e-03, -4.7693020e-03,  1.3032375e-03,
       -4.1818023e-03, -8.7049622e-03, -5.1145285e-04,  1.7499647e-03,
       -1.1373730e-03,  4.6153944e-03, -2.4798885e-05, -1.4958410e-03,
       -4.2443746e-03, -8.4368046e-04, -1.9284012e-04, -3.9331001e-04,
        1.8427867e-04,  2.8820855e-03], dtype=float32)

## **OBSERVATIONS**

1.  The word 'Deep' has been converted into the dense dimensional numerical vector of the size 50.

In [527]:
### Vector representation of the word 'enables'
model.wv['enables']

array([ 1.5324351e-03,  2.3176942e-03, -3.1155457e-03,  2.5394533e-03,
        4.2198398e-03,  2.0325074e-03, -6.6816981e-04,  1.2256730e-03,
       -6.2393997e-04,  3.0393673e-03, -3.8732109e-03, -3.2042246e-03,
       -6.2036206e-06,  2.2492241e-03, -1.7819413e-03, -2.5247602e-04,
        6.6729874e-04, -2.9046130e-03, -1.0007946e-03,  3.7230533e-03,
        1.5125585e-03, -1.0699903e-03, -2.9683560e-03,  2.0906501e-03,
       -2.3629630e-03, -1.8110677e-03, -7.6463708e-04, -4.4708843e-03,
       -1.7436801e-03, -2.8008544e-03, -1.3556100e-03,  5.3467168e-03,
       -3.1052921e-03, -1.8356079e-03,  2.2269890e-03,  4.5323358e-03,
        3.5720388e-04,  1.0883599e-03, -4.3031605e-04, -2.2362969e-03,
       -1.0469191e-03, -2.9619082e-04, -1.9925034e-03,  2.8957503e-03,
        7.4191426e-04,  2.0353163e-03,  3.6498471e-03, -4.1503198e-03,
        1.4126735e-03,  8.5774204e-04], dtype=float32)

## **OBSERVATIONS**

1.  The word 'enables' has been converted into the dense dimensional numerical vector of the size 50.

In [528]:
### Find most similar words to a given word 'learning'
model.wv.most_similar('learning')

[('learn', 0.566283643245697),
 ('embeddings', 0.3166630268096924),
 ('processing', 0.3066617250442505),
 ('is', 0.2814252972602844),
 ('language', 0.22058233618736267),
 ('fascinating', 0.1873551607131958),
 ('computers', 0.1703764796257019),
 ('natural', 0.1666349172592163),
 ('and', 0.1589219719171524),
 ('as', 0.14239010214805603)]

## **OBSERVATIONS**

1.  The above ten words are the list of all the words that are most similar with respect to 'learning'.

## **Step 9: Handle Out-of-Vocabulary (OOV) Words**

This is where FastText comes into the picture where it can deduce the vector form of some unknown words not present in the vocabulary list using the information of some subwords present in the vocabulary list.

In [529]:
### Find the vector representation of the word 'learnings' that is not known
model.wv['learnings']

array([-8.6743815e-04, -9.2491199e-04, -1.3378768e-03, -1.8773484e-03,
       -5.4910220e-04,  1.5938377e-03, -7.2624895e-04, -1.0992755e-03,
       -1.9265991e-03,  5.2845478e-04, -2.2062492e-04, -3.9157597e-03,
        3.1014791e-04,  2.5739563e-03, -1.4379311e-03, -1.1849512e-03,
        6.8146852e-05, -1.3054026e-03, -1.9864601e-03,  3.4175890e-03,
        4.0605391e-04, -4.9657107e-04, -7.8516663e-04,  1.0991159e-03,
       -1.3701107e-03, -3.7043048e-03, -2.8391177e-04,  3.4112758e-03,
       -2.7216771e-03,  5.7162889e-03,  1.1733305e-03,  1.8359000e-03,
       -2.6961204e-03,  2.9323995e-03, -7.0885126e-04, -2.5519500e-03,
        1.7971118e-03, -9.7494310e-04,  2.7351868e-03,  4.3866527e-03,
        2.2974834e-03,  6.8506144e-04,  2.4359836e-03, -7.4982658e-05,
        1.2949929e-03,  1.5505051e-03, -2.9311841e-03, -2.3272594e-03,
       -2.3558319e-03,  2.7747609e-04], dtype=float32)

## **OBSERVATIONS**

1.  learnings is the word not present in the vocabulary list.

2.  As Fasttext model is trained, so based on the subword(learning) in the vocabulary list, the vector representation of the word 'learnings' is computed easily.