## **GloVe Embeddings:**

1.  GloVe stands for Global Vector For Word Representation.

2.  It helps in finding out the maximum frequently occuring words in the given context.

3.  The model for GloVe embeddings used is "glove-wiki-gigaward-100"

4.  Each and every word is converted into numerical dense dimensional vector of size 100 in glove-wiki-gigaward-100.

## **glove-wiki-gigaward-100**

1.  glove-wiki-gigaward-100 --------> It is a pre-trained model used for GloVe embeddings where each and every word is converted into dense dimensional vector of the size 100.

  (a.)  It helps in finding out the maximum frequently occuring words in the particular context.

## **Importance of GloVe**

1.  It helps in finding out the most frequently occuring words from the given text in the dense representation form.


| Word  | Vector Size |
| ----- | ----------- |
| king  | 100         |
| queen | 100         |
| man   | 100         |
| woman | 100         |


### Dense Representation of the frequently occuring words in the same context

“cat” and “mat” co-occur in the same context (sentence).

“cat” and “dog” may co-occur often across many sentences.

“cat” and “table” may rarely co-occur.

So, word-word co-occurrence statistics capture how often each word appears with every other word.

We can store this information in a co-occurrence matrix X:

X[i][j] = number of times word j appears in the context of word i.


### Steps used in this Algorithm:---

1.   Import all the necessary Libraries

2.   Load the Pretrained GloVe Model

3.   Check the Vocabulary Size

4.   Get Vector of a Word

5.   Get the list of all the words in the vocabulary

6.   Find Similar Words (Like FastText)

7.   Get the Word Analogy

8.   Convert Sentence into GloVe Embedding

9.   Test Sentence Embedding

9.   Simple Similarity Between Two Sentences



## **Step 1: Import all the necessary libraries**

In [116]:
!pip install gensim

In [117]:
import  numpy             as  np
import  pandas            as  pd
import  matplotlib.pyplot as plt
import  seaborn           as sns

import  warnings
warnings.filterwarnings('ignore')

import  nltk
from    nltk.tokenize     import  word_tokenize
import  gensim.downloader as      api             #### download and load the pre-trained GloVe models


nltk.download('punkt_tab')
nltk.download('stopwords')


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## **OBSERVATIONS:**

1.  tokenize ----------->  converts the sentences into the tokens.

2.  word_tokenize ------>  converts the input text into tokens.

3.  gensim ------------->  module used for embeddings

4.  api ----------------> object for Glove Embedding

## **Step 2: Load the Pretrained GloVe Model**

In [118]:
#### Load the pre-trained GloVe model
model = api.load('glove-wiki-gigaword-100')

## **OBSERVATIONS**

1.  The 'glove-wiki-gigaword-100' is a pre-trained model created in Stanford university that is used for Glove Embedding.

2.  It is used to convert eacb and every into the dense dimensional vector of the size 100.

| Property         | Value                |
| ---------------- | -------------------- |
| Vocabulary Size  | 400,000 words        |
| Vector Dimension | 100                  |
| Corpus           | Wikipedia + Gigaword |
| Algorithm        | GloVe                |


## **Step 3: Check the Size of the Vocabulary**

In [119]:
print('Size of the Vocabulary is:', len(model))

Size of the Vocabulary is: 400000


## **OBSERVATIONS**

1.  There are total 400000 words in the vocabulary list.

## **Step 4: Get Vector of a Word**

In [120]:
### Get the vector representation of the word 'king'
vector_king = model['king']

In [121]:
print(vector_king)

[-0.32307  -0.87616   0.21977   0.25268   0.22976   0.7388   -0.37954
 -0.35307  -0.84369  -1.1113   -0.30266   0.33178  -0.25113   0.30448
 -0.077491 -0.89815   0.092496 -1.1407   -0.58324   0.66869  -0.23122
 -0.95855   0.28262  -0.078848  0.75315   0.26584   0.3422   -0.33949
  0.95608   0.065641  0.45747   0.39835   0.57965   0.39267  -0.21851
  0.58795  -0.55999   0.63368  -0.043983 -0.68731  -0.37841   0.38026
  0.61641  -0.88269  -0.12346  -0.37928  -0.38318   0.23868   0.6685
 -0.43321  -0.11065   0.081723  1.1569    0.78958  -0.21223  -2.3211
 -0.67806   0.44561   0.65707   0.1045    0.46217   0.19912   0.25802
  0.057194  0.53443  -0.43133  -0.34311   0.59789  -0.58417   0.068995
  0.23944  -0.85181   0.30379  -0.34177  -0.25746  -0.031101 -0.16285
  0.45169  -0.91627   0.64521   0.73281  -0.22752   0.30226   0.044801
 -0.83741   0.55006  -0.52506  -1.7357    0.4751   -0.70487   0.056939
 -0.7132    0.089623  0.41394  -1.3363   -0.61915  -0.33089  -0.52881
  0.16483  -0.98878

## **OBSERVATIONS**

1.  The word 'king' has been converted into the dense dimensional vector of the size 100.

## **Step 5: Get the list of all the words in the vocabulary**

In [122]:
### get the list of the words in the vocabulary
words = list(model.key_to_index.keys())

In [123]:
words

['the',
 ',',
 '.',
 'of',
 'to',
 'and',
 'in',
 'a',
 '"',
 "'s",
 'for',
 '-',
 'that',
 'on',
 'is',
 'was',
 'said',
 'with',
 'he',
 'as',
 'it',
 'by',
 'at',
 '(',
 ')',
 'from',
 'his',
 "''",
 '``',
 'an',
 'be',
 'has',
 'are',
 'have',
 'but',
 'were',
 'not',
 'this',
 'who',
 'they',
 'had',
 'i',
 'which',
 'will',
 'their',
 ':',
 'or',
 'its',
 'one',
 'after',
 'new',
 'been',
 'also',
 'we',
 'would',
 'two',
 'more',
 "'",
 'first',
 'about',
 'up',
 'when',
 'year',
 'there',
 'all',
 '--',
 'out',
 'she',
 'other',
 'people',
 "n't",
 'her',
 'percent',
 'than',
 'over',
 'into',
 'last',
 'some',
 'government',
 'time',
 '$',
 'you',
 'years',
 'if',
 'no',
 'world',
 'can',
 'three',
 'do',
 ';',
 'president',
 'only',
 'state',
 'million',
 'could',
 'us',
 'most',
 '_',
 'against',
 'u.s.',
 'so',
 'them',
 'what',
 'him',
 'united',
 'during',
 'before',
 'may',
 'since',
 'many',
 'while',
 'where',
 'states',
 'because',
 'now',
 'city',
 'made',
 'like',
 

## **OBSERVATIONS**

1.  key_to_index.keys() --------->  It provides the list of all the words present in the vocabulary.

## **Step 6: Find Similar Words (Like FastText)**

In [124]:
### Find out the most similar word w.r.to 'king'

ans = model.most_similar('king')

In [125]:
ans

[('prince', 0.7682328820228577),
 ('queen', 0.7507690787315369),
 ('son', 0.7020888328552246),
 ('brother', 0.6985775232315063),
 ('monarch', 0.6977890729904175),
 ('throne', 0.6919989585876465),
 ('kingdom', 0.6811409592628479),
 ('father', 0.6802029013633728),
 ('emperor', 0.6712858080863953),
 ('ii', 0.6676074266433716)]

## **OBSERVATIONS**

1.  The above 10 words are the most similar words with respect to 'king'.

2.  'prince' is the word that is the most similar w.r.to the king as it has the highest similarity ratio amongst all other words.

In [126]:
### Find out the top 5 most similar word w.r.to 'king'
ans = model.most_similar('king', topn=5)

In [127]:
ans

[('prince', 0.7682328820228577),
 ('queen', 0.7507690787315369),
 ('son', 0.7020888328552246),
 ('brother', 0.6985775232315063),
 ('monarch', 0.6977890729904175)]

## **OBSERVATIONS**

1.  The above 5 words are the most similar words with respect to 'king'.

2.  'prince' is the word that is the most similar w.r.to the king as it has the highest similarity ratio amongst all other words.

## **Step 7: Perform Word Analogy**

In [128]:
res = model.most_similar(
    positive = ["king","woman"] ,
    negative = ["man"]          ,
    topn     =    1
)

In [129]:
res

[('queen', 0.7698540687561035)]

## **OBSERVATIONS**

1.  Word Analogy is used to find out the relation of one word with respect to another based on the similarity ratio.

## **Step 8: Convert the sentece into GloVe Embeddings:**

In [130]:
### perform the function definition
def sentence_vector(text):
  ### convert the text to lower case
  text = text.lower()
  ### perform the word tokenization on the text
  words = word_tokenize(text)
  #### create an empty list of word vectors
  word_vectors = []

  #### Check if the word exists in the vocabulary ot not then append in the word vector list
  for x in words:
    if(x in model):
      word_vectors.append(model[x])

  #### Check if the length of the word vectors is 0 then return null
  if(len(word_vectors)==0):
    return(np.zeros(100))

  #### perform the embeddings of the word vectors and get the average values aong the column wize manner
  return(np.mean(word_vectors,axis=0))

### define the input sentence
text = "I love machine learning"

### perform the function call
ans = sentence_vector(text)
print(ans)

[ 0.05192025  0.59274     0.1211025  -0.02758251 -0.32590252  0.4873125
  0.08731876  0.0392628   0.16041625  0.03498251  0.22566    -0.079695
  0.07848275  0.14854674  0.2162875  -0.17473349  0.20247525  0.455735
 -0.6060775   0.62728506 -0.05533701  0.19815248 -0.0554575  -0.3169325
  0.14453602  0.44995502 -0.13674401 -0.39151236  0.342488   -0.038004
 -0.30873     0.8875      0.16554502 -0.09631325  0.23830576 -0.10760999
 -0.219939    0.21443748  0.6329025  -0.49880248 -0.17758176 -0.05304649
 -0.07534557 -0.45472002 -0.4974125  -0.15129998 -0.11091749 -0.19589199
  0.20618378 -0.87854004 -0.1415385   0.09702326  0.289347    0.93947
  0.20545    -2.203025    0.31823     0.38767502  1.13689     0.527365
  0.31559     0.86213243 -0.5244945   0.01804505  0.27870604  0.27692425
  0.60059696  0.07509273 -0.02488326  0.04104249 -0.017532   -0.005605
  0.33542    -0.2512015  -0.01976751  0.51892     0.031774   -0.08816692
 -0.4960075  -0.162435    0.28048003  0.05357481 -0.422645    0.15

### **OBSERVATIONS:**

1. We have taken the sentence as the input

2. Then perform the tokenization on the  input sentence

3. Checked if each word exists in the GloVe dictionary

4. If exists, then embedding is performed on it and we get the vector representation of it by taking the average of all the word vectors in column wise manner.

5. So the above is the vector representation of the sentence using GloVe embedding.

## **Step 9: Test the Sentence Embedding:**

In [131]:
test_data = "I love data science"

#### call the function sentence vector

res = sentence_vector(test_data)

print(res)

[-9.77497548e-02  5.70585012e-01  5.06172478e-01 -1.30757511e-01
 -5.12400120e-02 -3.76174897e-02 -4.53312397e-02 -1.64467514e-01
  1.82227492e-02 -7.37650096e-02  2.98972517e-01 -1.24224991e-01
  3.72374989e-02  2.97673494e-01  2.35732496e-01 -1.35974847e-02
  4.12530005e-01  6.12564981e-01 -4.12762493e-01  6.49580002e-01
 -9.63770077e-02  1.14566252e-01  5.27125001e-02 -1.97270006e-01
  1.19799897e-02  1.47619501e-01  2.03678757e-01 -4.29390013e-01
  1.68387473e-01 -3.37599963e-02 -4.00097489e-01  6.35429978e-01
 -1.43132493e-01  2.15232491e-01  2.00824440e-03  1.69336766e-01
 -3.56440008e-01  4.27749991e-01  2.15837494e-01 -4.42803502e-01
 -4.49841738e-01 -2.79556990e-01 -4.97065544e-01 -3.77547503e-01
 -4.79730010e-01 -1.89074993e-01  6.40150085e-02 -1.30869493e-01
  1.17490746e-01 -7.72624969e-01  3.67008746e-01  6.78248703e-04
  3.31472516e-01  8.15429986e-01  1.33585073e-02 -2.28782511e+00
  3.81698251e-01  2.73514986e-01  1.46107996e+00  4.51557517e-01
  4.60757464e-02  8.63384

## **OBSERVATIONS**

1.  Here we have obtained the dense dimensional numerical vector for the test data of the size 100.

## **Step 10: Compute Cosine Similarity between two sentences**

In [132]:
from sklearn.metrics.pairwise import cosine_similarity

### consider two sentences
sent1 = "I love machine learning"
sent2 = "I love artificial intelligence"

#### perform sentence mebedding
vec1 = sentence_vector(sent1)
vec2 = sentence_vector(sent2)

In [133]:
vec1

array([ 0.05192025,  0.59274   ,  0.1211025 , -0.02758251, -0.32590252,
        0.4873125 ,  0.08731876,  0.0392628 ,  0.16041625,  0.03498251,
        0.22566   , -0.079695  ,  0.07848275,  0.14854674,  0.2162875 ,
       -0.17473349,  0.20247525,  0.455735  , -0.6060775 ,  0.62728506,
       -0.05533701,  0.19815248, -0.0554575 , -0.3169325 ,  0.14453602,
        0.44995502, -0.13674401, -0.39151236,  0.342488  , -0.038004  ,
       -0.30873   ,  0.8875    ,  0.16554502, -0.09631325,  0.23830576,
       -0.10760999, -0.219939  ,  0.21443748,  0.6329025 , -0.49880248,
       -0.17758176, -0.05304649, -0.07534557, -0.45472002, -0.4974125 ,
       -0.15129998, -0.11091749, -0.19589199,  0.20618378, -0.87854004,
       -0.1415385 ,  0.09702326,  0.289347  ,  0.93947   ,  0.20545   ,
       -2.203025  ,  0.31823   ,  0.38767502,  1.13689   ,  0.527365  ,
        0.31559   ,  0.86213243, -0.5244945 ,  0.01804505,  0.27870604,
        0.27692425,  0.60059696,  0.07509273, -0.02488326,  0.04

In [134]:
vec2

array([ 6.19177520e-02,  2.64880002e-01,  4.73089755e-01, -8.84600133e-02,
       -1.83144018e-01, -2.00250000e-02, -3.08398753e-01, -2.49302492e-01,
        3.00510004e-02,  6.68507516e-02,  3.16017509e-01,  6.82852492e-02,
        3.35029006e-01,  3.85558486e-01,  4.26090389e-01,  1.67630017e-01,
        2.42317498e-01,  3.67292464e-01, -4.58935022e-01,  4.89197552e-01,
       -1.53804511e-01,  3.08878750e-01,  4.73049954e-02, -3.59152496e-01,
       -1.05886742e-01,  6.09379768e-01, -1.02566257e-01, -4.77104992e-01,
        3.68935466e-01, -7.07274899e-02, -2.81487405e-02,  4.45160478e-01,
        7.87040144e-02, -1.98642507e-01,  1.33470744e-01,  1.68742999e-01,
       -4.28422511e-01,  7.11849988e-01,  3.83485019e-01, -1.22955009e-01,
       -1.65536001e-01, -7.12015033e-02, -2.23225746e-02, -2.96917528e-01,
       -1.58582479e-01, -2.04081997e-01, -4.81499955e-02, -1.21404484e-01,
       -5.32750040e-02, -7.56496489e-01,  1.22986227e-01,  1.12602994e-01,
        5.42472482e-01,  

In [135]:
### Shape of the first vector
vec1.shape

(100,)

In [136]:
### Shape of the second vector
vec2.shape

(100,)

In [137]:
vec1.ndim

1

## **OBSERVATIONS:**

1.  Both the vectors are of 1d and cosine similarity expects the input to be 2D.

In [138]:
vec1 = vec1.reshape(1,-1)

In [139]:
### Shape of the first vector
vec1.shape

(1, 100)

In [140]:
vec1.ndim

2

In [141]:
vec2 = vec1.reshape(1,-1)

In [142]:
### Shape of the shape vector
vec2.shape

(1, 100)

In [143]:
vec2.ndim

2

## **OBSERVATIONS**

1. Both the input vectors have been converted in 2D form.

In [144]:
#### Compute the cosine similarity
cosine = cosine_similarity(vec1,vec2)

In [145]:
cosine

array([[0.9999999]], dtype=float32)

## **OBSERVATIONS:**

1.  The cosine similarity between two sentences is 0.99 which states that the two sentences are very much similar with respect to each other.