## **BERT Transformers**

1. BERT stands for Bidirectional Encoder Representations from Transformres. It refers to the technique of converting the text into the dense dimensional vectors known as Embeddings.

2.  These embeddings can capture the meaning and the context of words and sentences.

In [120]:
!pip install transformers torch

## **Step 1: Import all the necessary libraries**

In [121]:
from transformers import BertModel, BertTokenizer
import torch

## **OBSERVATIONS:**

1.  transformers ---------->  

    (a.)  A transformer has a predefined BERT model.

    (b.)  It is a deep learning architecture used in NLP thst uses Self Attention Mechanisms to capture the relationship between the words in the sentences.

2.  BertTokenizer ---------->

    (a.)  It converts the sentences into the word tokens

    (b.)  converts the tokens into the token id

    (c.)  Adding special tokens like [CLS] and [SEP].

3.  BertModel --------------->

    (a.)  BERTModel loads a pretrained BERT neural network.

4.  torch ------------------->

    (a.)  It is a deep learning library used for performing te deep learning operations.

## **Step 2: Load the BERT Tokenizer**

In [122]:
#### Load the BERT Tokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [123]:
tokenizer

BertTokenizer(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

## **OBSERVATIONS:**

1.  BertTokenizer -------->  

    It converts the sentences into words

    It converts the words into token id.

    It adds the special tokens like [CLS] and [SEP].

2.  Here the object of the Bert Tokenizer calls the function from_pretrained and loads the pre trained BERT Model.

3. The main objective of the above statement is to load a pre-trained BERT Tokenizer named 'bert-base-uncased' that converts the text into such a format that the BERT model can easily understand.

    (a.)  bert --------> converts the text into embeddings that capture the semantic meaning of the words in the sentences.

    (b.)  base -------->  defines the model size. BERT base has 3200 words/subwords

    (c.)  uncased ------> converts everything to lower case.

## **Step 3: Load the BERT Model**

In [124]:
#### Load a pre trained model
model = BertModel.from_pretrained('bert-base-uncased')

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [125]:
model

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (token_type_embeddings): Embedding(2, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-11): 12 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
  

## **OBSERVATIONS**

1.  The main objective of the above statement is to load a pre-trained BERT Model named 'bert-base-uncased' that converts the tokenized text into the context based numerical representations called as embeddings.

## **Step 4: Define the Input Sentence:**

In [126]:
#### Define the input text
text = "I love data science"

In [127]:
text

'I love data science'

## **Step 5: Tokenize the Sentence**

In [128]:
#### perform the tokenization of the input text
ans = tokenizer(
    text,
    max_length = 10,
    padding = True,
    truncation = True,
    return_tensors = 'pt'
)

In [129]:
ans

{'input_ids': tensor([[ 101, 1045, 2293, 2951, 2671,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1]])}

##**OBSERVATIONS**

1.  The main role of performing the tokenizer is to convert the input text into model based representation form in such a way that the BERT model can understand it easily.

2.  The tokenizer model has been trained with the following parameters :-----

    (a.)  text ---------->  it specifies the input text

    (b.)  max_length = 10 ------>  maximum length of the input text is 10

    (c.)  padding = True ------> makes sure that all the input sequences are of the equal length

    (d.)  truncation = True ------> if the length of the input sequence is greater than the max length then that portion of the length greater than the max length is cut off.

    (e.)  return_sensors = 'pt' ----->  Returns the output in the form of the PyTorch Sensors.

  3.  Here this model returns the output in form of

        {
            input_ids   ,

            attention_mask
        }

       (a.)  input_ids -------> It specifies the numerical representation of the words.

       (b.)   attention_mask ---------> It specifies which tokens are real and which are padded.

              (i.)  if Token is 1 ----------> real

              (ii.) if token is 0 ----------> padded.

## **Step 6: Generate Embeddings**

In [130]:
### Generate the embeddings

with torch.no_grad():
  outputs = model(**ans)

In [131]:
outputs

BaseModelOutputWithPoolingAndCrossAttentions(last_hidden_state=tensor([[[ 0.1780,  0.1575,  0.0917,  ..., -0.0813,  0.1342,  0.2354],
         [ 0.6465,  0.0906, -0.2098,  ..., -0.2241,  0.7832,  0.4494],
         [ 1.2863,  0.7920,  0.2601,  ...,  0.1102,  0.6732,  0.2334],
         [-0.1125, -0.3155,  0.7293,  ..., -0.2380,  0.3858,  0.0866],
         [-0.3269, -0.4303, -0.2545,  ...,  0.6810,  0.3645, -0.2278],
         [ 0.8227,  0.1161, -0.1685,  ...,  0.1160, -0.6402, -0.2483]]]), pooler_output=tensor([[-0.7458, -0.1519,  0.5371,  0.4485, -0.2743, -0.1097,  0.7619,  0.1196,
          0.2546, -0.9984,  0.2546,  0.0430,  0.9562, -0.2757,  0.8463, -0.3796,
          0.0664, -0.4263,  0.2288, -0.5538,  0.4354,  0.5996,  0.5666,  0.1885,
          0.2689,  0.0068, -0.3739,  0.8523,  0.8843,  0.5852, -0.4940,  0.1275,
         -0.9596, -0.0878,  0.5893, -0.9389,  0.0945, -0.6521,  0.0746,  0.0589,
         -0.7920,  0.1902,  0.9743, -0.4912, -0.2007, -0.2592, -0.9966,  0.1695,
        

In [132]:
outputs.last_hidden_state

tensor([[[ 0.1780,  0.1575,  0.0917,  ..., -0.0813,  0.1342,  0.2354],
         [ 0.6465,  0.0906, -0.2098,  ..., -0.2241,  0.7832,  0.4494],
         [ 1.2863,  0.7920,  0.2601,  ...,  0.1102,  0.6732,  0.2334],
         [-0.1125, -0.3155,  0.7293,  ..., -0.2380,  0.3858,  0.0866],
         [-0.3269, -0.4303, -0.2545,  ...,  0.6810,  0.3645, -0.2278],
         [ 0.8227,  0.1161, -0.1685,  ...,  0.1160, -0.6402, -0.2483]]])

## **OBSERVATIONS**

1.  It allows the BERT model to run in such a way that the outputs produced by the BERT model does not involve ant computation of the gradient

2.  It explains about the contextual embeddings for every token in the input sentence.

In [133]:
outputs.last_hidden_state.shape

torch.Size([1, 6, 768])

## **Step 7: Give the output of the model**

In [134]:
### Output for the model
answers = outputs.last_hidden_state

In [135]:
answers

tensor([[[ 0.1780,  0.1575,  0.0917,  ..., -0.0813,  0.1342,  0.2354],
         [ 0.6465,  0.0906, -0.2098,  ..., -0.2241,  0.7832,  0.4494],
         [ 1.2863,  0.7920,  0.2601,  ...,  0.1102,  0.6732,  0.2334],
         [-0.1125, -0.3155,  0.7293,  ..., -0.2380,  0.3858,  0.0866],
         [-0.3269, -0.4303, -0.2545,  ...,  0.6810,  0.3645, -0.2278],
         [ 0.8227,  0.1161, -0.1685,  ...,  0.1160, -0.6402, -0.2483]]])

In [136]:
### Shape of the model
answers.shape

torch.Size([1, 6, 768])

## **OBSERVATIONS**

1.  outputs.last_hidden_state ------->  It explains about the contextual embeddings for each input tokens in the text.

2.  The size of the output is (batch_size, sequence_length,hidden_size).

## **Step 8: Extract Token Embeddings**

In [137]:
token_embeddings = outputs.last_hidden_state

In [138]:
token_embeddings

tensor([[[ 0.1780,  0.1575,  0.0917,  ..., -0.0813,  0.1342,  0.2354],
         [ 0.6465,  0.0906, -0.2098,  ..., -0.2241,  0.7832,  0.4494],
         [ 1.2863,  0.7920,  0.2601,  ...,  0.1102,  0.6732,  0.2334],
         [-0.1125, -0.3155,  0.7293,  ..., -0.2380,  0.3858,  0.0866],
         [-0.3269, -0.4303, -0.2545,  ...,  0.6810,  0.3645, -0.2278],
         [ 0.8227,  0.1161, -0.1685,  ...,  0.1160, -0.6402, -0.2483]]])

## **OBSERVATIONS:**

1.  Final embeddings after all 12 transformer layers

## **Step 9: Print Shape of the model:**

In [139]:
### print the shape of the token embeddings
print('Shape of the token embeddings is:', token_embeddings.shape)

Shape of the token embeddings is: torch.Size([1, 6, 768])


## **OBSERVATIONS:**

1.  The size of the output is (batch_size, sequence_length,hidden_size).

## **Step 10: Print CLS Embedding**

In [145]:
## Print CLS Embedding

print(token_embeddings[0][0][:10])

tensor([ 0.1780,  0.1575,  0.0917, -0.0949, -0.1189, -0.3091,  0.0184,  0.5188,
         0.0239, -0.1420])


## **OBSERVATIONS:**

1.  It provides the shape of the token embeddings with the

      (a.)  first sentence

      (b.)  first token

      (c.) first ten numbers

## **CONCLUSIONS**

1.  The main role of using BERT Transformers is to convert the text into the context aware embeddings in such a way that the machines can understand the context of the words based on the surrounding words.