#### **Word Embeddings**

1.  Word Embeddings is a text representation technique that is used to convert each and every word into the dense numerical vector.

2.  The words with the similar meanings will have the same dense valued representations.

## **Example:**

| Word  | Vector                 |
| ----- | ---------------------- |
| King  | [0.25, 0.81, 0.44,...] |
| Queen | [0.28, 0.79, 0.47,...] |
| Apple | [0.91, 0.12, 0.33,...] |


## **Importance of Word Embeddings:**

1.  It is used to find out the similarities between two words by computing the similarity scores in the form of dense dimensional numerical vectors.

2. It helps in finding out the meaning behind each and every word in the input text.

3.  It is used to perform the dimensionality reduction.

4.  It helps in improving the speed and the accuracy of the model.

5.  It helps in finding out the relation of one word with respect to the other based on the similarity scores.



**Example:**

1.  king - man + woman = queen

## **Write a simple end to end implementation based on Word Embeddings**


## **Steps used in this Algorithm:**

1.  Import all the necessary libraries

2.  Download all the necessary libraries for NLTK

3.  Define the corpus text

4.  Perform the normalization of the text

5.  Perform the Word tokenization on the text

6.  Remove all the english stop words from the input text.

7.  Train the Word2Vec Model using Skip-Gram architecture

8.  Explore Word Vectors

9.  Find out the vector representation of the words that are most similar to the words 'and' and 'machine'

10.  To show the list of all the words that the model has learnt for embedding


## **Skip Grams**

1.  The main idea behind the Skip-Grams is to predict the surrounding context input word based on the target word.

Ex:  I love machine learing.

  Let us consider, the target word = machine. Based on the target word, we need to predict the surrounding context input words.

  Let us consider the context window is of the size 2, it means we need to predict 2 surrounding context input word before the target word and 2 surrounding context input word after the target word.

  If the target = 'machine' ---------> 2 surrounding context input words predicted before the target are ('I','love') and after the target is ('learning').

## **How Skip Grams Works Internally**

1. The target word is converted into the dense dimensional numerical vector.

2. It is passed into the neural network model.

3. The target word predicts all the context input word independently.

4. Each context word predicts the probability score based on the softmax layer.


## **Step 1: Import all the necessary libraries**

In [1]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 20.3 MB/s eta 0:00:00


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk

from  nltk.tokenize import word_tokenize
from  nltk.corpus   import stopwords
from  nltk.stem     import WordNetLemmatizer
from  gensim.models import Word2Vec

## **OBSERVATIONS:**

1.  word_tokenize -------------> divides the sentences into the words

2.  gensim        -------------> a module used for embedding

3.  Word2Vec      -------------> finds out the relationship between two words in the text and gives the relationship in the form of dense numerical vector.

## **Step 2: Download all the necessary libraries for NLTK**

In [3]:
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

## **OBSERVATIONS:**

1.  punkt_tab ----------->  It is a library resource downloaded from NLTK used for tokenization purposes.

2.   averaged_perceptron_tagger_eng ------------>  It is used for POS Tagging.

## **Step 3: Define the sample text**

In [4]:
#### define the sample text

corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]

In [5]:
corpus

['Natural Language Processing and Machine Learning are closely related fields.',
 'Word embeddings are a type of word representation that allows words to be represented as vectors.',
 'Deep learning models are used for creating high-quality word embeddings.',
 'The meaning of words can be captured by training on large text datasets.',
 'Gensim is a popular library for training Word2Vec models in Python.']

## **OBSERVATIONS:**

1.  Here the corpus text has been defined.

## **Step 4: Perform the normalization of the text**

In [6]:
#### convert the corpus to text form

corpus = " ".join(corpus)

In [7]:
corpus

'Natural Language Processing and Machine Learning are closely related fields. Word embeddings are a type of word representation that allows words to be represented as vectors. Deep learning models are used for creating high-quality word embeddings. The meaning of words can be captured by training on large text datasets. Gensim is a popular library for training Word2Vec models in Python.'

In [8]:
from nltk.tokenize import RegexpTokenizer

#### Create an object for RegexpTokenizer

reg = RegexpTokenizer(r'\w+')

#### using the object of Regular expression tokenizer, remove all the punctutaions from the text
ans = reg.tokenize(corpus)

#### convert all the filtered text from lists to words
ans = " ".join(ans)

In [9]:
ans

'Natural Language Processing and Machine Learning are closely related fields Word embeddings are a type of word representation that allows words to be represented as vectors Deep learning models are used for creating high quality word embeddings The meaning of words can be captured by training on large text datasets Gensim is a popular library for training Word2Vec models in Python'

## **OBSERVATIONS:**

1.  Here the normalization of the corpus text has been performed in which all the punctutaions and the special symbols have been removed from the text.

##  **Step 5:  Perform the Word tokenization on the text**

In [10]:
from nltk.tokenize import word_tokenize

#### perform the word tokenization on the filtered text
words = word_tokenize(ans)

#### convert all the words in the text to lower case
words = [x.lower() for x in words]
print(words)

['natural', 'language', 'processing', 'and', 'machine', 'learning', 'are', 'closely', 'related', 'fields', 'word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', 'deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high', 'quality', 'word', 'embeddings', 'the', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', 'gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'word2vec', 'models', 'in', 'python']


## **Step 6: Define all the english stop words and remove them from the text**

In [11]:
#### define all the english stopwords
from nltk.corpus import stopwords
english_stopwords = set(stopwords.words("english"))

#### remove all the stopwords from the text
res = [x for x in words if (x not in english_stopwords)]

In [12]:
res

['natural',
 'language',
 'processing',
 'machine',
 'learning',
 'closely',
 'related',
 'fields',
 'word',
 'embeddings',
 'type',
 'word',
 'representation',
 'allows',
 'words',
 'represented',
 'vectors',
 'deep',
 'learning',
 'models',
 'used',
 'creating',
 'high',
 'quality',
 'word',
 'embeddings',
 'meaning',
 'words',
 'captured',
 'training',
 'large',
 'text',
 'datasets',
 'gensim',
 'popular',
 'library',
 'training',
 'word2vec',
 'models',
 'python']

## **OBSERVATIONS:**

1.  All the english stop words have been removed from the input text.

## **Step 7: Define the list of tokenized sentences**

In [13]:
#### Define the corpus text

corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]



In [14]:
##### To construct the list of all the tokenized words in the list

res = [word_tokenize(x.lower()) for x in corpus]

res

[['natural',
  'language',
  'processing',
  'and',
  'machine',
  'learning',
  'are',
  'closely',
  'related',
  'fields',
  '.'],
 ['word',
  'embeddings',
  'are',
  'a',
  'type',
  'of',
  'word',
  'representation',
  'that',
  'allows',
  'words',
  'to',
  'be',
  'represented',
  'as',
  'vectors',
  '.'],
 ['deep',
  'learning',
  'models',
  'are',
  'used',
  'for',
  'creating',
  'high-quality',
  'word',
  'embeddings',
  '.'],
 ['the',
  'meaning',
  'of',
  'words',
  'can',
  'be',
  'captured',
  'by',
  'training',
  'on',
  'large',
  'text',
  'datasets',
  '.'],
 ['gensim',
  'is',
  'a',
  'popular',
  'library',
  'for',
  'training',
  'word2vec',
  'models',
  'in',
  'python',
  '.']]

## **OBSERVATIONS:**

1.  After performing word tokenization, we have obtained the list of all the tokenized sentences which can be the input for Word2Vec model.

## **Step 8: Train the Word2Vec model**

In [15]:
#### Train the Word2Vec model
skipgrams = Word2Vec(
    sentences     = res          ,
    vector_size   = 50           ,
    window        = 3            ,
    min_count     = 1            ,
    sg            = 1            ,
    epochs        = 100
)

In [16]:
skipgrams

## **OBSERVATIONS:**

1.  The skip grams Word2Vec model has been created with the help of the following parameters :-----

    (a.)  sentences = res -------->  list of all the tokenized sentences

    (b.)  vector    =  50 -------->  size of the dense dimensional vectore form of input word

    (c.)  window = 3 -------------->  size of context window. if window = 3 then 3 context window before the target and 3 after the target.

    (d.)  min_count = 1------------->  minimum number of words needed to form a vocabulary.

    (e.)  sg = 1 ------------------>  Type of model architecture where the input context word is predicted from the target word.

    (f.)  epochs = 100 ------------>  No of iterations needed to train the model.

## **Step 9: Get the list of all the vocabularies from the dictionaries**

In [17]:
#### get all the vocabularies from the dictionaries

words = skipgrams.wv.key_to_index

In [18]:
words

{'.': 0,
 'word': 1,
 'are': 2,
 'training': 3,
 'for': 4,
 'models': 5,
 'be': 6,
 'words': 7,
 'of': 8,
 'a': 9,
 'embeddings': 10,
 'learning': 11,
 'python': 12,
 'in': 13,
 'word2vec': 14,
 'library': 15,
 'popular': 16,
 'is': 17,
 'gensim': 18,
 'datasets': 19,
 'text': 20,
 'large': 21,
 'on': 22,
 'by': 23,
 'captured': 24,
 'can': 25,
 'meaning': 26,
 'the': 27,
 'high-quality': 28,
 'creating': 29,
 'used': 30,
 'deep': 31,
 'vectors': 32,
 'as': 33,
 'represented': 34,
 'to': 35,
 'allows': 36,
 'that': 37,
 'representation': 38,
 'type': 39,
 'fields': 40,
 'related': 41,
 'closely': 42,
 'machine': 43,
 'and': 44,
 'processing': 45,
 'language': 46,
 'natural': 47}

## **OBSERVATIONS:**

1.  key_to_index helps in getting the list of all the vocabularies from the corpus text.

## **Step 10: Explore the word vectors**

In [19]:
#### Get the dense dimensional numerical representation of the word 'natural'

skipgrams.wv['natural']

array([ 0.00735378,  0.00497393,  0.01114157,  0.01594871, -0.01240279,
        0.01517002,  0.01622976,  0.02488607,  0.007512  , -0.01110035,
       -0.00865914, -0.00417537,  0.00180949,  0.02212013,  0.00360116,
        0.0115539 ,  0.01197331, -0.01301393,  0.0101827 ,  0.01140497,
       -0.00013241,  0.00652788, -0.00716085, -0.01081918,  0.01669241,
       -0.00234791,  0.01293053,  0.00885004, -0.00451266,  0.00574325,
       -0.01230733, -0.00705541,  0.00379279,  0.00600469, -0.00319157,
        0.00208915, -0.01008951,  0.01859779, -0.0193346 ,  0.0138065 ,
        0.01430457, -0.01492667, -0.0115025 , -0.01158754, -0.0054677 ,
        0.01225077,  0.01911482,  0.00240991,  0.00264861,  0.02230951],
      dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'natural'.

In [20]:
#### Get the dense dimensional numerical representation of the word 'training'

skipgrams.wv['training']

array([ 0.01862395, -0.01831281,  0.00043344,  0.00834335, -0.00369054,
        0.01569102,  0.03314671,  0.03250148, -0.00635151,  0.00264269,
       -0.02217461, -0.00267231,  0.00659362, -0.0038236 ,  0.01101297,
        0.021617  ,  0.03074017,  0.00392409,  0.0037899 , -0.00482885,
        0.00193873, -0.01218854,  0.03189296,  0.01962004, -0.00224136,
       -0.00385152, -0.01636671,  0.01284105,  0.00722833, -0.00875682,
       -0.03441574, -0.00153307,  0.0141016 , -0.02434452,  0.00134096,
       -0.00223902,  0.01778134, -0.02249287,  0.00091185, -0.01377074,
        0.021655  , -0.00549146,  0.00133796, -0.00085573,  0.01135634,
       -0.00094671,  0.01048214, -0.01195065, -0.01499497,  0.01978878],
      dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'training'.

In [21]:
#### Get the dense dimensional numerical representation of the word 'and'

skipgrams.wv['and']

array([ 7.76391884e-04,  9.13006905e-03,  4.92043234e-03,  2.16485839e-02,
        3.67378561e-05, -1.14126895e-02,  3.65891145e-03,  1.16187232e-02,
       -9.19059757e-03, -2.18484420e-02, -1.32288588e-02, -1.69963464e-02,
        1.99381914e-02,  1.11467065e-02,  1.79607235e-02,  1.81943681e-02,
       -5.48013020e-03,  1.20153315e-02,  1.25141107e-02, -3.99846351e-03,
        1.08411601e-02,  1.44450553e-02, -9.62403044e-03,  2.03738566e-02,
        1.39736291e-02,  2.21483465e-02, -1.73616484e-02,  2.04764623e-02,
        1.22453421e-02, -2.82903155e-03, -1.87412500e-02,  6.22507511e-03,
       -1.21589610e-02, -1.61428545e-02,  6.14509825e-03,  1.72968823e-02,
        2.51329802e-02, -9.67694167e-03, -2.09322739e-02,  1.90725122e-02,
        2.16437131e-02, -9.07084811e-03, -1.84230395e-02, -3.08223884e-03,
       -8.95738485e-04, -9.18841735e-03,  9.08656744e-04, -3.82377347e-03,
       -4.78508603e-03, -7.82969035e-03], dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'and'.

In [22]:
#### Get the dense dimensional numerical representation of the word 'machine'

skipgrams.wv['machine']

array([ 0.01449395,  0.01274676, -0.01908677,  0.00811913, -0.01309085,
       -0.01845687,  0.00691228,  0.00757935, -0.01610652, -0.01883319,
       -0.00672934,  0.01057118, -0.00780058,  0.01911717,  0.00090596,
        0.00747844,  0.02598679,  0.0165633 , -0.01177003, -0.0002098 ,
        0.01229269,  0.01556609,  0.00862363, -0.00683072,  0.00299018,
       -0.00575807,  0.0019207 ,  0.01826918,  0.00919217,  0.0179157 ,
       -0.0222159 , -0.01529316,  0.01461737, -0.00303525, -0.01417821,
        0.00309936,  0.01374001, -0.0056397 , -0.01244262,  0.00963698,
        0.02909352, -0.01626427, -0.00224196,  0.00165029, -0.00580131,
       -0.00549196, -0.01131593,  0.01492768, -0.0099291 ,  0.01232163],
      dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'machine'.

## **Step 11: Find out the vector representations of the words most similar to 'and' and 'machine'**

In [23]:
### Vector representation of all the words most similar to 'and'

skipgrams.wv.most_similar('and')

[('are', 0.4520156681537628),
 ('used', 0.45019078254699707),
 ('by', 0.43641555309295654),
 ('a', 0.4132101535797119),
 ('related', 0.4129936397075653),
 ('be', 0.40556907653808594),
 ('to', 0.38448694348335266),
 ('word2vec', 0.3798808753490448),
 ('machine', 0.37022748589515686),
 ('learning', 0.36773473024368286)]

## **OBSERVATIONS**

1.  The above are the list of words that are most similar to 'and' along with the vector representation.

In [24]:
### Vector representation of all the words most similar to 'machine'

skipgrams.wv.most_similar('machine')

[('.', 0.5157498717308044),
 ('a', 0.46377620100975037),
 ('are', 0.43209725618362427),
 ('word2vec', 0.42735937237739563),
 ('creating', 0.3958236575126648),
 ('high-quality', 0.3800097107887268),
 ('and', 0.37022748589515686),
 ('word', 0.3700869083404541),
 ('processing', 0.3548687994480133),
 ('training', 0.3465283215045929)]

## **OBSERVATIONS**

1.  The above are the list of words that are most similar to 'machine' along with the vector representation.