## **Word Embeddings**

1.  Word Embedding refers to the technique of converting each and every input word into the numerical dense dimensional vectors.

2.  The words with the similar meanings with have the same dense dimensional vectors.


## **Example:**

| Word  | Vector                 |
| ----- | ---------------------- |
| King  | [0.25, 0.81, 0.44,...] |
| Queen | [0.28, 0.79, 0.47,...] |
| Apple | [0.91, 0.12, 0.33,...] |


## **Importance of Word Embeddings:**

1.  It is used to find out the similarities between two words by computing the similarity scores in the form of dense dimensional numerical vectors.

2. It helps in finding out the meaning behind each and every word in the input text.

3.  It is used to perform the dimensionality reduction.

4.  It helps in improving the speed and the accuracy of the model.

5.  It helps in finding out the relation of one word with respect to the other based on the similarity scores.

**Example:**

1.  king - man + woman = queen

## **Write a simple end to end implementation based on Word Embeddings**


## **Steps used in this Algorithm:**

1.  Import all the necessary libraries

2.  Download all the necessary libraries for NLTK

3.  Define the corpus text

4.  Perform the normalization of the text

5.  Perform the Word tokenization on the text

6.  Remove all the english stop words from the input text.

7.  Train the Word2Vec Model using CBOW architecture

8.  Explore Word Vectors

9.  Find out the vector representation of the words that are most similar to the words 'and' and 'machine'

10.  To show the list of all the words that the model has learnt for embedding


## **CBOW**

1.  CBOW stands for Continuous Bag Of Words.

2.  The main idea behind this is to predict the target word based on the surrounding context  input word.

Ex:   I love machine learning

Context window = 2, it means we need to predict the target word based on the 2 surrounding context input word before it and 2 surrounding context input word after it.

      I love _ learning

      It forms the context window of the size 2 and forms the context input words

      I,love,_,learning

      Based on the above context input words, it predicts the target word: machine

      I,love,machine,learning.

## **How CBOW Works Internally**

1.  All the context input words are converted into the dense dimensional vectors.

2.  Then the dense dimensional numerical vectors are all averaged.

3.  This provides the probability of the target word.

## **Step 1: Import all the necessary libraries**


In [481]:
!pip install gensim

In [482]:
import  numpy   as  np
import  pandas  as  pd
import  matplotlib.pyplot as plt
import  seaborn as  sns

from    nltk.tokenize  import word_tokenize
from    nltk.corpus    import stopwords
from    nltk.stem      import WordNetLemmatizer

from    gensim.models  import Word2Vec

## **OBSERVATIONS:**

1.  word_tokenize ---------->  Converts the sentences into words

2.  gensim        ---------->  a model considered for word embedding

3.   Word2Vec     ---------->  it converts the word into the dense dimensional numerical vectors.

## **Step 2: Download the necessary resources required for NLTK**

In [483]:
## Download the necessary library required for NLTK
import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('stopwords')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## **OBSERVATIONS:**

1.  punkt_tab ------->  It is a resource downloaded from NLTK required for tokenization.

2.  averaged_perceptron_tagger_eng ---->  It is needed for POS Tagging.

3.  stopwords -------->  It is used for the removal of the stopwords.

## **Step 3: Define the Sample Text**

In [484]:
#### define the sample text
corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]

In [485]:
corpus

['Natural Language Processing and Machine Learning are closely related fields.',
 'Word embeddings are a type of word representation that allows words to be represented as vectors.',
 'Deep learning models are used for creating high-quality word embeddings.',
 'The meaning of words can be captured by training on large text datasets.',
 'Gensim is a popular library for training Word2Vec models in Python.']

## **OBSERVATIONS:**

1.  Here the corpus input text has been defined.

In [486]:
### convert the corpus text into the text form

corpus = " ".join(corpus)

In [487]:
corpus

'Natural Language Processing and Machine Learning are closely related fields. Word embeddings are a type of word representation that allows words to be represented as vectors. Deep learning models are used for creating high-quality word embeddings. The meaning of words can be captured by training on large text datasets. Gensim is a popular library for training Word2Vec models in Python.'

##  **Step 4:  Perform the Word tokenization on the text**

In [488]:
#### perform word tokenization on the corpus text

words = word_tokenize(corpus)

In [489]:
words

['Natural',
 'Language',
 'Processing',
 'and',
 'Machine',
 'Learning',
 'are',
 'closely',
 'related',
 'fields',
 '.',
 'Word',
 'embeddings',
 'are',
 'a',
 'type',
 'of',
 'word',
 'representation',
 'that',
 'allows',
 'words',
 'to',
 'be',
 'represented',
 'as',
 'vectors',
 '.',
 'Deep',
 'learning',
 'models',
 'are',
 'used',
 'for',
 'creating',
 'high-quality',
 'word',
 'embeddings',
 '.',
 'The',
 'meaning',
 'of',
 'words',
 'can',
 'be',
 'captured',
 'by',
 'training',
 'on',
 'large',
 'text',
 'datasets',
 '.',
 'Gensim',
 'is',
 'a',
 'popular',
 'library',
 'for',
 'training',
 'Word2Vec',
 'models',
 'in',
 'Python',
 '.']

## **OBSERVATIONS:**

1.  Here the entire input corpus text has been converted into the words.

## **Step 5: Define all the english stop words and remove them from the text**

In [490]:
#### define all the english stop words

english_stopwords = set(stopwords.words("english"))

In [491]:
english_stopwords

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [492]:
#### Remove all the english stop words from the tokenized words

res = [x for x in words if(x not in english_stopwords)]

In [493]:
res

['Natural',
 'Language',
 'Processing',
 'Machine',
 'Learning',
 'closely',
 'related',
 'fields',
 '.',
 'Word',
 'embeddings',
 'type',
 'word',
 'representation',
 'allows',
 'words',
 'represented',
 'vectors',
 '.',
 'Deep',
 'learning',
 'models',
 'used',
 'creating',
 'high-quality',
 'word',
 'embeddings',
 '.',
 'The',
 'meaning',
 'words',
 'captured',
 'training',
 'large',
 'text',
 'datasets',
 '.',
 'Gensim',
 'popular',
 'library',
 'training',
 'Word2Vec',
 'models',
 'Python',
 '.']

In [494]:
#### Convert the filtered word to text form

res = " ".join(res)

In [495]:
res

'Natural Language Processing Machine Learning closely related fields . Word embeddings type word representation allows words represented vectors . Deep learning models used creating high-quality word embeddings . The meaning words captured training large text datasets . Gensim popular library training Word2Vec models Python .'

## **OBSERVATIONS:**

1.  All the english stop words have been removed from the input text.

## **Step 6: Perform the normalization on the corpus text**

In [496]:
#### Remove all the punctuations and the special symbols from the text

from nltk.tokenize import RegexpTokenizer

#### create an object for Reg exp tokenizer
reg = RegexpTokenizer(r'\w+')

#### apply the object of reegular expression on the text to remove all the punctuations and special symbols from the text
ans = reg.tokenize(res)

In [497]:
ans

['Natural',
 'Language',
 'Processing',
 'Machine',
 'Learning',
 'closely',
 'related',
 'fields',
 'Word',
 'embeddings',
 'type',
 'word',
 'representation',
 'allows',
 'words',
 'represented',
 'vectors',
 'Deep',
 'learning',
 'models',
 'used',
 'creating',
 'high',
 'quality',
 'word',
 'embeddings',
 'The',
 'meaning',
 'words',
 'captured',
 'training',
 'large',
 'text',
 'datasets',
 'Gensim',
 'popular',
 'library',
 'training',
 'Word2Vec',
 'models',
 'Python']

## **OBSERVATIONS:**

1.All the punctuations and the special symbols have been removed from the text.

In [498]:
#### Convert it into text form

ans = " ".join(ans)

In [499]:
ans

'Natural Language Processing Machine Learning closely related fields Word embeddings type word representation allows words represented vectors Deep learning models used creating high quality word embeddings The meaning words captured training large text datasets Gensim popular library training Word2Vec models Python'

## **Step 7: Define the list of tokenized sentences**

In [500]:
### define the list of tokenized sentences

corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]

In [501]:
#### perform the word tokenization on the corpus text

res = [word_tokenize(x.lower()) for x in corpus if(x != '')]

print(res)

[['natural', 'language', 'processing', 'and', 'machine', 'learning', 'are', 'closely', 'related', 'fields', '.'], ['word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', '.'], ['deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high-quality', 'word', 'embeddings', '.'], ['the', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', '.'], ['gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'word2vec', 'models', 'in', 'python', '.']]


## **OBSERVATIONS:**

1. After applying word tokenization on each sentences in the list, it has become the list of all the tokenized sentences that can be the input for the CBOW Word2Vec model.

## **Step 8: Train the Word2Vec model**

In [502]:
## Train the Word2Vec model

cbow = Word2Vec(
    sentences   =  res             ,
    vector_size =   50             ,
    window      =    3             ,
    min_count   =    1             ,
    sg          =    0             ,
    epochs      =    100
)

In [503]:
cbow

## **OBSERVATIONS:**

1.  The cbow Word2Vec model has been created with the help of the following parameters :-----

    (a.)  sentences = res -------->  list of all the tokenized sentences

    (b.)  vector    =  50 -------->  size of the dense dimensional vectore form of input word

    (c.)  window = 3 -------------->  size of context window. if window = 3 then 3 context window before the target and 3 after the target.

    (d.)  min_count = 1------------->  minimum number of words needed to form a vocabulary.

    (e.)  sg = 0 ------------------>  Type of model architecture where the input context word is predicted from the target word.

    (f.)  epochs = 100 ------------>  No of iterations needed to train the model.

## **Step 9: Get the list of all the vocabularies from the dictionaries**

In [504]:
#### Get all the vocabularies from the dictioanries

words = cbow.wv.key_to_index

In [505]:
words

{'.': 0,
 'word': 1,
 'are': 2,
 'training': 3,
 'for': 4,
 'models': 5,
 'be': 6,
 'words': 7,
 'of': 8,
 'a': 9,
 'embeddings': 10,
 'learning': 11,
 'python': 12,
 'in': 13,
 'word2vec': 14,
 'library': 15,
 'popular': 16,
 'is': 17,
 'gensim': 18,
 'datasets': 19,
 'text': 20,
 'large': 21,
 'on': 22,
 'by': 23,
 'captured': 24,
 'can': 25,
 'meaning': 26,
 'the': 27,
 'high-quality': 28,
 'creating': 29,
 'used': 30,
 'deep': 31,
 'vectors': 32,
 'as': 33,
 'represented': 34,
 'to': 35,
 'allows': 36,
 'that': 37,
 'representation': 38,
 'type': 39,
 'fields': 40,
 'related': 41,
 'closely': 42,
 'machine': 43,
 'and': 44,
 'processing': 45,
 'language': 46,
 'natural': 47}

## **OBSERVATIONS:**

1.  key_to_index helps in getting the list of all the vocabularies from the corpus text.

## **Step 10: Explore the word vectors**

In [506]:
#### Get the dense dimensional numerical representation of the word 'natural'

cbow.wv['natural']

array([ 0.00699806,  0.00469796,  0.01108254,  0.01569879, -0.01242217,
        0.01562483,  0.01341129,  0.02114157,  0.00826154, -0.00840245,
       -0.00803872, -0.0024587 , -0.00141286,  0.02039655,  0.00273099,
        0.00932626,  0.00830445, -0.01621871,  0.01216197,  0.01455295,
       -0.00260283,  0.00551177, -0.01120573, -0.01162836,  0.01644766,
       -0.00464357,  0.01297208,  0.00513226, -0.00401876,  0.00629348,
       -0.00951927, -0.00496117,  0.00329364,  0.00802115, -0.0031375 ,
        0.00164507, -0.01367713,  0.01896198, -0.01835306,  0.01440091,
        0.01012293, -0.0143893 , -0.01136863, -0.0143218 , -0.00856171,
        0.01328081,  0.01916406,  0.00350576,  0.00128381,  0.01994897],
      dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'natural'.

In [507]:
#### Get the dense dimensional numerical representation of the word 'training'

cbow.wv['training']

array([ 0.01682093, -0.01759238,  0.00107221,  0.00764728, -0.00348085,
        0.01564886,  0.02275001,  0.01889095, -0.00400273,  0.01033596,
       -0.01837344,  0.00216467, -0.00288703, -0.00842384,  0.00840821,
        0.01554672,  0.02068344, -0.00597249,  0.01036537,  0.0065782 ,
       -0.00484935, -0.01469261,  0.01823916,  0.01561607, -0.00186402,
       -0.00899914, -0.01528675,  0.00094346,  0.01004312, -0.0078883 ,
       -0.02421928,  0.0034071 ,  0.01162123, -0.01717458,  0.00177302,
       -0.00365796,  0.00716695, -0.02032081,  0.00335671, -0.01006497,
        0.00921269, -0.00400842,  0.0032669 , -0.01040126,  0.00106175,
        0.00315365,  0.01053362, -0.00772449, -0.01825194,  0.01182027],
      dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'training'.

In [508]:
#### Get the dense dimensional numerical representation of the word 'and'
cbow.wv['and']

array([ 0.00018774,  0.0090975 ,  0.00483873,  0.02077695,  0.00037773,
       -0.01141587, -0.00036813,  0.00639544, -0.00805818, -0.01825272,
       -0.01182912, -0.01532571,  0.01545134,  0.00883123,  0.01715365,
        0.0151855 , -0.00994112,  0.0078078 ,  0.01504973,  0.00072297,
        0.00741111,  0.0129896 , -0.01509411,  0.0189632 ,  0.013627  ,
        0.01904808, -0.01716955,  0.01510367,  0.01333817, -0.00276821,
       -0.01487494,  0.0085975 , -0.01309427, -0.01296896,  0.00653372,
        0.01653673,  0.02061739, -0.00869386, -0.01938032,  0.01941955,
        0.01604813, -0.00865967, -0.01779248, -0.00709295, -0.00549124,
       -0.00767929,  0.00133798, -0.00175478, -0.00598082, -0.0106355 ],
      dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'and'.

In [509]:
#### Get the dense dimensional numerical representation of the word 'machine'
cbow.wv['machine']

array([ 1.38767501e-02,  1.27547709e-02, -1.94403455e-02,  7.10700080e-03,
       -1.30583849e-02, -1.88706126e-02,  2.37601483e-03,  1.51365413e-03,
       -1.54858893e-02, -1.52489319e-02, -5.61180850e-03,  1.24633871e-02,
       -1.23069454e-02,  1.63674857e-02,  2.08636593e-05,  4.30864701e-03,
        2.13472918e-02,  1.16836606e-02, -9.04008280e-03,  4.99267038e-03,
        8.19391292e-03,  1.39079476e-02,  2.84056971e-03, -8.08171555e-03,
        2.72642379e-03, -8.81033670e-03,  1.97464367e-03,  1.27054192e-02,
        1.05124600e-02,  1.86052434e-02, -1.72608197e-02, -1.30702471e-02,
        1.37978848e-02,  1.97771340e-04, -1.37183741e-02,  2.25852989e-03,
        8.79017171e-03, -5.04150009e-03, -1.11420834e-02,  1.01354253e-02,
        2.26622969e-02, -1.54554360e-02, -1.14744401e-03, -2.99247587e-03,
       -1.05237961e-02, -4.00301535e-03, -1.06647415e-02,  1.71461608e-02,
       -1.16504729e-02,  8.87040980e-03], dtype=float32)

## **OBSERVATIONS:**

1.  The above vector represents the dense dimensional numerical vector of the size 50 for the word 'machine'.

## **Step 11: Find out the vector representations of the words most similar to 'and' and 'machine'**

In [510]:
#### Vector representation of all the words most similar to 'and'

cbow.wv.most_similar('and')

[('used', 0.3690727949142456),
 ('by', 0.31513360142707825),
 ('are', 0.2984626293182373),
 ('a', 0.2782883644104004),
 ('related', 0.2708548903465271),
 ('to', 0.26222237944602966),
 ('be', 0.23448440432548523),
 ('processing', 0.23242348432540894),
 ('machine', 0.23120737075805664),
 ('language', 0.2278352528810501)]

## **OBSERVATIONS:**

1.  The above words are the list of all the words and their vector representations that are most similar to the word 'and'

In [511]:
#### Vector representation of all the words most similar to 'machine'

cbow.wv.most_similar('machine')

[('.', 0.3434886634349823),
 ('a', 0.3294759690761566),
 ('natural', 0.25562813878059387),
 ('word2vec', 0.2532128691673279),
 ('are', 0.24818044900894165),
 ('processing', 0.2366793304681778),
 ('and', 0.23120737075805664),
 ('creating', 0.22531941533088684),
 ('in', 0.20836141705513),
 ('high-quality', 0.20542047917842865)]

## **OBSERVATIONS:**

1.  The above words are the list of all the words and their vector representations that are most similar to the word 'machine'