## Numpy

It stands for Numerical Python.

It is used to work with arrays.

It is used for scientific mathematical computations.

In [7522]:
import numpy as np

# create a simple array

x = [10,20,30,40,50]

print('Array is:', x)

print('Type of Array is:', type(x))

print('-----------------------List into Numpy Array-------------------------------------------------')
### convert the list into numpy array
arr = np.array(x)

print('Array is:',arr)

print('Type of Array is:', type(arr))

Array is: [10, 20, 30, 40, 50]
Type of Array is: <class 'list'>
-----------------------List into Numpy Array-------------------------------------------------
Array is: [10 20 30 40 50]
Type of Array is: <class 'numpy.ndarray'>


## Numpy

It is a standard library used in Python

It is used with arrays for performing mathematical computations like linear algebra, fourier transformations, matrices

It stands for Numerical Python


## Why use Numpy ?

Ans  (i) Unlike arrays, Numpy arrays are used to perform many mathematical computations like linear algebra , fourier transformations etc and is very much faster to process.


## Why is NumPy Faster Than Lists ?

Ans   (i)  As all the elements in Numpy are stored in one contiguous memory location, so accessing all the elements in numpy array is very easy and can be easily manipulated.

In [7523]:
# create a simple numpy array

import numpy as np 

x = np.array([1,2,3,4,5])

print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7524]:
## checking the version of numpy array

print(np.__version__)

2.0.1


## Numpy

It is used to work with arrays. The array object in Numpy is called ndarray.


The ndarray is created using array() function.

In [7525]:
import numpy as np

res = np.array([1,2,3,4,5])

print(res)

print(type(res))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7526]:
# Use a tuple to create a NumPy array

import numpy as np 

tuples = (1,2,3,4,5)


arr = np.array(tuples)

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Dimensions in Arrays

A dimension in arrays is one level of array depth (nested arrays)


## (i) 0-D Arrays

Each element in an array is 0-D Array.

In [7527]:
import numpy as np

ans = np.array(42)

print(ans)

print(type(ans))

42
<class 'numpy.ndarray'>


## (ii)   1-D Arrays

An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array

In [7528]:
import numpy as np

x = np.array([1,2,3,4,5])

print(x)

print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## (ii) 2-D Arrays.

An array that has 1-D arrays as its elements is called a 2-D array.

It is often used to represent the matrix.

In [7529]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])

print(x)

print(x.ndim)

print(type(x))

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>


## (iii)  3-D arrays


An array that has 2-D arrays (matrices) as its elements is called 3-D array

It is used to represent 3 D Tensor.

In [7530]:
## Create a 3-D array with two 2-D arrays, both containing two arrays with the values 1,2,3 and 4,5,6

import numpy as np

x = np.array([[[1,2,3],[4,5,6],[1,2,3],[4,5,6]]])

print(x)

print(x.ndim)

print(type(x))

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]]
3
<class 'numpy.ndarray'>


## Check Number of Dimensions

In [7531]:
import numpy as np

a = np.array([1,2,3,4,5])

b = np.array([[1,2,3],[4,5,6]])

c = np.array([[[1,2,3],[4,5,6]]])

d = np.array([[[[1,2,3],[4,5,6]]]])

print(a.ndim)

print(b.ndim)

print(c.ndim)

print(d.ndim)

1
2
3
4


## Higher Dimensional Arrays

An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument

In [7532]:
import numpy as np

### Make the 1-D Array into 5-D
x = np.array([1,2,3,4,5], ndmin=5)

print(x)

print(type(x))

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>


## Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc

In [7533]:
## Get the first element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("First Element in the array is:", x[0])

First Element in the array is: 1


In [7534]:
## Get the second element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("Second Element in the array is:", x[1])

Second Element in the array is: 2


In [7535]:
## Get the third element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("Third Element in the array is:", x[2])

Third Element in the array is: 3


In [7536]:
## Get the fourth element from the following array

import numpy as np 

x = np.array([1,2,3,4,5])

print("Fourth Element in the array is:", x[3])

Fourth Element in the array is: 4


## Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element

In [7537]:
## Access the element on the first row, second column

import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr[0][1])

2


In [7538]:
## Access the element on the 2nd row, 5th column

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1][4])

10


## Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element

In [7539]:
## Access the third element of the second array of the first array

import numpy as np 

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])


print(arr[0][1][2])

6


## Negative Indexing

Use negative indexing to access an array from the end

In [7540]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ',arr[1][-1])

Last element from 2nd dim:  10


In [7541]:
import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr[1,1,0]

np.int64(7)

## NumPy Array Slicing


Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [7542]:
## Slice elements from index 1 to index 5 from the following array

import numpy as np 

x = np.array([1,2,3,4,5,6,7])


print(x[1:6])

[2 3 4 5 6]


In [7543]:
## elements from index 4 till the end of the array

x[4:]

array([5, 6, 7])

In [7544]:
## Slice elements from the beginning to index 4 (not included)

x[:4]

array([1, 2, 3, 4])

## Negative Slicing

Use the minus operator to refer to an index from the end

In [7545]:
## Slice from the index 3 from the end to index 1 from the end

x[-3:]

array([5, 6, 7])

In [7546]:
## Return every other element from index 1 to index 5

x[1:6]

array([2, 3, 4, 5, 6])

In [7547]:
## Return every other element from the entire array

x[::2]

array([1, 3, 5, 7])

In [7548]:
## From the second element, slice elements from index 1 to index 4 (not included)


import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


arr[1,1:4]

array([7, 8, 9])

In [7549]:
## From both elements, return index 2

arr[:,2]

array([3, 8])

In [7550]:
## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

arr[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

## Excercises on Numpy :

In [7551]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

##print(arr)

## Slice from the index 3 from the end to index 1 from the end

print(arr[-3:-1])

[5 6]


In [7552]:
## Return every other element from index 1 to index 5

arr[1:6:2]

array([2, 4, 6])

In [7553]:
## Return every other element from the entire array

arr[::2]

array([1, 3, 5, 7])

In [7554]:
## From the second element, slice elements from index 1 to index 4 (not included)

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr[1,1:4]

array([7, 8, 9])

In [7555]:
## From both elements, return index 2

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr[:,2]

array([3, 8])

In [7556]:
## From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

arr[:,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

## NumPy Data Types

By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

integer - used to represent integer numbers. e.g. -1, -2, -3

float - used to represent real numbers. e.g. 1.2, 42.42

boolean - used to represent True or False.

complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

## Checking the Data Type of an Array

The NumPy array object has a property called dtype that returns the data type of the array

In [7557]:
## Get the data type of an array object

import numpy as np

x = np.array([1,2,3,4,5])

print(x)

print(x.dtype)

[1 2 3 4 5]
int64


In [7558]:
## Get the data type of an array containing strings

import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr)

print(arr.dtype)

['apple' 'banana' 'cherry']
<U6


## Creating Arrays With a Defined Data Type

We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements

In [7559]:
import numpy as np

x = np.array([1,2,3,4,5],dtype='S')

print(x)

print(x.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [7560]:
## Create an array with data type 4 bytes integer

import numpy as np

x = np.array([1,2,3,4,5], dtype = 'i4')

print(x)

print(x.dtype)

[1 2 3 4 5]
int32


In [7561]:
## Change data type from float to integer by using 'i' as parameter value

import numpy as np 

x = np.array([1.1,2.1,3.1], dtype = 'i')

print(x)

print(x.dtype)

[1 2 3]
int32


In [7562]:
## Change data type from float to string by using 'S' as parameter value

import numpy as np 

x = np.array([1.1,2.1,3.1] , dtype = 'S')

print(x)

print(x.dtype)

[b'1.1' b'2.1' b'3.1']
|S3


In [7563]:
## Change data type from integer to boolean

import numpy as np 

x = np.array([1,0,3,-1], dtype = 'bool')

print(x)

[ True False  True  True]


## Shape of an Array

The shape of an array is the number of elements in each dimension 


## Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [7564]:
## Print the shape of a 2-D array

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [7565]:
## Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4

arr = np.array([1,2,3,4], ndmin=5)

print(arr)

print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## NumPy Array Reshaping

###  Reshaping arrays


Reshaping means changing the shape of an array.

We cannot add or remove the number of dimensions in the array through reshaping.


## Reshape From 1-D to 2-D

In [7566]:
## Convert the following 1-D array with 12 elements into a 2-D array

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype='int')

print(x)

x = x.reshape(4,3)

print(x)

print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [7567]:
x = x.reshape(3,4)

print(x)

print(x.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


## Reshape From 1-D to 3-D

In [7568]:
## Convert the following 1-D array with 12 elements into a 3-D array

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12],dtype=int)

print(x)

x = x.reshape(2,2,3)

print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
3


### Reshape (1,-1)  Row Vector

In [7569]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print('----------------------------Original Array--------------------------------------------------------------')

print(arr)

print(arr.ndim)

print(arr.shape)
### Convert it into row vector

print('----------------------------Reshaped Array--------------------------------------------------------------')
rows = arr.reshape(1,-1)

print(rows)

print(rows.ndim)

print(rows.shape)

----------------------------Original Array--------------------------------------------------------------
[1 2 3 4 5]
1
(5,)
----------------------------Reshaped Array--------------------------------------------------------------
[[1 2 3 4 5]]
2
(1, 5)


### OBSERVATIONS

1. It is used to convert the numpy array into row vector.

2. Here we have only one row and all the columns are inferred automatically.

3. Here we have only one horizontal row.

### Reshape (-1,1)  Column Vector

In [7570]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print('----------------------------Original Array--------------------------------------------------------------')

print(arr)

print(arr.ndim)

print(arr.shape)


print('----------------------------Reshaped Array--------------------------------------------------------------')

x = arr.reshape(-1,1)

print(x)

print(x.ndim)

print(x.shape)

----------------------------Original Array--------------------------------------------------------------
[1 2 3 4 5]
1
(5,)
----------------------------Reshaped Array--------------------------------------------------------------
[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)


### OBSERVATIONS:

1. It is used to convert the numpy array into column vector.

2. Here we have only one column and all the rows are inferred automatically.

3. It becomes a vertical vector.

In [7571]:
## Check if the returned array is a copy or a view

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8], dtype = int)
print("----------------Before Reshaping---------------------------------------")
print(x)

print("----------------After Reshaping---------------------------------------")
x = x.reshape(4,2)
print(x)

print("-----------------Replica Data-----------------------------------------")
x = x.base
print(x)

----------------Before Reshaping---------------------------------------
[1 2 3 4 5 6 7 8]
----------------After Reshaping---------------------------------------
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
-----------------Replica Data-----------------------------------------
[1 2 3 4 5 6 7 8]


In [7572]:
## Convert 1D array with 8 elements to 3D array with 2x2 elements

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8], dtype = 'int')

print("------------------Before Reshaping---------------------------------")
print(x)

print("------------------After Reshaping---------------------------------")
x = x.reshape(2,2,2)
print(x)
print(x.ndim)

------------------Before Reshaping---------------------------------
[1 2 3 4 5 6 7 8]
------------------After Reshaping---------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array

We can use reshape(-1) to do this.

In [7573]:
## Convert the array into a 1D array

import numpy as np 

print("-----------------------Before Reshaping------------------------------")
x = np.array([[1,2,3,4],[5,6,7,8]], dtype = 'int')

print(x)

print("-----------------------After Flattening------------------------------")

x = x.flatten()
print(x)

-----------------------Before Reshaping------------------------------
[[1 2 3 4]
 [5 6 7 8]]
-----------------------After Flattening------------------------------
[1 2 3 4 5 6 7 8]


## NumPy Array Iterating


Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one

In [7574]:
## Iterate on the elements of the following 1-D array

import numpy as np 

x = np.array([1,2,3,4,5], dtype = 'int')

# print(x)

for i in x:
    print(i)

1
2
3
4
5


In [7575]:
## Iterating 2-D Arrays

# In a 2-D array it will go through all the rows

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [7576]:
## Iterating 3-D Arrays

## In a 3-D array it will go through all the 2-D arrays

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7577]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


## Enumerated Iteration Using ndenumerate()

It will return the index position as well as the element from the array

In [7578]:
import numpy as np

x = np.array([1,2,3,4,5], dtype='i')

print(x)

for a,b in np.ndenumerate(x):
    print(a,b)

[1 2 3 4 5]
(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5


In [7579]:
## Enumerate on following 2D array's elements

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr)

for x,y in np.ndenumerate(arr):
    print(x,y)

[[1 2 3 4]
 [5 6 7 8]]
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [7580]:
import numpy as np

arr = np.array([1,2,3], dtype='i')

arr

array([1, 2, 3], dtype=int32)

In [7581]:
for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
    print(x)


np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [7582]:
import numpy as np 

x = np.array([1,2,3,4,5], dtype='i')

print(x)

for i in np.nditer(x):
    print(i)



[1 2 3 4 5]
1
2
3
4
5


In [7583]:
import numpy as np
arr = np.array(['a', 'b', 'c'])

print(arr)

for x in arr:
    print('Hello ' + x)

['a' 'b' 'c']
Hello a
Hello b
Hello c


## Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0

In [7584]:
## Join two arrays

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

print(arr1)

print(arr2)


print(arr1.ndim)

print(arr2.ndim)


x = np.concatenate((arr1,arr2), axis=0)

print(x)



[1 2 3]
[4 5 6]
1
1
[1 2 3 4 5 6]


In [7585]:
## Join two 2-D arrays along rows (axis=0)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)

x = np.concatenate((arr1,arr2),axis=0)

print(x)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
2
2
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7586]:
## Join two 2-D arrays along columns (axis=1)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

print(arr1)

print(arr2)

print(arr1.ndim)

print(arr2.ndim)


y = np.concatenate((arr1,arr2),axis=1)

print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
2
2
[[1 2 5 6]
 [3 4 7 8]]


In [7587]:
## Join two 2-D arrays along rows (axis=0)

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])


print(arr1)

print(arr2)


## Along the rows

x = np.concatenate((arr1,arr2), axis=0)

print(x)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7588]:
## Along the columns

y = np.concatenate((arr1, arr2), axis=1)

print(y)

[[1 2 5 6]
 [3 4 7 8]]


## stack ----->

It is a function used in numpy array that palces the numpy array one above the another in the form of stacks

It creates a new dimension.

In [7589]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# To join two arrays using stack

res = np.stack((arr1,arr2), axis=0)

print(res)

[[1 2 3]
 [4 5 6]]


### OBSERVATIONS:

1.  It joins the two numpy arrays one above the other in the form of rows.

In [7590]:
print(x.ndim)

2


In [7591]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

# To join two arrays using stack

arr1

array([1, 2, 3])

In [7592]:
arr2

array([4, 5, 6])

In [7593]:
res = np.stack((arr1,arr2), axis=1)

print(res)

[[1 4]
 [2 5]
 [3 6]]


### hstack

NumPy provides a helper function: hstack() to stack along rows


hstack----> It is a type of stacking technique that joins two arrays side by side

In [7594]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

x = np.hstack((arr1, arr2))

print(x)

[1 2 3 4 5 6]


## vstack

It is a type of stacking technique that joins two arrays one above the another.

In [7595]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

y = np.vstack((arr1, arr2))

print(y)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)

NumPy provides a helper function: dstack() to stack along height, which is the same as depth


It converts 1d into multi dimenional array.

It stacks them along the depth.

In [7596]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


print(arr1.ndim)

print(arr2.ndim)

1
1


In [7597]:
### stack along the depth

x = np.dstack((arr1, arr2))

print(x)

[[[1 4]
  [2 5]
  [3 6]]]


In [7598]:
print(x.ndim)

3


## Sorting Arrays


Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array

In [7599]:
import numpy as np

arr = np.array([3, 2, 0, 1])


print("--------------------------------Original Array-----------------------------------------------------------")
print(arr)


print("--------------------------------Sorted   Array-----------------------------------------------------------")
res = np.sort(arr)

print(res)

--------------------------------Original Array-----------------------------------------------------------
[3 2 0 1]
--------------------------------Sorted   Array-----------------------------------------------------------
[0 1 2 3]


In [7600]:
import numpy as np

arr1 = np.array(['banana','apple','cherry'])


print("--------------------------------Original Array-----------------------------------------------------------")
print(arr1)


print("--------------------------------Sorted Array-----------------------------------------------------------")

res = np.sort(arr1)

print(res)



--------------------------------Original Array-----------------------------------------------------------
['banana' 'apple' 'cherry']
--------------------------------Sorted Array-----------------------------------------------------------
['apple' 'banana' 'cherry']


In [7601]:
## Sort a boolean array

arr = [True, False,True]

print("--------------------------------Original Array-----------------------------------------------------------")

print(arr)

print("--------------------------------Sorted Array-----------------------------------------------------------")

res = np.sort(arr)

print(res)

--------------------------------Original Array-----------------------------------------------------------
[True, False, True]
--------------------------------Sorted Array-----------------------------------------------------------
[False  True  True]


## Sorting a 2-D Array

If you use the sort() method on a 2-D array, both arrays will be sorted

In [7602]:
import numpy as np 

x = np.array([[1,2,3,4],[5,6,7,8]])

print("--------------------------------Original Array-----------------------------------------------------------")

print(x)

print("--------------------------------Sorted Array-----------------------------------------------------------")

res = np.sort(x)

print(res)

--------------------------------Original Array-----------------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------------------Sorted Array-----------------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]


In [7603]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print("--------------------------------Original Array-----------------------------------------------------------")

print(arr)

print("--------------------------------Sorted Array-----------------------------------------------------------")

x = np.sort(arr)

print(x)

--------------------------------Original Array-----------------------------------------------------------
[[3 2 4]
 [5 0 1]]
--------------------------------Sorted Array-----------------------------------------------------------
[[2 3 4]
 [0 1 5]]


## Searching Arrays

You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method

In [7604]:
import numpy as np 

x = np.array([1,2,3,4,5,6,7,8])

print(x)

# To search for a particular element in the array

print(np.where(x==1))
print(np.where(x==3))
print(np.where(x==5))
print(np.where(x==7))
print(np.where(x==10))

[1 2 3 4 5 6 7 8]
(array([0]),)
(array([2]),)
(array([4]),)
(array([6]),)
(array([], dtype=int64),)


## OBSERVATION:

It returns the index of the particular element in the array.

In [7605]:
## Find the indexes where the values are even

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8])

print(x)

### Return all the index positions where the numbers are even
print(np.where((x%2)==0))

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [7606]:
## Find the indexes where the values are odd

import numpy as np 

x = np.array([1,2,3,4,5,6,7,8])

print(x)

### Return all the index positions where the numbers are odd

print(np.where((x%2)!= 0))

[1 2 3 4 5 6 7 8]
(array([0, 2, 4, 6]),)


## Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order

In [7607]:
## Find the indexes where the value 7 should be inserted

import numpy as np 

x = np.array([6,7,8,9])

print(x)

### Returns the index position where element 7 needs to be inserted

x=np.searchsorted(x,7)
print(x)

[6 7 8 9]
1


### OBSERVATIONS:

1.  Element '7' needs to be inserted at the index position 1.

In [7608]:
## Find the indexes where the value 7 should be inserted, starting from the right

import numpy as np 

x = np.array([6,7,8,9])

ans = np.searchsorted(x,7,side='right')

print(ans)

2


## Multiple Values

To search for more than one value, use an array with the specified values

In [7609]:
import numpy as np 

x = np.array([6,7,8,9])


ans = np.searchsorted(x,[1,3,5,7])

print(ans)

[0 0 0 1]


## Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits

In [7610]:
import numpy as np

x = np.array([1,2,3,4,5,6,7])

print('-----------------------------------Original Array------------------------------------------------------------------')
print(x)


print('-----------------------------------Splitted Array------------------------------------------------------------------')

### Split the array into three parts
ans = np.array_split(x,3)

print(ans)

-----------------------------------Original Array------------------------------------------------------------------
[1 2 3 4 5 6 7]
-----------------------------------Splitted Array------------------------------------------------------------------
[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [7611]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10])

print('-----------------------------------Original Array------------------------------------------------------------------')
print(x)

print('-----------------------------------Splitted Array------------------------------------------------------------------')

## Split the array into 5 equal parts

x = np.array_split(x,5)
print(x)

-----------------------------------Original Array------------------------------------------------------------------
[ 1  2  3  4  5  6  7  8  9 10]
-----------------------------------Splitted Array------------------------------------------------------------------
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [7612]:
## Split the array in 4 parts

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print('-----------------------------------Original Array------------------------------------------------------------------')
print(arr)

print('-----------------------------------Splitted Array------------------------------------------------------------------')
x = np.array_split(arr,4)
print(x)

-----------------------------------Original Array------------------------------------------------------------------
[1 2 3 4 5 6]
-----------------------------------Splitted Array------------------------------------------------------------------
[array([1, 2]), array([3, 4]), array([5]), array([6])]


## Split Into Arrays

The return value of the array_split() method is a list containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element

In [7613]:
## Access the splitted arrays

import numpy as np 

arr = np.array([1,2,3,4,5,6], dtype='int')

print(arr)


### split the array into 3 parts

res = np.array_split(arr,3)

print(res)

## Access the splitted array

print(res[0])
print(res[1])
print(res[2])

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


## Splitting 2-D Arrays

Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [7614]:
import numpy as np 

arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])

print('--------------------------------------------Original Array------------------------------------------------------')

print(arr)


## Split the 2-D array into three 2-D arrays

print('---------------------------------------------Splitted Array----------------------------------------------------')

x = np.array_split(arr,3)

print(x)


## Accessing all the 2D Arrays

print(x[0])
print(x[1])
print(x[2])

--------------------------------------------Original Array------------------------------------------------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
---------------------------------------------Splitted Array----------------------------------------------------
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [7615]:
## Split the 2-D array into three 2-D arrays along columns

import numpy as np 

arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

print('--------------------------------------------Original Array------------------------------------------------------')
print(arr)

print('--------------------------------------------Splitted Array------------------------------------------------------')

x = np.array_split(arr,3, axis=1)

print(x)

--------------------------------------------Original Array------------------------------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------------------------------Splitted Array------------------------------------------------------
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [7616]:
## Use the hsplit() method to split the 2-D array into three 2-D arrays along columns

import numpy as np

arr = np.array([[1,2,3,4],[5,6,7,8]])

print('--------------------------------------------Original Array------------------------------------------------------')
print(arr)

print('--------------------------------------------Splitted Array------------------------------------------------------')

x = np.hsplit(arr,2)

print(x)

--------------------------------------------Original Array------------------------------------------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------------------------------Splitted Array------------------------------------------------------
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


### OBSERVATIONS:

1.  It splits the array into two horizontal parts.