#### To implement the Simple Linear Regression using Ordinary Least Square method


##### Step 1: Import  all the  necessary libararies

In [363]:
import  numpy               as  np
import  pandas              as  pd
import  matplotlib.pyplot   as  plt
import  seaborn             as  sns
import  statsmodels.api     as  sm

from    sklearn.model_selection     import   train_test_split
from    sklearn.preprocessing       import   StandardScaler
from    sklearn.linear_model        import   LinearRegression
from    sklearn.metrics             import   mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score


#### Step 2: Load the dataset

In [364]:
df = pd.read_csv("height-weight.csv")

In [365]:
df.head()

,Weight,Height
0,45,120
1,58,135
2,48,123
3,60,145
4,70,160


#### OBSERVATIONS:

1.  The above dataset contains the height vs weight for different persons in the dataset.

#### Step 3: Perform the Data Exploration

In [366]:
#### get the top five rows of the dataset

df.head()

,Weight,Height
0,45,120
1,58,135
2,48,123
3,60,145
4,70,160


In [367]:
#### get the bottom five rows of the dataset

df.tail()

,Weight,Height
18,76,150
19,87,167
20,45,129
21,56,140
22,72,160


In [368]:
#### get the length of the dataset

print("Length of the dataset is:", len(df))

Length of the dataset is: 23


In [369]:
#### Shape of the dataset

print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (23, 2)


In [370]:
#### get the columns used in the dataset

df.columns

Index(['Weight', 'Height'], dtype='object')

In [371]:
#### get the information about the columns used in the dataset

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  23 non-null     int64
 1   Height  23 non-null     int64
dtypes: int64(2)
memory usage: 496.0 bytes


#### Step 4: Perform Data Cleaning

In [372]:
#### To check for the NULL records in the dataset

df.isnull().sum()

Weight    0
Height    0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL records in the dataset.

In [373]:
#### To check for the duplicate records used in the dataset

df[df.duplicated()]

,Weight,Height
11,95,182


#### OBSERVATIONS:

1.  There is one duplicate record in the dataset.

In [374]:
df = df.drop_duplicates()

In [375]:
#### To again check for the duplicate records used in the dataset

df[df.duplicated()]

,Weight,Height


#### OBSERVATIONS:

1.  There is no duplicate record in the dataset.

#### Step 5: Divide the dataset into independent and dependent features

In [376]:
#### independent features

X = df.drop(columns='Height',axis=1)

print(X)

    Weight
0       45
1       58
2       48
3       60
4       70
5       78
6       80
7       90
8       95
9       78
10      82
12     105
13     100
14      85
15      78
16      50
17      65
18      76
19      87
20      45
21      56
22      72


In [377]:
#### dependent features

Y = df[['Height']]

print(Y)

    Height
0      120
1      135
2      123
3      145
4      160
5      162
6      163
7      175
8      182
9      170
10     176
12     175
13     183
14     170
15     177
16     140
17     159
18     150
19     167
20     129
21     140
22     160


#### Step 6: Divide the independent and dependent features into training and testing data

In [378]:
from  sklearn.model_selection  import  train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [379]:
X_train

,Weight
5,78
21,56
12,105
3,60
4,70
18,76
13,100
19,87
17,65
2,48


In [380]:
X_test

,Weight
0,45
14,85
8,95
1,58
16,50


In [381]:
print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (17, 1)
Shape of the input testing  data is: (5, 1)


In [382]:
Y_train

,Height
5,162
21,140
12,175
3,145
4,160
18,150
13,183
19,167
17,159
2,123


In [383]:
Y_test

,Height
0,120
14,170
8,182
1,135
16,140


In [384]:
print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (17, 1)
Shape of the output testing  data is: (5, 1)


#### Step 7: Perform Feature Scaling on the inputs

In [385]:
from  sklearn.preprocessing import  StandardScaler

#### create an object for Standard Scaler

sc = StandardScaler()

#### using the object for Standard Scaler, transform the inputs

X_train_scaled = sc.fit_transform(X_train)

X_test_scaled  = sc.transform(X_test)

In [386]:
X_train_scaled

array([[ 0.20608301],
       [-1.17025708],
       [ 1.89522766],
       [-0.92001342],
       [-0.2944043 ],
       [ 0.08096118],
       [ 1.58242309],
       [ 0.76913122],
       [-0.60720886],
       [-1.67074438],
       [ 0.20608301],
       [-0.16928247],
       [ 0.95681396],
       [ 0.45632666],
       [ 0.20608301],
       [-1.85842712],
       [ 0.33120483]])

In [387]:
X_test_scaled

array([[-1.85842712],
       [ 0.6440094 ],
       [ 1.26961853],
       [-1.04513525],
       [-1.54562255]])

#### OBSERVATIONS:

1.  All the input features are in the same scale range

#### Step 8: Perform Linear Regression using Ordinary Least Squares Method

In [388]:
import  statsmodels.api  as  sm

#### create an object for OLS and train the model

model = sm.OLS(X_train_scaled, Y_train).fit()


print(model)

In [389]:
#### predict the model

Y_pred = model.predict(X_test_scaled)

In [390]:
Y_pred

array([-0.00108302,  0.00037531,  0.00073989, -0.00060907, -0.00090073])

In [391]:
#### summary of the model

print(model.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.009
Model:                            OLS   Adj. R-squared (uncentered):             -0.053
Method:                 Least Squares   F-statistic:                             0.1412
Date:                Fri, 08 May 2026   Prob (F-statistic):                       0.712
Time:                        12:47:49   Log-Likelihood:                         -24.047
No. Observations:                  17   AIC:                                      50.09
Df Residuals:                      16   BIC:                                      50.93
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

c:\Users\DELL\Desktop\Complete_Data_Science\vens\lib\site-packages\scipy\stats\_axis_nan_policy.py:418: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=17 observations were given.
  return hypotest_fun_in(*args, **kwds)
