#### **Simple Neural Networks:**

1.  The main aim of this project is to build a simple neural networks and predict whether the student has passed or failed based on the number of hours the student has studied.


#### **Algorithm of Simple Neural Networks:**

1.  Import all the necessary libraries

2.  Create the sample dataset

3.  Normalize the Input Data

4.  Create the ANN Model

5.  Compile the ANN Model

6.  Train  the ANN Model

7.  Predict the ANN Model

8.  Combine the Actual Value and the Predicted Value

9.  Take the test data and predict whether the student has passed or failed.

#### **Step 1: Import all the necessary libraries**

In [358]:
import  numpy             as  np
import  pandas            as  pd
import  matplotlib.pyplot as  plt
import  seaborn           as  sns


from    tensorflow.keras.models import Sequential
from    tensorflow.keras.layers import Dense

#### **OBSERVATIONS:**

1.    Sequential --------->  It helps in creating the Sequential model.

2.    Dense      ---------->  It creates the dense layer one after the another.

#### **Step 2: Create the sample dataset**

In [359]:
X = np.array([[2], [4], [6], [8], [10]])   # Study hours
Y = np.array([[0], [0], [1], [1], [1]])    # Pass(1) / Fail(0)

In [360]:
#### Independent variables
print(X)

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]


#### **OBSERVATIONS:**

1.  The independent variable represents the Study Hours.

In [361]:
#### dependent variables
print(Y)

[[0]
 [0]
 [1]
 [1]
 [1]]


#### **OBSERVATIONS:**

1.  The dependent variables represents the students who passed or failed.

#### **Step 3: Normalize the Input**

In [362]:
#### Normalize the inputs
X = X / 10.0

In [363]:
X

array([[0.2],
       [0.4],
       [0.6],
       [0.8],
       [1. ]])

#### **Step 4: Create the ANN Model**

In [364]:
#### Create the ANN Model
ann = Sequential([
    #### create the first dense layer
    Dense(4,activation='relu',input_shape=(1,)) ,
    #### create the output layer
    Dense(1,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


#### **OBSERVATIONS:**

1.  A Sequential model of ANN is made with

      (a.)  the first dense layer --------->
      
        (i.)  This layer has 4 dense neurons in it.

        (ii.) Relu activation functions has been applied on it to increase the non-linearity of the image.

        (iii.) The shape of the input vector is 1 means 1 feature in each row.


      (b.)  the second dense layer ----------->

        (i.)  This layer has 1 neuron in it.

        (ii.)  As the dataset is a binary classification problem which determines whether the student will pass / fail, so sigmoid activation function has been applied on it.

#### **Step 5: Compile the ANN Model**

In [365]:
#### Compile the ANN Model
ann.compile(
    optimizer = 'adam'                    ,
    loss      = 'binary_crossentropy'     ,
    metrics   =  ['accuracy']
)

#### **OBSERVATIONS:**

1.  The model has been made ready for training with the help of the following parameters:--

    (a.)  optimizer = 'adam' ------>  Adam is an optimizer that updates the weights during backpropagation.

    (b.)  loss = 'binary_crossentropy' --------> It is a loss function used in the binary classification problem.

    (c.)  metrics = ['accuracy'] --------------> It is used to evaluate the performance of the ANN model.

#### **Step 6: Train  the ANN Model**

In [ ]:
#### Train the ANN Model
ann.fit(X,Y,epochs=100,verbose=0)

#### **OBSERVATIONS:**

1.  The ann model has been trained with the following parameters:-----

    (a.)  X -------------->  independent variables

    (b.)  Y -------------->  dependent   variables

    (c.)  epochs = 100 ---->  Total number of iterations needed to train the model is 100

    (d.)  verbose = 0 ------>  Amount of information printed during the model training.

#### **Step 7: Predict the ANN Model**

In [ ]:
#### predict the model
Y_pred = ann.predict(X)

In [ ]:
Y_pred

#### **Step 8: Combine the Actual Value and the Predicted Value**

In [ ]:
### Combine the Actual Value and the Predicted Value
Y.shape

In [ ]:
Y_pred.shape

In [ ]:
Y

In [ ]:
Y_pred

In [ ]:
Y.flatten()

In [ ]:
Y_pred.flatten()

In [ ]:
#### Construct the dataframe
df = pd.DataFrame({
    'Actual Value '   :   Y.flatten()                                  ,
    'Predicted Value' :   Y_pred.flatten()                             ,
    'Predicted Class' :  (Y_pred.flatten() > 0.5).astype(int)
})

In [ ]:
df

#### **Step 9: Take the test data and predict whether the student has passed or failed**

In [ ]:
#### construct a new test data

X = [[5]]

#### Normalize the inputs


test_data = np.array(X)/10.0
print(test_data)

#### perform the prediction on the model
Y_pred_data = ann.predict(test_data)
print(Y_pred_data)

### check if the student has passed or failed
if(Y_pred_data > 0.5):
  print("Student has passed")
else:
  print("Student has failed")