### NumPy (Numerical Python) 

It is a Python library used for high-performance numerical computing.

### Main advantages of Numpy:

1.  Fast computations

2.  Multidimensional arrays

3.  Mathematical functions

4.  Linear algebra support

5.  Used heavily in ML libraries like

    a.  Pandas

    b.  Scikit-learn

    c.  TensorFlow

    d.  PyTorch

### Core NumPy Concepts

#### 1. NumPy Arrays

A NumPy array is a homogeneous multidimensional array.

In [1439]:
import numpy  as  np

### Creating Arrays

####  1D Array

In [1440]:
x = np.array([10, 20, 30, 40, 50])

print(x)

print("No of dimensions used in the array is:", x.ndim)

print("Type of the array is:", x.dtype)

[10 20 30 40 50]
No of dimensions used in the array is: 1
Type of the array is: int64


#### 2D Array

In [1441]:
x = np.array([
    [1,2,3],
    [4,5,6]
])

print(x)

print("No of dimensions used in the array is:", x.ndim)

print("Type of the array is:", x.dtype)

[[1 2 3]
 [4 5 6]]
No of dimensions used in the array is: 2
Type of the array is: int64


In [1442]:
### Array Attribute

print("==================Original array ========================================================")
print(x)

print("==================No of dimensions used in the array=====================================")
print(x.ndim)

print("========================Data Type of every element in the array===========================")
print(x.dtype)

print("====================Shape of the array====================================================")
print(x.shape)

print("======================Size of the array====================================================")
print(x.size)

==================Original array ========================================================
[[1 2 3]
 [4 5 6]]
==================No of dimensions used in the array=====================================
2
========================Data Type of every element in the array===========================
int64
====================Shape of the array====================================================
(2, 3)
======================Size of the array====================================================
6


### 3. Special Arrays

##### Zeros -------------> It fills the array with zeros with sepcific sets of rows and columns.

In [1443]:
a = np.zeros((3,3), dtype='int32')

print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### OBSERVATIONS:

1. Here we are creating the numpy array and filling zeros in the array with 3 rows and 3 columns. Each element in the numpy array is of int type.

##### Ones -------------> It fills the array with ones with sepcific sets of rows and columns.

In [1444]:
a = np.ones((3,3), dtype='int32')

print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### OBSERVATIONS:

1. The numpy array is created of the size 3 * 3. Each element is filled with 1. It is of integer type.

### Identity Matrix -----> Ones at the diagonal position and the rest is zero.

In [1445]:
a = np.eye(3, dtype='int32')

print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### OBSERVATIONS:

1.  Here a identity matrix is created with 1 at the diagonal position and the rest position is filled with zeros.

###  4. Range Functions

arange()    -------------> It creates a numpy array.

In [1446]:
a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


### OBSERVATIONS:

1. Here a numpy array is created with elements from 0 to 9.

linspace() ---------------> It creates a numpy array with the range of elements in it.

In [1447]:
a = np.linspace(0,1)

print(a)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


### OBSERVATIONS:

1. With the help of linspace, a range of numbers is created between 0 to 1.

### 5. Indexing and Slicing

#### Indexing

In [1448]:
arr = np.array([10,20,30,40])

print("============First element in the array =====================")
print(arr[0])

============First element in the array =====================
10


### Slicing

In [1449]:
print("==============Extract the second and third elements from the array ==========================")

print(arr[1:3])

==============Extract the second and third elements from the array ==========================
[20 30]


### 2D Slicing

In [1450]:
arr2 = np.array([
[1,2,3],
[4,5,6]
])

print("==============Extract the element 2 from the numpy array =======================================")
print(arr2[0][1])

==============Extract the element 2 from the numpy array =======================================
2


### 6. Mathematical Operations

In [1451]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a+b)

print(a*b)

[5 7 9]
[ 4 10 18]


### 7. Aggregation Functions

In [1452]:
arr = np.array([10,20,30,40])

print("Sum of all the elements in the array is:"    ,  np.sum(arr))
print("Mean of all the elements in the array is:"   ,  np.mean(arr))
print("Maximum of all the elements in the array is:",  np.max(arr))
print("Minimum of all the elements in the array is:",  np.min(arr))

Sum of all the elements in the array is: 100
Mean of all the elements in the array is: 25.0
Maximum of all the elements in the array is: 40
Minimum of all the elements in the array is: 10


### 8. Reshaping

In [1453]:
a = np.arange(1,10)

print("=========================Original array ===============================================")

print(a)

### Convert the numpy array into 3 * 3

print("=========================Reshaped array ===============================================")

a1 = a.reshape(3,3)

print(a1)

=========================Original array ===============================================
[1 2 3 4 5 6 7 8 9]
=========================Reshaped array ===============================================
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 9. Broadcasting

Here the numpy array automatically matches the dimensions.

In [1454]:
a = np.arange(1,10)

print("=========================Original array ===============================================")

print(a)

print("==========================Broadcasted array ===========================================")

a = a + 10

print(a)

=========================Original array ===============================================
[1 2 3 4 5 6 7 8 9]
==========================Broadcasted array ===========================================
[11 12 13 14 15 16 17 18 19]


### OBSERVATIONS:

1. 10 is automatically matched with all the dimensions of the array and added to every element of the array.

### NumPy Coding Practice

Important coding problems.

In [1455]:
### Create a 5x5 matrix.

a = np.arange(1,26)

print("=========================Original array ===============================================")
print(a)

print("=========================Reshaped array ===============================================")

a = a.reshape(5,5)

print(a)

=========================Original array ===============================================
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
=========================Reshaped array ===============================================
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [1456]:
### Problem 2

#### Find row mean.

print("=========================Original array ===============================================")
print(a)

print("=========================Reshaped array ===============================================")
x = a.reshape(5,5)
print(x)

### Find the row mean

print("===========================Row mean ===================================================")

ans = np.mean(x, axis=1)

print(ans)

=========================Original array ===============================================
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
=========================Reshaped array ===============================================
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
===========================Row mean ===================================================
[ 3.  8. 13. 18. 23.]


In [1457]:
### Problem 3

#### Find column sum.

print("=========================Original array ===============================================")
print(a)

print("=========================Reshaped array ===============================================")
x = a.reshape(5,5)
print(x)

print("=========================Column sum ====================================================")
ans = np.sum(x,axis=0)
print(ans)

=========================Original array ===============================================
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
=========================Reshaped array ===============================================
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
=========================Column sum ====================================================
[55 60 65 70 75]


### OBSERVATIONS:

1. When axis = 1, then the operation is performed along the rows.

### Real World Project

Student Performance Analysis

### Goal

1. Perform all the numpy calculations and based on it get the performance of the student.


### Steps used in this Algorithm :---


1.  Import Libraries

2.  Create Dataset

3.  Calculate Average Score along the rows

4.  Find Top Student

5.  Calculate Subject Average along the columns

6.  Standard Deviation

7.  Rank Students

### Step 1: Import Libraries

In [1458]:
import numpy as np

### Step 2:  Create Dataset

In [1459]:
scores = np.array([
[85,78,92],
[70,65,60],
[90,88,95],
[60,55,58],
[75,80,72]
])

In [1460]:
scores

array([[85, 78, 92],
       [70, 65, 60],
       [90, 88, 95],
       [60, 55, 58],
       [75, 80, 72]])

### Step 3: Calculate Average Score along the rows

In [1461]:
average = np.mean(scores,axis=1)

In [1462]:
average

array([85.        , 65.        , 91.        , 57.66666667, 75.66666667])

### Step 4: Find Top Student

In [1463]:
### We need to get the student that has the maximum average score

### Find out the average scores of all the students along the rows

x = np.mean(scores,axis=1)
print(x)

### Find out the index having the maximum average score

ans = np.argmax(x)
print(ans)

[85.         65.         91.         57.66666667 75.66666667]
2


### OBSERVATIONS:

1. Index 2 (91) is the index having the maximum average score.

### Step 5: Calculate Subject Average along the columns

In [1464]:
avg_scores_cols = np.mean(scores,axis=0)

print(avg_scores_cols)

[76.  73.2 75.4]


### Step 6: Standard Deviation

In [1465]:
std = np.std(scores)

print("Standard deviation of the scores is:", std)

Standard deviation of the scores is: 12.883408796674203


### Step 7: Rank Students

In [1466]:
### We need to rank the performance of the students according to the average score in each row

avg_scores_mean = np.mean(scores,axis=1)

print(avg_scores_mean)

### provide the rank by assigning the indices to every element in the array in ascending order

averagerank = np.argsort(avg_scores_mean)

print(averagerank)

[85.         65.         91.         57.66666667 75.66666667]
[3 1 4 0 2]


In [1467]:
### provide the rank by assigning the indices to every element in the array in descending order

averagerankdesc = np.argsort(avg_scores_mean)[::-1]

print(averagerankdesc)

[2 0 4 1 3]


#### Interview Questions:----

### 1.  Create Identity Matrix

An Identity matrix is a matrix that has 1 in the diagonal and 0 on all its sides except diagonal.

In [1468]:
import numpy as np

x = np.eye(3, dtype='int32')

print(x)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 2. Find Array Mean

Mean = average value of array.

In [1469]:
import numpy as np 

x = np.array([10,20,30,40,50])

print(np.mean(x))

30.0


### 3. Find Duplicate Values

In [1470]:
import numpy as np

arr = np.array([1,2,3,2,4,5,1])

unique, counts = np.unique(arr, return_counts=True)

print(unique,counts)

### Get all the duplicate elements from the array
duplicates = unique[counts > 1]

print(duplicates)

[1 2 3 4 5] [2 2 1 1 1]
[1 2]


### 4. Matrix Multiplication

In [1471]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


### perform the dot multiplication between two vectors

res = np.dot(A,B)

print(res)

[[19 22]
 [43 50]]


### 5. Reshape Matrix

Change the shape of an array.

In [1472]:
import numpy as np

arr = np.arange(1,13)

print("======================Original array is:================================")
print(arr)

print("======================Reshaped array is:===================================")

arr = arr.reshape(4,3)

print(arr)

======================Original array is:================================
[ 1  2  3  4  5  6  7  8  9 10 11 12]
======================Reshaped array is:===================================
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 6. Broadcast Scalar

Add scalar value to all elements.

In [1473]:
import numpy as np

arr = np.array([1,2,3,4])

### Add the scalar value 10 to the numpy array

res = arr + 10

print(res)

[11 12 13 14]


### 7. Normalize Dataset (Min-Max Scaling)

In [1474]:
import numpy as np

data = np.array([10,20,30,40,50])

normalized_data = (data - np.min(data))/(np.max(data) - np.min(data))

print(normalized_data)

[0.   0.25 0.5  0.75 1.  ]


### 8. Standardize Data (Z-score)

In [1475]:
import numpy as np

data = np.array([10,20,30,40,50])


standarddata = (data - np.mean(data))/(np.std(data))

print(standarddata)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### 9. Find Missing Values

In [1476]:
import numpy as np

data = np.array([1,2,np.nan,4,np.nan])

print(data)


### Check for the missing values

print(np.isnan(data))

[ 1.  2. nan  4. nan]
[False False  True False  True]


### 10. Dot Product

In [1477]:
import numpy as np

A = np.array([1,2,3])
B = np.array([4,5,6])


res = np.dot(A,B)

print(res)

32
