#### Predict the House Price based on the following factors :---

.   Area

.   Bedrooms

.   Bathrooms

.   Location factors


using Multiple Linear Regression

##### Step 1:-- Import all the necessary libraries

In [689]:
import numpy             as  np
import pandas            as  pd
import matplotlib.pyplot as plt
import seaborn           as sns


from   sklearn.model_selection import train_test_split
from   sklearn.preprocessing   import StandardScaler
from   sklearn.linear_model    import LinearRegression
from   sklearn.metrics         import r2_score, mean_absolute_error, mean_squared_error, root_mean_squared_error

#### Step 2:-- Load the Dataset

In [690]:
df = pd.read_csv('Housing.csv')

In [691]:
df

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished


#### OBSERVATIONS:

1.  The dataset contains the following features as input:----

    (a.)  Input ------->  area, bedrooms, stories, mainroad, guestroom,-----, furnishingstatus

    (b.)  Output ------>  House Price

#### Step 3:-- Perform the Data Exploration

In [692]:
print("Total length of the dataset is:", len(df))

Total length of the dataset is: 545


In [693]:
print("Shape of the dataset is:", df.shape)

Shape of the dataset is: (545, 13)


In [694]:
print(df.columns)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')


In [695]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB
None


In [696]:
print(df.describe())

              price          area    bedrooms   bathrooms     stories  \
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000   
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505   
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492   
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000   
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000   
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000   
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000   
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000   

          parking  
count  545.000000  
mean     0.693578  
std      0.861586  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      3.000000  


#### Step 4:-- Perform the Data Cleaning

In [697]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

#### OBSERVATIONS:

1.  There are no NULL Values in the dataset.

In [698]:
df[df.duplicated()]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus


#### OBSERVATIONS:

1.  There are no duplicated records in the dataset.

#### Step 5:-- Divide the dataset into independent and dependent variables

In [699]:
#### Independent variables

X = df[['area', 'bedrooms', 'bathrooms', 'stories']]

#### Dependent variables

Y = df['price']

In [700]:
print(X)

     area  bedrooms  bathrooms  stories
0    7420         4          2        3
1    8960         4          4        4
2    9960         3          2        2
3    7500         4          2        2
4    7420         4          1        2
..    ...       ...        ...      ...
540  3000         2          1        1
541  2400         3          1        1
542  3620         2          1        1
543  2910         3          1        1
544  3850         3          1        2

[545 rows x 4 columns]


In [701]:
print(Y)

0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64


#### Step 6:-- Divide the independent and dependent variables into the training and testing data

In [702]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [703]:
X_train

,area,bedrooms,bathrooms,stories
46,6000,3,2,4
93,7200,3,2,1
335,3816,2,1,1
412,2610,3,1,2
471,3750,3,1,2
...,...,...,...,...
71,6000,4,2,4
106,5450,4,2,1
270,4500,3,2,3
435,4040,2,1,1


In [704]:
X_test

,area,bedrooms,bathrooms,stories
316,5900,4,2,2
77,6500,3,2,3
360,4040,2,1,1
90,5000,3,1,2
493,3960,3,1,1
...,...,...,...,...
15,6000,4,1,2
357,6930,4,1,2
39,6000,4,2,4
54,6000,3,2,2


In [705]:
print("Shape of the input training data is:", X_train.shape)

print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (436, 4)
Shape of the input testing  data is: (109, 4)


In [706]:
Y_train

46     7525000
93     6300000
335    3920000
412    3430000
471    3010000
        ...   
71     6755000
106    6160000
270    4340000
435    3290000
102    6195000
Name: price, Length: 436, dtype: int64

In [707]:
Y_test

316    4060000
77     6650000
360    3710000
90     6440000
493    2800000
        ...   
15     9100000
357    3773000
39     7910000
54     7350000
155    5530000
Name: price, Length: 109, dtype: int64

In [708]:
print("Shape of the output training data is:", Y_train.shape)

print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (436,)
Shape of the output testing  data is: (109,)


#### Step 7:-- Perform the Feature Scaling

In [709]:
from sklearn.preprocessing import StandardScaler

#### create an object for Standard Scaler

sc = StandardScaler()

#### Using the object for Standard Scaler, transform the inputs

X_train_scaled = sc.fit_transform(X_train)

X_test_scaled = sc.transform(X_test)

In [710]:
X_train_scaled

array([[ 0.38416819,  0.05527092,  1.53917323,  2.58764353],
       [ 0.9291807 ,  0.05527092,  1.53917323, -0.91249891],
       [-0.60775457, -1.28351359, -0.5579503 , -0.91249891],
       ...,
       [-0.29709744,  0.05527092,  1.53917323,  1.42092939],
       [-0.5060189 , -1.28351359, -0.5579503 , -0.91249891],
       [ 0.15707965,  0.05527092,  1.53917323,  2.58764353]],
      shape=(436, 4))

In [711]:
X_test_scaled

array([[ 0.33875048,  1.39405543,  1.53917323,  0.25421524],
       [ 0.61125674,  0.05527092,  1.53917323,  1.42092939],
       [-0.5060189 , -1.28351359, -0.5579503 , -0.91249891],
       [-0.0700089 ,  0.05527092, -0.5579503 ,  0.25421524],
       [-0.54235307,  0.05527092, -0.5579503 , -0.91249891],
       [ 0.7111757 ,  0.05527092, -0.5579503 , -0.91249891],
       [ 1.52869446,  0.05527092, -0.5579503 , -0.91249891],
       [-0.07455067,  1.39405543,  1.53917323,  0.25421524],
       [-0.86936058, -1.28351359, -0.5579503 , -0.91249891],
       [-1.11461621,  0.05527092, -0.5579503 , -0.91249891],
       [ 1.55594508,  1.39405543,  3.63629675,  2.58764353],
       [-0.55416168, -1.28351359, -0.5579503 , -0.91249891],
       [-0.65135557, -1.28351359, -0.5579503 , -0.91249891],
       [-0.93294537,  0.05527092, -0.5579503 ,  0.25421524],
       [-0.5378113 ,  0.05527092, -0.5579503 ,  0.25421524],
       [-0.69223151,  0.05527092,  3.63629675,  0.25421524],
       [-1.43254017, -1.

#### OBSERVATIONS:

1.  After performing the feature scaling on the inputs , all the inputs has been scaled in the same range of 0 to 1.

#### Step 8:--- Train the Linear model

In [712]:
from sklearn.linear_model import LinearRegression


#### create an object for Linear Regression

lin = LinearRegression()


#### using the object for linear regression, train the model


lin.fit(X_train_scaled, Y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


#### OBSERVATIONS:

1.  The linear regression model has been trained with the help of the training data.

#### Step 9 :-- Predict the model

In [713]:
Y_pred = lin.predict(X_test_scaled)

In [714]:
Y_pred

array([6177576.81007289, 6696157.1747214 , 3437037.80871784,
       4430631.95405246, 3583802.16724906, 4547069.04340544,
       5175286.57133352, 5859977.94873147, 3157830.01852758,
       3144049.89769941, 9338793.18082852, 3400042.77651763,
       3325354.69264173, 3767513.4523506 , 4071151.92418251,
       6468790.52236393, 3208917.60328875, 4779641.69179028,
       4727290.23112961, 4121096.89468396, 5405331.46791935,
       4583715.06586791, 3300575.00126235, 4011820.26876708,
       5081053.94214431, 7419871.20773819, 3105478.55786691,
       4990763.43308296, 7292511.80350258, 3557927.34102657,
       5339773.17082078, 3774493.64710536, 6521652.30585249,
       4994282.68049904, 4526789.9006117 , 5549179.01346347,
       4307082.50689327, 3970119.36891988, 3416277.49313491,
       5091109.49649506, 4986821.3129551 , 3293943.81624533,
       6668236.39570237, 4151424.16386221, 4382854.19798733,
       4080960.77484411, 7005511.96540856, 4479673.5860171 ,
       4836566.85704649,

#### OBSERVATIONS:

1.  Based on the input test data, we have obtained the predicted value of the House Price.

#### Step 10:-- Compare the Actual vs Predicted prices and store the residual in the dataframe

In [715]:
res = pd.DataFrame({
    'Actual Results'     :    Y_test          ,
    'Predicted Results'  :    Y_pred          ,
    'Residual'           :    (Y_test - Y_pred) 
})

In [716]:
res

,Actual Results,Predicted Results,Residual
316,4060000,6.177577e+06,-2.117577e+06
77,6650000,6.696157e+06,-4.615717e+04
360,3710000,3.437038e+06,2.729622e+05
90,6440000,4.430632e+06,2.009368e+06
493,2800000,3.583802e+06,-7.838022e+05
...,...,...,...
15,9100000,4.954327e+06,4.145673e+06
357,3773000,5.278906e+06,-1.505906e+06
39,7910000,7.180197e+06,7.298029e+05
54,7350000,6.037793e+06,1.312207e+06


#### Step 11:-- Perform the Regression Metrics

In [717]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error

mae = mean_absolute_error(Y_test, Y_pred)

print("Mean Absolute error of the model is:", mae)

Mean Absolute error of the model is: 1158970.480316688


In [718]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error

mse = mean_squared_error(Y_test, Y_pred)

print("Mean squared error of the model is:", mse)

Mean squared error of the model is: 2457741642022.0894


In [719]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error

rmse = root_mean_squared_error(Y_test, Y_pred)

print("Root Mean squared error of the model is:", rmse)

Root Mean squared error of the model is: 1567718.6106001579


In [720]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, root_mean_squared_error

r2 = r2_score(Y_test, Y_pred)

print("R2 Score of the model is:", r2)

R2 Score of the model is: 0.5137585349037066


#### OBSERVATIONS:

1.  As the R2 score of the model is 0.51, so the model is ok.

#### Step 12:-- Dump the model

In [721]:
import joblib

joblib.dump(lin, "model.pkl")

['model.pkl']