### Convolutional Neural Networks based on Cat Dog Classification:-

### **Aim:-**

1.  The main aim of this project is to predict whether the given image is of Cat or Dog using CNN Model.


### **Steps used in this Algorithm:-**

1.  Import all the necessary libraries

2.  Load the dataset

3.  Check the shape of the data

4.  Perform the Data preprocessing

5.  Check the entire training and testing data

6.  Check and Visualize the sample image

7.  Build the entire CNN Model

8.  Compile the CNN Model

9.  Get the summary of the model

10.  Train the CNN Model

11.  Evaluate the CNN Model

12.  Making predictions

13.  Visualize predictions

### Step 1:  Import all the necessary libraries

In [79]:
import numpy  as  np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn    as   sns

import tensorflow as tf

from   tensorflow.keras.models   import Sequential
from   tensorflow.keras.layers   import Dense, Dropout, BatchNormalization, Conv2D, MaxPooling2D
from   tensorflow.keras.utils    import to_categorical


### **OBSERVATIONS:**

1.   numpy ---------------> computation of numerical array

2.   pandas --------------> Data Creation and manipulation

3.   matplotlib ----------> Data Visualization

4.   seaborn ------------> Data correlation

5.   tensorflow ----------> Deep Learning Framework

6.   cifar10 ------------> It is an image dataset

7.   Sequential ----------> Linear stacks of layers

8.   Conv2D --------------> Convolutional layer and forms feature maps

9.   MaxPooling2D --------> Reduces the size of the image

10.  Dense -------------> Fully Connected dense layer

11.  Flatten -------------> Converts the 2D feature maps into 1D vector

12.  Dropout -------------> Reduces overfitting

13.  BatchNormaliation -------> helps in normalizing the activations

14.  to_categorical ---------> forms one hot encoding of the labels

### Step 2:  Load the dataset

In [80]:
### Input data

X_train = pd.read_csv('/content/input.csv')
X_test  = pd.read_csv('/content/input_test.csv')

In [81]:
### Output data

Y_train = pd.read_csv('/content/labels.csv')
Y_test  = pd.read_csv('/content/labels_test.csv')

### Step 3: Check the shape of the data

In [82]:
### Input data

print("Shape of the input training data is:", X_train.shape)
print("Shape of the input testing  data is:", X_test.shape)

Shape of the input training data is: (1999, 30000)
Shape of the input testing  data is: (399, 30000)


In [83]:
### Output data

print("Shape of the output training data is:", Y_train.shape)
print("Shape of the output testing  data is:", Y_test.shape)

Shape of the output training data is: (1999, 1)
Shape of the output testing  data is: (399, 1)


### **OBSERVATIONS:**

1. The input and the output training and testing data is in the form of (no of input images, total features processed per image).

2. But this shape is not acceptable for the CNN Model to get it processed. As CNN accepts the input in the form of (batch_size, height,width,number of channels).

### Step 4: Perform the Data preprocessing

In [84]:
X_train = X_train.values  ### Convert the datarame into numpy array as CNN can work with numpy array
X_test  = X_test.values

In [85]:
X_train = X_train.reshape(len(X_train),100,100,3)

X_test  = X_test.reshape(len(X_test), 100,100,3)

In [86]:
Y_train = Y_train.values  ### Convert the datarame into numpy array as CNN can work with numpy array
Y_test  = Y_test.values

In [87]:
Y_train


array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [88]:
Y_test

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [89]:
### Reshape it into proper form

Y_train = Y_train.reshape(len(Y_train),1)

Y_test = Y_test.reshape(len(Y_test),1)

In [90]:
Y_train

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [91]:
Y_test

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    