### Count Vectorizer vs Tfidf Vectorizer

1.  Both the Count Vectorizer and Tfidf Vectorizer are the text representation techniques that is used to convert the text into the numerical array vectors taht can be Numerical Array vectors that can be easily be trained by the Machine Learning Model.


### Definition :-

1.  Count Vectorizer ------->  converts the text into the matrix of word counts.

2.  Tfidf Vectorizer ------->  converts the text into the Tfidf scores.

### Steps used in this Algorithm:---

1.   Import all the necessary Libraries

2.   Create Sample Corpus

3.   Apply CountVectorizer (Bag of Words)

4.   Apply TfidfVectorizer

### Step 1: Import all the necessary Libraries

In [62]:
import  numpy             as  np
import  pandas            as  pd
import  matplotlib.pyplot as plt
import  seaborn           as sns

from    sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

### OBSERVATIONS:

1.  numpy ------------->   Computation of numerical array

2.  pandas ------------>   Data Creation and Manipulation

3.  matplotlib -------->   Data Visualization

4.  seaborn   --------->   Data Correlation

5.  CountVectorizer ---->  Converts the text into the matrix of word counts

6.  TfidfVectorizer -----> Vonverts the text into the matrix of Tfidf scores

### Step 2:  Create Sample Corpus

In [63]:
# Define a small collection of text documents
corpus = [
    "I love data science",
    "Data science is amazing",
    "I love machine learning",
    "Machine learning and data science are related"
]

### OBSERVATIONS:

1.  corpus → A list of documents (sentences).

2.  Each sentence will be converted into numerical features.

### Step 3: Apply CountVectorizer (Bag of Words)

In [64]:
### Create the object for Bag of Words Model

count = CountVectorizer()

### Fit and transform the corpus text
X = count.fit_transform(corpus)

print(X)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 17 stored elements and shape (4, 10)>
  Coords	Values
  (0, 6)	1
  (0, 3)	1
  (0, 9)	1
  (1, 3)	1
  (1, 9)	1
  (1, 4)	1
  (1, 0)	1
  (2, 6)	1
  (2, 7)	1
  (2, 5)	1
  (3, 3)	1
  (3, 9)	1
  (3, 7)	1
  (3, 5)	1
  (3, 1)	1
  (3, 2)	1
  (3, 8)	1


### OBSERVATIONS:

1. The object for the Bag Of Model is created.

2. Using the bag of model object, we have transformed the corpus text into the matrix of word counts.

3. It has maximum of non-zero values.

4. It needs to be converted into the numpy array for better view and visibility

5. It helps in tokenizing, removing the punctuations and building the vocabulary.

In [65]:
### Convert the matrix of word count into numpy array for better view

X = X.toarray()


print(X)

[[0 0 0 1 0 0 1 0 0 1]
 [1 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 0 1 1 1 0 0]
 [0 1 1 1 0 1 0 1 1 1]]


### OBSERVATIONS:

1. The sparse matrix is converted into the numpy array for better view and visibility.

2. This numpy array can be easily be trained in any model as an input.

3. every row represents every sentence in the corpus and the words mentioned in each corpus text is marked as '1' as the rest is marked as '0'.

### Step 4;  Apply TfidfVectorizer

In [66]:
### Create the object for Tfidfvectorizer

tfidf = TfidfVectorizer()

### using the object for tfidf vectorizer , transform the text

X = tfidf.fit_transform(corpus)

print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 17 stored elements and shape (4, 10)>
  Coords	Values
  (0, 6)	0.6578293132998527
  (0, 3)	0.5325695234255544
  (0, 9)	0.5325695234255544
  (1, 3)	0.38044393252779135
  (1, 9)	0.38044393252779135
  (1, 4)	0.5960389368177127
  (1, 0)	0.5960389368177127
  (2, 6)	0.5773502691896257
  (2, 7)	0.5773502691896257
  (2, 5)	0.5773502691896257
  (3, 3)	0.28380912750743487
  (3, 9)	0.28380912750743487
  (3, 7)	0.35056073478553806
  (3, 5)	0.35056073478553806
  (3, 1)	0.4446418411636436
  (3, 2)	0.4446418411636436
  (3, 8)	0.4446418411636436


### OBSERVATIONS:

1. The object for Tfidf Vectprizer is created.

2. It depicts 

     (a.)  how many times a particular term appears in the document

     (b.)  how unique a term appears across the entire corpus text

3. It converts the corpus text into the matrix of Tfidf scores.

### Which is more important ?

1.  Tfidf Vectorizer is more important than the Count Vectorizer. (Advantages of Tfidf Vectorizer) This is because of the following reasons:---

    (a.)   It can handle the common words in a better way

    (b.)   better handles the classification tasks

    (c.)   reduces the noise


3. The main disadvantages of Count Vectorizer is :-----

   (a.)   Frequency is a problem in which a word occuring more than once.

   (b.)   It cannot handle the deep learning models

   (c.)   It cannot word with the large datasets