### Word-Embeddings:

Word-Embeddings are the  numerical dense valued representations of the words in the text. It helps in finding out the similarity between two words in the text and the similar words have the same dense vector values.

It helps in finding out the relation between the words in the text.

It captures the similarity between the two words in the text in the form of vectors.


### Importances of Word-Embeddings:---

1. It is used to find out the similarity score between two word in the text in the form of dense dimensional vectors.

2. It is used to find out the meaning behind every text.

3. It is useful for dimensionality reduction.

4. It is used to improve the accuracy and the performance of the model

5. It helps in finding out the relation between the words in th etext and even finds out which words are more similar. It is also represented in the form of similarity score dense dimensional vectors.



Ex:---

1.   king - man + woman = queen

### Write a simple end to end implementation based on Word Embeddings


#### Steps used in this Algorithm :----

1.   Import all the necessary libraries

2.   Download all the necessary libraries for NLTK

3.   Define the corpus text

4.   Perform the normalization of the text

5.   Perform the Word tokenization on the text

6.   Train the Word2Vec Model

7.   Explore Word Vectors

8.   Find out the vector representation of the words that are most similar to the words 'and' and 'machine'

9.   To show the list of all the words that the model has learnt for embedding

### Step 1: Import all the necessary libraries

In [459]:
import  numpy   as   np

from    nltk.tokenize   import  word_tokenize

from    gensim.models   import Word2Vec

import  nltk

### OBSERVATIONS:

1.  numpy ------------->  Computation of numerical array

2.  word_tokenize ------>  breaks the sentences into words

3.  gensim ------------>  a module used for embedding

4.  Word2Vec ---------->  finds out the relation between the word and mentions the relation in form of numerical dense dimensional vector

### Step 2: Download all the necessary libraries for NLTK

In [460]:
nltk.download('punkt_tab')

nltk.download('average_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Error loading average_perceptron_tagger_eng: Package
[nltk_data]     'average_perceptron_tagger_eng' not found in index


False

### OBSERVATIONS:

1. Here we are downloading the additional resources needed for NLTK libraries

    (a.)  punkt_tab ----------->  Tokenization model

    (b.)  average_perceptron_tagger_eng  ---------->  POS Tagging Model

### Step 3:  Define the corpus text

In [461]:
corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]

In [462]:
corpus

['Natural Language Processing and Machine Learning are closely related fields.',
 'Word embeddings are a type of word representation that allows words to be represented as vectors.',
 'Deep learning models are used for creating high-quality word embeddings.',
 'The meaning of words can be captured by training on large text datasets.',
 'Gensim is a popular library for training Word2Vec models in Python.']

### OBSERVATIONS:

1.  A corpus ia a container that has a series of sentences needed for text preprocessing.

### Step 4: Perform the normalization of the text

In [463]:
### convert the courpus in list to string

corpus = " ".join(corpus)

In [464]:
from  nltk.tokenize  import RegexpTokenizer

### Create the object for Regular Expression Tokenizer

reg = RegexpTokenizer(r'\w+')


### using the object for Regular Expression Tokenizer, normalize the text

ans = reg.tokenize(corpus)

print(ans)


['Natural', 'Language', 'Processing', 'and', 'Machine', 'Learning', 'are', 'closely', 'related', 'fields', 'Word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', 'Deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high', 'quality', 'word', 'embeddings', 'The', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', 'Gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'Word2Vec', 'models', 'in', 'Python']


### OBSERVATIONS:

1. Now using Regular Expression Tokenizer, all the punctuations and special symbols have been removed from the text.

### Step 5: Perform the Word tokenization on the text

In [465]:
### Word Tokenization breaks the sentences into words. So the input is in the form of text

ans = " ".join(ans)

In [466]:
ans

'Natural Language Processing and Machine Learning are closely related fields Word embeddings are a type of word representation that allows words to be represented as vectors Deep learning models are used for creating high quality word embeddings The meaning of words can be captured by training on large text datasets Gensim is a popular library for training Word2Vec models in Python'

In [467]:
from nltk.tokenize  import word_tokenize


words = word_tokenize(ans)

In [468]:
print(words)

['Natural', 'Language', 'Processing', 'and', 'Machine', 'Learning', 'are', 'closely', 'related', 'fields', 'Word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', 'Deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high', 'quality', 'word', 'embeddings', 'The', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', 'Gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'Word2Vec', 'models', 'in', 'Python']


In [469]:
corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]


### For the Word2Vec model, the input must be in the form of list of sentences

tokenized_sentences = [ word_tokenize(x.lower()) for x in corpus]

print(tokenized_sentences)


[['natural', 'language', 'processing', 'and', 'machine', 'learning', 'are', 'closely', 'related', 'fields', '.'], ['word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', '.'], ['deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high-quality', 'word', 'embeddings', '.'], ['the', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', '.'], ['gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'word2vec', 'models', 'in', 'python', '.']]


### Step 6: Train the Word2Vec Model

In [470]:
cbow_model = Word2Vec(
    sentences           =           tokenized_sentences           ,         ### all inputs in form of list of sentences
    vector_size         =               50                        ,         ### every word tokens is in dense dimensional vectors
    window              =               3                         ,         ### size of the context word needed for embedding
    min_count           =               1                         ,         ### keeps all the words onnce with frequency  < 1
    sg                  =               0                         ,         ### sg defines the tyupe of architecture
    epochs              =             100                                   ### no of iteraations needed to train the model
)

In [471]:
cbow_model

### OBSERVATIONS:

1. The object for cbow model is created

2. The model is trained with the help of following parameters:---

    (a.)  sentences -------->  tokenized words (It accepts the tokenized words as the input)

    (b.)  vector_size ------>  Every tokenized input is in form of 50 size dense dimensional vectors

    (c.)  window     -------> size of the context input embeddings

    (d.)  min_count ---------> keeps all the input context embeddings as intact

    (e.)  sg ----------------> If sg = 0 then Continuous Bag Of Words

                               takes every context input
                                
                               converts every input into dense embedding vectors

                               considers every input vector in 1d row vector

                               take the average to find out the target word using the context wod

    (f.) epochs = 100 -----------> 100 iteartions needed to tarin the model

### Step 7:  Explore Word Vectors


In [472]:
### Get the numerical dense dimensional representation of the 'Natural' of size 50

cbow_model.wv['natural']

array([ 0.00699806,  0.00469796,  0.01108254,  0.01569879, -0.01242217,
        0.01562483,  0.01341129,  0.02114157,  0.00826154, -0.00840245,
       -0.00803872, -0.0024587 , -0.00141286,  0.02039655,  0.00273099,
        0.00932626,  0.00830445, -0.01621871,  0.01216197,  0.01455295,
       -0.00260283,  0.00551177, -0.01120573, -0.01162836,  0.01644766,
       -0.00464357,  0.01297208,  0.00513226, -0.00401876,  0.00629348,
       -0.00951927, -0.00496117,  0.00329364,  0.00802115, -0.0031375 ,
        0.00164507, -0.01367713,  0.01896198, -0.01835306,  0.01440091,
        0.01012293, -0.0143893 , -0.01136863, -0.0143218 , -0.00856171,
        0.01328081,  0.01916406,  0.00350576,  0.00128381,  0.01994897],
      dtype=float32)

### OBSERVATIONS:

1. The word 'natural' is represented in the form of numerical dense dimensisonal vector of size 50

In [473]:
cbow_model.wv['and']

array([ 0.00018774,  0.0090975 ,  0.00483873,  0.02077695,  0.00037773,
       -0.01141587, -0.00036813,  0.00639544, -0.00805818, -0.01825272,
       -0.01182912, -0.01532571,  0.01545134,  0.00883123,  0.01715365,
        0.0151855 , -0.00994112,  0.0078078 ,  0.01504973,  0.00072297,
        0.00741111,  0.0129896 , -0.01509411,  0.0189632 ,  0.013627  ,
        0.01904808, -0.01716955,  0.01510367,  0.01333817, -0.00276821,
       -0.01487494,  0.0085975 , -0.01309427, -0.01296896,  0.00653372,
        0.01653673,  0.02061739, -0.00869386, -0.01938032,  0.01941955,
        0.01604813, -0.00865967, -0.01779248, -0.00709295, -0.00549124,
       -0.00767929,  0.00133798, -0.00175478, -0.00598082, -0.0106355 ],
      dtype=float32)

### OBSERVATIONS:

1. The word 'and' is represented in the form of numerical dense dimensional vector of the size 50

In [474]:
cbow_model.wv['machine']

array([ 1.38767501e-02,  1.27547709e-02, -1.94403455e-02,  7.10700080e-03,
       -1.30583849e-02, -1.88706126e-02,  2.37601483e-03,  1.51365413e-03,
       -1.54858893e-02, -1.52489319e-02, -5.61180850e-03,  1.24633871e-02,
       -1.23069454e-02,  1.63674857e-02,  2.08636593e-05,  4.30864701e-03,
        2.13472918e-02,  1.16836606e-02, -9.04008280e-03,  4.99267038e-03,
        8.19391292e-03,  1.39079476e-02,  2.84056971e-03, -8.08171555e-03,
        2.72642379e-03, -8.81033670e-03,  1.97464367e-03,  1.27054192e-02,
        1.05124600e-02,  1.86052434e-02, -1.72608197e-02, -1.30702471e-02,
        1.37978848e-02,  1.97771340e-04, -1.37183741e-02,  2.25852989e-03,
        8.79017171e-03, -5.04150009e-03, -1.11420834e-02,  1.01354253e-02,
        2.26622969e-02, -1.54554360e-02, -1.14744401e-03, -2.99247587e-03,
       -1.05237961e-02, -4.00301535e-03, -1.06647415e-02,  1.71461608e-02,
       -1.16504729e-02,  8.87040980e-03], dtype=float32)

### OBSERVATIONS:

1. The word 'machine' is represented in the form of numerical dense dimensional vector of the size 50

### Step 8: Find out the vector representation of the words that are most similar to the words 'and' and 'machine'

In [475]:
cbow_model.wv['and']

array([ 0.00018774,  0.0090975 ,  0.00483873,  0.02077695,  0.00037773,
       -0.01141587, -0.00036813,  0.00639544, -0.00805818, -0.01825272,
       -0.01182912, -0.01532571,  0.01545134,  0.00883123,  0.01715365,
        0.0151855 , -0.00994112,  0.0078078 ,  0.01504973,  0.00072297,
        0.00741111,  0.0129896 , -0.01509411,  0.0189632 ,  0.013627  ,
        0.01904808, -0.01716955,  0.01510367,  0.01333817, -0.00276821,
       -0.01487494,  0.0085975 , -0.01309427, -0.01296896,  0.00653372,
        0.01653673,  0.02061739, -0.00869386, -0.01938032,  0.01941955,
        0.01604813, -0.00865967, -0.01779248, -0.00709295, -0.00549124,
       -0.00767929,  0.00133798, -0.00175478, -0.00598082, -0.0106355 ],
      dtype=float32)

In [476]:
### Most similar to 'and'

cbow_model.wv.most_similar('and')

[('used', 0.3690727949142456),
 ('by', 0.31513360142707825),
 ('are', 0.2984626293182373),
 ('a', 0.2782883644104004),
 ('related', 0.2708548903465271),
 ('to', 0.26222237944602966),
 ('be', 0.23448440432548523),
 ('processing', 0.23242348432540894),
 ('machine', 0.23120737075805664),
 ('language', 0.2278352528810501)]

### OBSERVATIONS:

1. All the above words are the most similar w.r.to the word 'and' as their vector values are similar w.r.to 'and'

In [477]:
cbow_model.wv['machine']

array([ 1.38767501e-02,  1.27547709e-02, -1.94403455e-02,  7.10700080e-03,
       -1.30583849e-02, -1.88706126e-02,  2.37601483e-03,  1.51365413e-03,
       -1.54858893e-02, -1.52489319e-02, -5.61180850e-03,  1.24633871e-02,
       -1.23069454e-02,  1.63674857e-02,  2.08636593e-05,  4.30864701e-03,
        2.13472918e-02,  1.16836606e-02, -9.04008280e-03,  4.99267038e-03,
        8.19391292e-03,  1.39079476e-02,  2.84056971e-03, -8.08171555e-03,
        2.72642379e-03, -8.81033670e-03,  1.97464367e-03,  1.27054192e-02,
        1.05124600e-02,  1.86052434e-02, -1.72608197e-02, -1.30702471e-02,
        1.37978848e-02,  1.97771340e-04, -1.37183741e-02,  2.25852989e-03,
        8.79017171e-03, -5.04150009e-03, -1.11420834e-02,  1.01354253e-02,
        2.26622969e-02, -1.54554360e-02, -1.14744401e-03, -2.99247587e-03,
       -1.05237961e-02, -4.00301535e-03, -1.06647415e-02,  1.71461608e-02,
       -1.16504729e-02,  8.87040980e-03], dtype=float32)

In [478]:
### Most similar to 'machine'

cbow_model.wv.most_similar('machine')

[('.', 0.3434886634349823),
 ('a', 0.3294759690761566),
 ('natural', 0.25562813878059387),
 ('word2vec', 0.2532128691673279),
 ('are', 0.24818044900894165),
 ('processing', 0.2366793304681778),
 ('and', 0.23120737075805664),
 ('creating', 0.22531941533088684),
 ('in', 0.20836141705513),
 ('high-quality', 0.20542047917842865)]

### OBSERVATIONS:

1. All the above words are the most similar w.r.to the word 'machine' as their vector values are similar w.r.to 'machine'

### Step 9: To show the list of all the words that the model has learnt for embedding

In [479]:
cbow_model.wv.key_to_index

{'.': 0,
 'word': 1,
 'are': 2,
 'training': 3,
 'for': 4,
 'models': 5,
 'be': 6,
 'words': 7,
 'of': 8,
 'a': 9,
 'embeddings': 10,
 'learning': 11,
 'python': 12,
 'in': 13,
 'word2vec': 14,
 'library': 15,
 'popular': 16,
 'is': 17,
 'gensim': 18,
 'datasets': 19,
 'text': 20,
 'large': 21,
 'on': 22,
 'by': 23,
 'captured': 24,
 'can': 25,
 'meaning': 26,
 'the': 27,
 'high-quality': 28,
 'creating': 29,
 'used': 30,
 'deep': 31,
 'vectors': 32,
 'as': 33,
 'represented': 34,
 'to': 35,
 'allows': 36,
 'that': 37,
 'representation': 38,
 'type': 39,
 'fields': 40,
 'related': 41,
 'closely': 42,
 'machine': 43,
 'and': 44,
 'processing': 45,
 'language': 46,
 'natural': 47}

### OBSERVATIONS:

1. key_to_index ---> It helps in mapping every word present in the vocabulary to its unique integer index that is trained using the Word2Vec Model.