### Word-Embeddings:

Word-Embeddings are the  numerical dense valued representations of the words in the text. It helps in finding out the similarity between two words in the text and the similar words have the same dense vector values.

It helps in finding out the relation between the words in the text.

It captures the similarity between the two words in the text in the form of vectors.


### Importances of Word-Embeddings:---

1. It is used to find out the similarity score between two word in the text in the form of dense dimensional vectors.

2. It is used to find out the meaning behind every text.

3. It is useful for dimensionality reduction.

4. It is used to improve the accuracy and the performance of the model

5. It helps in finding out the relation between the words in th etext and even finds out which words are more similar. It is also represented in the form of similarity score dense dimensional vectors.



Ex:---

1.   king - man + woman = queen


### Write a simple end to end implementation based on Word Embeddings based on Skip-Grams


#### Steps used in this Algorithm :----

1.   Import all the necessary libraries

2.   Download all the necessary libraries for NLTK

3.   Define the corpus text

4.   Perform the normalization of the text

5.   Perform the Word tokenization on the text

6.   Train the Word2Vec Model based on Skip-Grams

7.   Explore Word Vectors

8.   Find out the vector representation of the words that are most similar to the words 'and' and 'machine'

9.   To show the list of all the words that the model has learnt for embedding

### Step 1: Import all the necessary libraries

In [203]:
import  nltk  

from    nltk.tokenize  import   word_tokenize

from    gensim.models  import   Word2Vec

import  numpy   as   np

### OBSERVATIONS:

1.  nltk ------------->   Library used for text preprocessing

2.  tokenize --------->   used for breaking the text into smaller parts

3.  word_tokenize ---->   breaks the sentences into words

4.  gensim ----------->   model used for embedding

5.  Word2Vec -----------> converts each word into numerical dense dimensional vector and depicts the relationship between them

6.  numpy ------------->  Computation of numerical array

### Step 2:  Download all the necessary libraries for NLTK

In [204]:
nltk.download('punkt_tab')

nltk.download('average_perceptron_tagger_eng')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Error loading average_perceptron_tagger_eng: Package
[nltk_data]     'average_perceptron_tagger_eng' not found in index


False

### OBSEREVATIONS:

1.  Here we are downloading the necessary libraries needed for NLTK.

    (a.)   punkt_tab ------------>  Tokenization model

    (b.)   average_perceptron_tagger_eng ------------>  POS Tagging Model

### Step 3: Define the corpus text

In [205]:
corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]

In [206]:
corpus

['Natural Language Processing and Machine Learning are closely related fields.',
 'Word embeddings are a type of word representation that allows words to be represented as vectors.',
 'Deep learning models are used for creating high-quality word embeddings.',
 'The meaning of words can be captured by training on large text datasets.',
 'Gensim is a popular library for training Word2Vec models in Python.']

### OBSERVATIONS:

1.  The corpus is the dataset that contains the set of sentences used for text processing.

### Step 4:  Perform the normalization of the text

In [207]:
from nltk.tokenize import RegexpTokenizer


### Create an object for RegexpTokenizer

reg = RegexpTokenizer(r'\w+')




### Accept the input in the form of string

corpus = " ".join(corpus)

### using the object for Regular Expression Tokenizer, normalize the text

res = reg.tokenize(corpus)

print(res)

### Again convert the list to strings

res = " ".join(res)

print(res)

['Natural', 'Language', 'Processing', 'and', 'Machine', 'Learning', 'are', 'closely', 'related', 'fields', 'Word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', 'Deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high', 'quality', 'word', 'embeddings', 'The', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', 'Gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'Word2Vec', 'models', 'in', 'Python']
Natural Language Processing and Machine Learning are closely related fields Word embeddings are a type of word representation that allows words to be represented as vectors Deep learning models are used for creating high quality word embeddings The meaning of words can be captured by training on large text datasets Gensim is a popular library for training Word2Vec models in Python


### Step 5:  Perform the Word tokenization on the text

In [208]:
from nltk.tokenize import word_tokenize

words = word_tokenize(res)

print(words)

['Natural', 'Language', 'Processing', 'and', 'Machine', 'Learning', 'are', 'closely', 'related', 'fields', 'Word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', 'Deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high', 'quality', 'word', 'embeddings', 'The', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', 'Gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'Word2Vec', 'models', 'in', 'Python']


### Step 6: Train the Word2Vec Model based on Skip-Grams

In [209]:
corpus = [
    "Natural Language Processing and Machine Learning are closely related fields.",
    "Word embeddings are a type of word representation that allows words to be represented as vectors.",
    "Deep learning models are used for creating high-quality word embeddings.",
    "The meaning of words can be captured by training on large text datasets.",
    "Gensim is a popular library for training Word2Vec models in Python."
]

tokenized_sentences = [word_tokenize(x.lower()) for x in corpus]

print(tokenized_sentences)

[['natural', 'language', 'processing', 'and', 'machine', 'learning', 'are', 'closely', 'related', 'fields', '.'], ['word', 'embeddings', 'are', 'a', 'type', 'of', 'word', 'representation', 'that', 'allows', 'words', 'to', 'be', 'represented', 'as', 'vectors', '.'], ['deep', 'learning', 'models', 'are', 'used', 'for', 'creating', 'high-quality', 'word', 'embeddings', '.'], ['the', 'meaning', 'of', 'words', 'can', 'be', 'captured', 'by', 'training', 'on', 'large', 'text', 'datasets', '.'], ['gensim', 'is', 'a', 'popular', 'library', 'for', 'training', 'word2vec', 'models', 'in', 'python', '.']]


In [210]:
### Train the Word2Vec Model using Skip-Grams

skipgrams_model = Word2Vec(
    sentences        =             tokenized_sentences           ,
    vector_size      =                50                         ,
    window           =                 3                         ,
    min_count        =                 1                         ,
    sg               =                 1                         ,
    epochs           =              100
)

In [211]:
skipgrams_model

### OBSERVATIONS:

1. The skip-grams model has been trained with the help of the following input parameters:---

   (a.)    sentences -------> tokenized_sentences . It contains all the sentences in the form of list of sentences with tokens

   (b.)    vector_size = 50 ----------> Each and every input word is converted into numerical dense dimensional vector of size 50

   (c.)    window = 3     ------------> Total inputs for context input is 3 needed for embedding.

   (d.)    min_count = 1 -------------> combine all the context input whose frequency is less than 1.

   (e.)    sg = 1      ---------------> The type of model architecture used is Skip-Grams that predict the context input from the target input

   (f.)    epochs = 100 ---------------> 100 iterations is needed to train the model.

### Step 7:  Explore Word Vectors

In [212]:
### Get the numerical dense dimensional representation of the 'Natural' of size 50

skipgrams_model.wv['natural']

array([ 0.00735378,  0.00497393,  0.01114157,  0.01594871, -0.01240279,
        0.01517002,  0.01622976,  0.02488607,  0.007512  , -0.01110035,
       -0.00865914, -0.00417537,  0.00180949,  0.02212013,  0.00360116,
        0.0115539 ,  0.01197331, -0.01301393,  0.0101827 ,  0.01140497,
       -0.00013241,  0.00652788, -0.00716085, -0.01081918,  0.01669241,
       -0.00234791,  0.01293053,  0.00885004, -0.00451266,  0.00574325,
       -0.01230733, -0.00705541,  0.00379279,  0.00600469, -0.00319157,
        0.00208915, -0.01008951,  0.01859779, -0.0193346 ,  0.0138065 ,
        0.01430457, -0.01492667, -0.0115025 , -0.01158754, -0.0054677 ,
        0.01225077,  0.01911482,  0.00240991,  0.00264861,  0.02230951],
      dtype=float32)

### OBSERVATIONS:

1. We have obtained the numerical dense dimensional vector for the word 'natural' of the size 50.

In [213]:
### Get the numerical dense dimensional representation of the 'and' of size 50

skipgrams_model.wv['and']

array([ 7.76391884e-04,  9.13006905e-03,  4.92043234e-03,  2.16485839e-02,
        3.67378561e-05, -1.14126895e-02,  3.65891145e-03,  1.16187232e-02,
       -9.19059757e-03, -2.18484420e-02, -1.32288588e-02, -1.69963464e-02,
        1.99381914e-02,  1.11467065e-02,  1.79607235e-02,  1.81943681e-02,
       -5.48013020e-03,  1.20153315e-02,  1.25141107e-02, -3.99846351e-03,
        1.08411601e-02,  1.44450553e-02, -9.62403044e-03,  2.03738566e-02,
        1.39736291e-02,  2.21483465e-02, -1.73616484e-02,  2.04764623e-02,
        1.22453421e-02, -2.82903155e-03, -1.87412500e-02,  6.22507511e-03,
       -1.21589610e-02, -1.61428545e-02,  6.14509825e-03,  1.72968823e-02,
        2.51329802e-02, -9.67694167e-03, -2.09322739e-02,  1.90725122e-02,
        2.16437131e-02, -9.07084811e-03, -1.84230395e-02, -3.08223884e-03,
       -8.95738485e-04, -9.18841735e-03,  9.08656744e-04, -3.82377347e-03,
       -4.78508603e-03, -7.82969035e-03], dtype=float32)

### OBSERVATIONS:

1. We have obtained the numerical dense dimensional vector for the word 'and' of the size 50.

In [214]:
### Get the numerical dense dimensional representation of the 'machine' of size 50

skipgrams_model.wv['machine']

array([ 0.01449395,  0.01274676, -0.01908677,  0.00811913, -0.01309085,
       -0.01845687,  0.00691228,  0.00757935, -0.01610652, -0.01883319,
       -0.00672934,  0.01057118, -0.00780058,  0.01911717,  0.00090596,
        0.00747844,  0.02598679,  0.0165633 , -0.01177003, -0.0002098 ,
        0.01229269,  0.01556609,  0.00862363, -0.00683072,  0.00299018,
       -0.00575807,  0.0019207 ,  0.01826918,  0.00919217,  0.0179157 ,
       -0.0222159 , -0.01529316,  0.01461737, -0.00303525, -0.01417821,
        0.00309936,  0.01374001, -0.0056397 , -0.01244262,  0.00963698,
        0.02909352, -0.01626427, -0.00224196,  0.00165029, -0.00580131,
       -0.00549196, -0.01131593,  0.01492768, -0.0099291 ,  0.01232163],
      dtype=float32)

### OBSERVATIONS:

1. We have obtained the numerical dense dimensional vector for the word 'machine' of the size 50.

### Step 8: Find out the vector representation of the words that are most similar to the words 'and' and 'machine'

In [215]:
### Dense dimensional vectors for the words that are most similar to 'and'

skipgrams_model.wv.most_similar('and')

[('are', 0.4520156681537628),
 ('used', 0.45019078254699707),
 ('by', 0.43641555309295654),
 ('a', 0.4132101535797119),
 ('related', 0.4129936397075653),
 ('be', 0.40556907653808594),
 ('to', 0.38448694348335266),
 ('word2vec', 0.3798808753490448),
 ('machine', 0.37022748589515686),
 ('learning', 0.36773473024368286)]

### OBSERVATIONS:

1. All the above words are the most similar w.r.to the word 'and' as their vector values are similar w.r.to 'and'

In [216]:
### Dense dimensional vectors for the words that are most similar to 'machine'

skipgrams_model.wv.most_similar('machine')

[('.', 0.5157498717308044),
 ('a', 0.46377620100975037),
 ('are', 0.43209725618362427),
 ('word2vec', 0.42735937237739563),
 ('creating', 0.3958236575126648),
 ('high-quality', 0.3800097107887268),
 ('and', 0.37022748589515686),
 ('word', 0.3700869083404541),
 ('processing', 0.3548687994480133),
 ('training', 0.3465283215045929)]

### OBSERVATIONS:

1. All the above words are the most similar w.r.to the word 'machine' as their vector values are similar w.r.to 'machine'

### Step 9: To show the list of all the words that the model has learnt for embedding

In [217]:
skipgrams_model.wv.key_to_index

{'.': 0,
 'word': 1,
 'are': 2,
 'training': 3,
 'for': 4,
 'models': 5,
 'be': 6,
 'words': 7,
 'of': 8,
 'a': 9,
 'embeddings': 10,
 'learning': 11,
 'python': 12,
 'in': 13,
 'word2vec': 14,
 'library': 15,
 'popular': 16,
 'is': 17,
 'gensim': 18,
 'datasets': 19,
 'text': 20,
 'large': 21,
 'on': 22,
 'by': 23,
 'captured': 24,
 'can': 25,
 'meaning': 26,
 'the': 27,
 'high-quality': 28,
 'creating': 29,
 'used': 30,
 'deep': 31,
 'vectors': 32,
 'as': 33,
 'represented': 34,
 'to': 35,
 'allows': 36,
 'that': 37,
 'representation': 38,
 'type': 39,
 'fields': 40,
 'related': 41,
 'closely': 42,
 'machine': 43,
 'and': 44,
 'processing': 45,
 'language': 46,
 'natural': 47}

### OBSERVATIONS:

1. key_to_index ---> It helps in mapping every word present in the vocabulary to its unique integer index that is trained using the Word2Vec Model.